[build]
  base    = "thrivehaus-app"
  command = "npm run build"
  publish = "thrivehaus-app/.next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
