import type { Culture } from './types';

export const cultures: Culture[] = [
  {
    id: 'filipino',
    name: 'Filipino',
    emoji: '🇵🇭',
    tagline: 'The hearty, sour, and savory soul of Southeast Asia',
    description:
      'Filipino cuisine is a vibrant blend of Malay, Chinese, Spanish, and American influences, shaped by over 7,000 islands and centuries of trade. It celebrates bold contrasts — sour and salty, sweet and savory — with fermented ingredients, vinegar-braises, and tropical fruits at its core.',
    region: 'Southeast Asia',
    country: 'Philippines',
    commonIngredients: [
      'Vinegar', 'Soy sauce', 'Garlic', 'Pork belly', 'Fish sauce (patis)',
      'Calamansi lime', 'Coconut milk', 'Tamarind', 'Banana blossom', 'Bagoong (shrimp paste)',
      'Lemongrass', 'Annatto seeds', 'Longanisa', 'Rice', 'Palm sugar',
    ],
    recipeIds: ['adobo', 'sinigang', 'pancit'],
    geographyNotes:
      'The Philippines is an archipelago of 7,641 islands in Southeast Asia, bordered by the South China Sea to the west, the Philippine Sea to the east, and the Celebes Sea to the south. The country sits along the Pacific Ring of Fire.',
    foodHistory:
      'Pre-colonial Filipino cuisine centered on rice, seafood, and tropical produce. Spanish colonization (1565–1898) introduced tomatoes, corn, chiles, and stewing techniques. Chinese traders brought noodles, tofu, and soy sauce. American influence added canned goods and fast food culture. Today, Filipino cuisine is experiencing a global renaissance led by chefs celebrating ancestral ingredients.',
    nutritionThemes: [
      'High in protein from fish, pork, and chicken',
      'Rich in probiotics from fermented ingredients',
      'Abundant tropical fruit antioxidants',
      'Complex carbohydrates from rice',
      'Heart-healthy coconut',
    ],
    primaryColor: '#D4393B',
    accentColor: '#FCD116',
    bgGradient: 'from-red-50 to-yellow-50',
    mapFact: 'The Philippines spans over 300,000 km² and has more than 175 spoken languages.',
    languages: ['Filipino (Tagalog)', 'English', 'Cebuano', 'Ilocano'],
    population: '115 million',
    connections: [
      {
        cultureId: 'mexican',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'Both colonies of Spain',
        detail: 'Spain ruled the Philippines (1565–1898) and Mexico simultaneously, and the Manila-Acapulco Galleon Trade directly linked the two. Longanisa sausage mirrors Mexican chorizo; adobo mirrors Spanish-Mexican braising techniques. Filipino rice cakes echo Mexican tamales.',
        sharedIngredients: ['Vinegar', 'Pork belly', 'Garlic', 'Annatto seeds'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Southeast Asian neighbors',
        detail: 'Filipino and Vietnamese kitchens share the same tropical pantry: fish sauce, tamarind, lemongrass, and coconut milk. Both cuisines use sour and umami contrasts as their backbone. Sinigang\'s sour broth echoes canh chua; patis mirrors nước mắm.',
        sharedIngredients: ['Fish sauce', 'Tamarind', 'Lemongrass', 'Coconut milk', 'Rice'],
      },
      {
        cultureId: 'indian',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Spice route connections',
        detail: 'Indian traders sailed to the Philippines for centuries before European colonization. Coconut milk, tamarind, and turmeric appear in both kitchens. The Philippine term "kari" (curry) traces directly to South Indian trade influence.',
        sharedIngredients: ['Coconut milk', 'Tamarind', 'Turmeric', 'Ginger'],
      },
    ],
  },
  {
    id: 'mexican',
    name: 'Mexican',
    emoji: '🇲🇽',
    tagline: 'Ancient corn civilizations meet Spanish fire and flavor',
    description:
      'Mexican cuisine — a UNESCO Intangible Cultural Heritage — is one of the world\'s most complex culinary traditions. Built on the "Three Sisters" of corn, beans, and squash, it layers indigenous Aztec and Maya traditions with Spanish, Caribbean, and African influences into layers of chile-spiced, slow-cooked brilliance.',
    region: 'North America / Mesoamerica',
    country: 'Mexico',
    commonIngredients: [
      'Corn (masa, tortillas)', 'Dried chile peppers', 'Tomatoes & tomatillos', 'Avocado',
      'Black beans & pinto beans', 'Cilantro', 'Lime', 'Cumin', 'Epazote', 'Mexican oregano',
      'Chocolate (cacao)', 'Pumpkin seeds (pepitas)', 'Chayote', 'Nopales (cactus)', 'Queso fresco',
    ],
    recipeIds: ['tamales', 'mole', 'horchata'],
    geographyNotes:
      'Mexico sits in North America, bordered by the US to the north, the Pacific Ocean to the west, and the Gulf of Mexico and Caribbean Sea to the east. It spans diverse biomes from desert highlands to tropical coasts.',
    foodHistory:
      'Mexican food traces back 9,000 years to ancient Mesoamerican civilizations who domesticated corn. The Aztec empire cultivated cacao, vanilla, and tomatoes unknown to the rest of the world. Spanish conquistadors (1519) merged these with Mediterranean ingredients, creating "mestizo" cuisine. Each of Mexico\'s 32 states has distinct culinary traditions.',
    nutritionThemes: [
      'Complete protein from corn + beans combination',
      'Lycopene-rich tomatoes and tomatillos',
      'Monounsaturated fats from avocado',
      'Antioxidants from dark chocolate and chiles',
      'High fiber from legumes and vegetables',
    ],
    primaryColor: '#006847',
    accentColor: '#CE1126',
    bgGradient: 'from-green-50 to-red-50',
    mapFact: 'Mexico is the 13th largest country by area and home to 68 recognized indigenous languages.',
    languages: ['Spanish', 'Nahuatl', 'Yucatec Maya', 'Zapotec'],
    population: '130 million',
    connections: [
      {
        cultureId: 'filipino',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'Linked by the Manila Galleon',
        detail: 'The Manila-Acapulco Galleon Trade (1565–1815) was the world\'s first transpacific trade route. Mexican silver flowed to Asia; Filipino spices and Chinese goods flowed to Mexico. Annatto (achiote) for color, vinegar-braised meats, and stuffed masa dishes trace this direct exchange.',
        sharedIngredients: ['Annatto seeds', 'Corn', 'Pork', 'Vinegar', 'Chocolate'],
      },
      {
        cultureId: 'southern',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Corn, chiles & African roots',
        detail: 'Both Southern American and Mexican cuisines are built on corn and shaped by African diaspora. Enslaved Africans in both regions transformed Indigenous ingredients. The Gulf Coast border zone blurs into Tex-Mex and Creole — tamales appear in both traditions; chiles crossed into Southern hot sauce culture.',
        sharedIngredients: ['Corn', 'Black-eyed peas', 'Chiles', 'Pork', 'Molasses'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'colonization',
        headline: 'Spanish brought the Mediterranean pantry',
        detail: 'Spanish colonizers who conquered Mexico came from a Mediterranean food tradition. They brought olive oil, wine, wheat, onions, garlic, and livestock (pigs, cattle, chickens) to Mesoamerica — permanently transforming Mexican cuisine and creating "mestizo" cooking.',
        sharedIngredients: ['Garlic', 'Onions', 'Olive oil', 'Wheat', 'Pork'],
      },
    ],
  },
  {
    id: 'vietnamese',
    name: 'Vietnamese',
    emoji: '🇻🇳',
    tagline: 'Fresh herbs, bright broths, and the art of balance',
    description:
      'Vietnamese cuisine is celebrated for its delicate balance of five fundamental tastes: spicy, sour, bitter, salty, and sweet. It emphasizes fresh herbs, minimal oil, and pure flavors. The long, narrow country\'s geography creates three distinct regional cuisines — northern, central, and southern — each with its own character.',
    region: 'Southeast Asia',
    country: 'Vietnam',
    commonIngredients: [
      'Rice noodles (pho, bun)', 'Fish sauce (nuoc mam)', 'Lemongrass', 'Fresh mint & basil',
      'Bean sprouts', 'Lime', 'Star anise', 'Cinnamon', 'Ginger', 'Shallots',
      'Hoisin sauce', 'Sriracha', 'Shrimp paste', 'Jasmine rice', 'Pork belly',
    ],
    recipeIds: ['pho', 'spring-rolls', 'bun-cha'],
    geographyNotes:
      'Vietnam stretches 1,650 km along the eastern edge of the Indochina Peninsula, bordered by China, Laos, Cambodia, and the South China Sea. Its S-shaped coastline and diverse terrain — from the Red River Delta to the Mekong Delta — shapes regional cuisines.',
    foodHistory:
      'Vietnamese cuisine developed over 4,000 years, strongly influenced by Chinese rule (111 BCE–938 CE), which introduced chopsticks, woks, and soy-based sauces. French colonization (1887–1954) added baguettes, pâté, and coffee culture, visible in bánh mì sandwiches. The Vietnamese concept of yin-yang balance in food — cooling and heating ingredients — remains central today.',
    nutritionThemes: [
      'High in fresh vegetables and herbs',
      'Lean protein from seafood and pork',
      'Probiotic-rich fermented ingredients',
      'Low fat cooking methods (steaming, boiling)',
      'Collagen-rich bone broths',
    ],
    primaryColor: '#DA251D',
    accentColor: '#FFCD00',
    bgGradient: 'from-red-50 to-amber-50',
    mapFact: 'Vietnam has over 3,200 km of coastline and is one of the world\'s top rice exporters.',
    languages: ['Vietnamese', 'Khmer', 'Cham', 'Muong'],
    population: '98 million',
    connections: [
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'France left a baguette behind',
        detail: 'French colonization of Vietnam (1887–1954) permanently altered Vietnamese food. Bánh mì is a Vietnamese baguette. Pâté, coffee culture, and custard (bánh flan) are French-Vietnamese fusions. This is one of history\'s most visible colonial food exchanges — a Southeast Asian street food with a Parisian backbone.',
        sharedIngredients: ['Wheat bread', 'Pâté', 'Coffee', 'Caramel'],
      },
      {
        cultureId: 'filipino',
        strength: 'strong',
        linkType: 'geography',
        headline: 'The fish sauce belt',
        detail: 'Vietnam and the Philippines anchor the Southeast Asian fish sauce tradition. Both cultures ferment small fish into their most essential condiment — nước mắm and patis are nearly identical in process and function. Tamarind souring, coconut-based dishes, and fresh herb garnishes connect both kitchens.',
        sharedIngredients: ['Fish sauce', 'Tamarind', 'Rice noodles', 'Bean sprouts', 'Lemongrass'],
      },
      {
        cultureId: 'persian',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Silk Road spice exchange',
        detail: 'The ancient Silk Road carried Persian saffron, dried fruits, and spice-layering techniques eastward through Central Asia into Chinese and Vietnamese kitchens. Star anise — the defining spice of phở — traveled this route. Vietnamese five-spice blends reflect this historic Central Asian spice corridor.',
        sharedIngredients: ['Star anise', 'Cinnamon', 'Ginger', 'Cardamom'],
      },
    ],
  },
  {
    id: 'persian',
    name: 'Persian',
    emoji: '🇮🇷',
    tagline: 'Saffron-gilded poetry on a plate from ancient Persia',
    description:
      'Persian cuisine is one of the world\'s oldest and most sophisticated culinary traditions, dating back 2,500 years to the Achaemenid Empire. It is defined by the artful use of dried fruits, nuts, fragrant rice, and precious spices like saffron, combining sweet and sour notes with incredible complexity and elegance.',
    region: 'Middle East / Central Asia',
    country: 'Iran',
    commonIngredients: [
      'Saffron', 'Rose water', 'Barberries (zereshk)', 'Dried limes (limu omani)',
      'Walnuts', 'Pomegranate molasses', 'Fresh dill, parsley, cilantro, fenugreek',
      'Lamb', 'Long-grain basmati rice', 'Split chickpeas', 'Kashk (whey)',
      'Turmeric', 'Dried apricots', 'Chickpeas', 'Ghee',
    ],
    recipeIds: ['ghormeh-sabzi', 'fesenjan', 'tahdig'],
    geographyNotes:
      'Iran (ancient Persia) spans 1.6 million km² in the Middle East, bordered by Turkey, Iraq, the Caspian Sea, Russia, Turkmenistan, Afghanistan, and Pakistan. Its central plateau, mountain ranges, and diverse climate zones allow extraordinary agricultural diversity.',
    foodHistory:
      'Persian food culture stretches back to the Achaemenid Empire (550–330 BCE), when Persia was the world\'s largest empire. Persian food spread through Silk Road trade routes to influence Indian Mughal cuisine, Ottoman Turkish cooking, and Arab traditions. The concept of the Persian "sofreh" (table spread) as an act of hospitality and generosity remains central to the culture.',
    nutritionThemes: [
      'Rich in omega-3s from walnuts and fish',
      'Antioxidants from pomegranate and saffron',
      'Anti-inflammatory turmeric and herbs',
      'Plant-forward cooking with legumes',
      'Probiotic kashk and fermented dairy',
    ],
    primaryColor: '#239F40',
    accentColor: '#DA0000',
    bgGradient: 'from-green-50 to-rose-50',
    mapFact: 'Iran is home to one of the oldest civilizations on Earth, with settlements dating back 7,000+ years.',
    languages: ['Persian (Farsi)', 'Azerbaijani', 'Kurdish', 'Arabic'],
    population: '87 million',
    connections: [
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'The Mughal Empire merged two cuisines',
        detail: 'The Mughal emperors (1526–1857) were Persian-speaking Central Asians who ruled India for 300 years. They brought Persian rice techniques, saffron, dried fruits, rosewater, and nut-enriched sauces into Indian cooking — and took Indian spices back. Biryani is a direct Persian-Indian fusion. Korma, haleem, and kebab all trace to this empire.',
        sharedIngredients: ['Saffron', 'Basmati rice', 'Ghee', 'Cardamom', 'Rose water', 'Dried fruits'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Ancient empires, shared pantry',
        detail: 'The Persian and Mediterranean worlds overlapped constantly — Persia ruled Greece briefly, Rome traded with Persia, and the Ottoman Empire absorbed both Persian and Mediterranean traditions. Pomegranate, eggplant, lamb, chickpeas, and pistachios flow freely between Persian and Mediterranean kitchens as a result.',
        sharedIngredients: ['Pomegranate', 'Eggplant', 'Lamb', 'Chickpeas', 'Pistachios', 'Lemon'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'The Silk Road ran both ways',
        detail: 'Persia was the commercial hub of the ancient world. Persian merchants carried saffron, dried limes, and layered spice blends east along the Silk Road into Central Asia and eventually into East and Southeast Asian cooking. Star anise traveled west; saffron traveled east. Both kitchens still carry traces of this exchange.',
        sharedIngredients: ['Star anise', 'Cinnamon', 'Cardamom', 'Dried limes', 'Turmeric'],
      },
    ],
  },
  {
    id: 'indian',
    name: 'Indian',
    emoji: '🇮🇳',
    tagline: 'A spice-trader\'s paradise with 5,000 years of flavor',
    description:
      'Indian cuisine is not one cuisine but a vast constellation of regional traditions spanning 28 states, shaped by geography, religion, season, and ancient Ayurvedic principles. From the buttery richness of Punjab to the coconut-laced curries of Kerala, the fiery street food of Mumbai to the delicate vegetarian thalis of Gujarat — India feeds the world\'s culinary imagination.',
    region: 'South Asia',
    country: 'India',
    commonIngredients: [
      'Turmeric', 'Cumin', 'Coriander', 'Cardamom', 'Garam masala', 'Mustard seeds',
      'Ghee', 'Paneer', 'Lentils (dal)', 'Basmati rice', 'Coconut milk', 'Tamarind',
      'Fenugreek seeds', 'Curry leaves', 'Hing (asafoetida)', 'Chana (chickpeas)',
    ],
    recipeIds: ['biryani', 'dal-tadka', 'kheer'],
    geographyNotes:
      'India is the 7th largest country, spanning from the Himalayas in the north to tropical coastlines in the south. The Gangetic Plain, Deccan Plateau, Thar Desert, and coastal regions each produce unique ingredients that define regional cuisines.',
    foodHistory:
      'Indian culinary history spans 5,000+ years, from Indus Valley civilization seeds to Vedic-era cooking texts. The Silk Road brought spices westward to Rome and Europe, making Indian spices the engine of world trade. Mughal emperors (1526–1857) created biryani and korma. British colonization (1858–1947) influenced tea culture. India\'s independence movement was even partly sparked by salt.',
    nutritionThemes: [
      'Complete protein from dal + rice or roti',
      'Anti-inflammatory spice compounds (curcumin)',
      'Probiotic-rich lassi, yogurt, and fermented dosas',
      'Fiber from legumes and vegetables',
      'Ayurvedic balance of six tastes',
    ],
    primaryColor: '#FF9933',
    accentColor: '#138808',
    bgGradient: 'from-orange-50 to-green-50',
    mapFact: 'India is home to over 22 official languages and more than 1,600 dialects.',
    languages: ['Hindi', 'Bengali', 'Tamil', 'Telugu', 'Marathi', 'Urdu', 'English'],
    population: '1.4 billion',
    connections: [
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'Mughal fusion created North Indian cuisine',
        detail: 'Mughal emperors were Persian in language, culture, and taste — and they ruled India for over 300 years. The result is North Indian cuisine as we know it: biryani (Persian layered rice + Indian spices), korma (Persian braising + Indian aromatics), naan (Persian bread), and kebab culture. This is one of history\'s great culinary fusions.',
        sharedIngredients: ['Saffron', 'Basmati rice', 'Cardamom', 'Rose water', 'Ghee', 'Pistachios'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Ancient spice trade neighbors',
        detail: 'Indian traders were sailing to Southeast Asia millennia before Europeans arrived. They carried tamarind, coconut cultivation techniques, turmeric, and curry concepts to the Philippines and beyond. The Tagalog word for "curry" (kari) is Sanskrit. Coconut milk, tamarind souring, and turmeric coloring appear in both cuisines for this reason.',
        sharedIngredients: ['Tamarind', 'Coconut milk', 'Turmeric', 'Ginger', 'Mustard seeds'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Rome\'s most valuable imports came from India',
        detail: 'Roman historian Pliny complained that India was draining Rome\'s treasury through spice purchases. Black pepper, cardamom, and cinnamon — Indian exports — were literally worth more than gold in ancient Rome. This spice trade shaped Mediterranean cooking for 2,000 years and made Indian spices central to European cuisine.',
        sharedIngredients: ['Black pepper', 'Cardamom', 'Cinnamon', 'Turmeric', 'Lentils', 'Chickpeas'],
      },
    ],
  },
  {
    id: 'southern',
    name: 'Southern American',
    emoji: '🌽',
    tagline: 'Soul food, smoke, and the roots of American cooking',
    description:
      'Southern American cuisine is the deeply soulful cooking tradition born from the American South — a fusion of West African, Native American, and European culinary traditions forged through resilience and community. It\'s the food of barbecue pits, church potlucks, Sunday suppers, and front-porch storytelling, rich with history and love in every bite.',
    region: 'North America',
    country: 'United States (South)',
    commonIngredients: [
      'Cornmeal & grits', 'Collard greens', 'Black-eyed peas', 'Sweet potatoes', 'Okra',
      'Buttermilk', 'Lard & bacon fat', 'Smoked pork', 'Hot sauce', 'Molasses',
      'Peanuts', 'Peaches', 'Sorghum syrup', 'Cast iron cookware', 'Church lady seasoning',
    ],
    recipeIds: ['fried-chicken', 'shrimp-grits', 'peach-cobbler'],
    geographyNotes:
      'The American South encompasses states from Virginia to Texas, including the Mississippi River Delta, Appalachian Mountains, Gulf Coast, and Atlantic coastal lowlands. Each sub-region has distinct food traditions: Creole Louisiana, Appalachian cooking, Low Country South Carolina, and Texas BBQ.',
    foodHistory:
      'Southern food is inseparable from the history of African enslavement. Enslaved Africans brought okra, black-eyed peas, rice cultivation, and technique to American kitchens, yet were denied credit for centuries. Native Americans contributed corn, beans, squash, and game. West African, Scottish, Irish, and French settlers each added layers. Modern chefs are now rightfully centering Black Southern culinary heritage.',
    nutritionThemes: [
      'High fiber from beans, peas, and greens',
      'Potassium and vitamins from sweet potatoes',
      'Probiotic-rich fermented hot sauces',
      'Plant diversity in seasonal produce',
      'Iron from cast-iron cooking methods',
    ],
    primaryColor: '#8B4513',
    accentColor: '#DAA520',
    bgGradient: 'from-amber-50 to-orange-50',
    mapFact: 'The Mississippi Delta region is called the "cradle of American music and food culture."',
    languages: ['English', 'Gullah Geechee', 'Louisiana Creole'],
    population: '130 million (US South)',
    connections: [
      {
        cultureId: 'mexican',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Corn culture runs deep in both',
        detail: 'Southern American and Mexican cuisine share corn as their foundation — cornbread mirrors tortillas; grits mirror masa. The Gulf Coast border zone created Tex-Mex, and Louisiana Creole cuisine blends Spanish, French, and African traditions with Mexican chile influence. Tamales are made in Mississippi Delta communities to this day.',
        sharedIngredients: ['Corn', 'Chiles', 'Pork', 'Black-eyed peas', 'Molasses'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'colonization',
        headline: 'European settlers shaped the South',
        detail: 'Scottish, Irish, French, and Spanish colonizers brought Mediterranean and Northern European cooking to the American South — cast iron from France, pastry from the British Isles, wine grape cultivation from France and Spain. Southern fried chicken techniques trace partly to Scottish frying traditions brought by Scots-Irish settlers.',
        sharedIngredients: ['Olive oil', 'Wheat', 'Pork', 'Butter', 'Wine'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'ingredient',
        headline: "The African diaspora's global pantry",
        detail: 'Enslaved Africans brought okra, black-eyed peas, rice cultivation, and cooking techniques to the American South — and many of these same ingredients traveled via the African diaspora to Southeast Asia through the Indian Ocean trade. Okra appears in both gumbo and Filipino dishes. Rice paddle technique, coconut use, and fermentation traditions have common African roots.',
        sharedIngredients: ['Okra', 'Rice', 'Coconut', 'Fermented fish paste'],
      },
    ],
  },
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    emoji: '🫒',
    tagline: 'Olive oil, sunshine, and the world\'s healthiest diet',
    description:
      'Mediterranean cuisine encompasses the cooking traditions of countries bordering the Mediterranean Sea — Greece, Italy, Spain, Morocco, Lebanon, Turkey, and more. United by olive oil, fresh vegetables, legumes, whole grains, seafood, and wine, it is consistently ranked the world\'s healthiest dietary pattern and a UNESCO cultural heritage.',
    region: 'Europe / Middle East / North Africa',
    country: 'Multiple (Greece, Italy, Spain, Lebanon, Morocco)',
    commonIngredients: [
      'Extra-virgin olive oil', 'Kalamata olives', 'Feta & halloumi cheese', 'Tomatoes',
      'Eggplant (aubergine)', 'Lamb', 'Chickpeas', 'Tahini', 'Lemon', 'Oregano & thyme',
      'Za\'atar', 'Grape leaves', 'Pomegranate', 'Capers', 'Pine nuts',
    ],
    recipeIds: ['greek-salad', 'hummus', 'moussaka'],
    geographyNotes:
      'The Mediterranean Sea is bordered by 21 countries across three continents. The climate — hot, dry summers and mild, wet winters — is perfect for olive trees, grapes, wheat, and citrus. The sea itself provides abundant seafood central to the regional diet.',
    foodHistory:
      'Mediterranean food traces back to ancient Greek and Roman civilizations, which spread olive cultivation, wine production, and bread-making across Europe. The Ottoman Empire unified many of these traditions across Turkey, the Middle East, and North Africa. The Mediterranean Diet was formalized by nutritionist Ancel Keys in the 1960s after he observed lower heart disease rates in Mediterranean populations.',
    nutritionThemes: [
      'Heart-healthy monounsaturated fats from olive oil',
      'Anti-inflammatory polyphenols in olives and wine',
      'Omega-3 fatty acids from fresh fish',
      'High fiber from legumes and whole grains',
      'Antioxidant-rich vegetables and herbs',
    ],
    primaryColor: '#1E6FBF',
    accentColor: '#C0A060',
    bgGradient: 'from-blue-50 to-amber-50',
    mapFact: 'The Mediterranean Sea covers 2.5 million km² and has been a center of world trade for 5,000 years.',
    languages: ['Greek', 'Italian', 'Spanish', 'Arabic', 'Turkish', 'French', 'Hebrew'],
    population: '500 million (Mediterranean basin)',
    connections: [
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Two ancient empires, one pantry',
        detail: 'Persia and the Mediterranean world were deeply entangled for 3,000 years. Persian Wars, Alexander\'s conquest, and Silk Road commerce kept these kitchens in constant dialogue. Pomegranate, eggplant, chickpeas, lamb, saffron, and pistachios cross both cuisines freely. The Ottoman Empire unified Mediterranean and Persian cooking for 600 years.',
        sharedIngredients: ['Pomegranate', 'Eggplant', 'Chickpeas', 'Lamb', 'Saffron', 'Pistachios'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'France bridges Southeast Asia and the Mediterranean',
        detail: 'French colonial cuisine created a remarkable bridge: baguettes, café au lait, and crème caramel traveled from France\'s Mediterranean-influenced culture into Vietnam, creating bánh mì and Vietnamese coffee culture. France itself sits at the crossroads of Mediterranean and Northern European food — and carried that complexity into its colonies.',
        sharedIngredients: ['Wheat bread', 'Coffee', 'Butter', 'Wine', 'Herbs (thyme, bay, parsley)'],
      },
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'The spice trade built both kitchens',
        detail: 'Mediterranean civilization was built partly on the Indian spice trade. Roman cookbooks (Apicius, 1st century AD) call for black pepper in nearly every dish — all imported from India. Arab merchants controlled this trade for centuries, enriching both Mediterranean and Indian cuisine with cross-cultural ingredients. The search for a sea route to India\'s spices launched the Age of Exploration.',
        sharedIngredients: ['Black pepper', 'Cardamom', 'Cinnamon', 'Ginger', 'Lentils', 'Chickpeas'],
      },
    ],
  },
];

export function getCultureById(id: string): Culture | undefined {
  return cultures.find((c) => c.id === id);
}
