import type { Culture } from './types';

export const cultures: Culture[] = [
  {
    id: 'filipino',
    name: 'Filipino',
    emoji: '🇵🇭',
    tagline: 'The hearty, sour, and savory soul of Southeast Asia',
    description:
      'Filipino cuisine is a vibrant blend of Malay, Chinese, Spanish, and American influences, shaped by over 7,000 islands and centuries of trade. It celebrates bold contrasts — sour and salty, sweet and savory — with fermented ingredients, vinegar-braises, and tropical fruits at its core.',
    region: 'Southeast Asia',
    country: 'Philippines',
    commonIngredients: [
      'Vinegar', 'Soy sauce', 'Garlic', 'Pork belly', 'Fish sauce (patis)',
      'Calamansi lime', 'Coconut milk', 'Tamarind', 'Banana blossom', 'Bagoong (shrimp paste)',
      'Lemongrass', 'Annatto seeds', 'Longanisa', 'Rice', 'Palm sugar',
    ],
    recipeIds: ['adobo', 'sinigang', 'pancit'],
    geographyNotes:
      'The Philippines is an archipelago of 7,641 islands in Southeast Asia, bordered by the South China Sea to the west, the Philippine Sea to the east, and the Celebes Sea to the south. The country sits along the Pacific Ring of Fire.',
    foodHistory:
      'Pre-colonial Filipino cuisine centered on rice, seafood, and tropical produce. Spanish colonization (1565–1898) introduced tomatoes, corn, chiles, and stewing techniques. Chinese traders brought noodles, tofu, and soy sauce. American influence added canned goods and fast food culture. Today, Filipino cuisine is experiencing a global renaissance led by chefs celebrating ancestral ingredients.',
    nutritionThemes: [
      'High in protein from fish, pork, and chicken',
      'Rich in probiotics from fermented ingredients',
      'Abundant tropical fruit antioxidants',
      'Complex carbohydrates from rice',
      'Heart-healthy coconut',
    ],
    primaryColor: '#D4393B',
    accentColor: '#FCD116',
    bgGradient: 'from-red-50 to-yellow-50',
    mapFact: 'The Philippines spans over 300,000 km² and has more than 175 spoken languages.',
    languages: ['Filipino (Tagalog)', 'English', 'Cebuano', 'Ilocano'],
    population: '115 million',
    connections: [
      {
        cultureId: 'mexican',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'Both colonies of Spain',
        detail: 'Spain ruled the Philippines (1565–1898) and Mexico simultaneously, and the Manila-Acapulco Galleon Trade directly linked the two. Longanisa sausage mirrors Mexican chorizo; adobo mirrors Spanish-Mexican braising techniques. Filipino rice cakes echo Mexican tamales.',
        sharedIngredients: ['Vinegar', 'Pork belly', 'Garlic', 'Annatto seeds'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Southeast Asian neighbors',
        detail: "Filipino and Vietnamese kitchens share the same tropical pantry: fish sauce, tamarind, lemongrass, and coconut milk. Both cuisines use sour and umami contrasts as their backbone. Sinigang's sour broth echoes canh chua; patis mirrors nước mắm.",
        sharedIngredients: ['Fish sauce', 'Tamarind', 'Lemongrass', 'Coconut milk', 'Rice'],
      },
      {
        cultureId: 'indian',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Spice route connections',
        detail: 'Indian traders sailed to the Philippines for centuries before European colonization. Coconut milk, tamarind, and turmeric appear in both kitchens. The Philippine term "kari" (curry) traces directly to South Indian trade influence.',
        sharedIngredients: ['Coconut milk', 'Tamarind', 'Turmeric', 'Ginger'],
      },
      {
        cultureId: 'japanese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Pacific neighbors with ancient trade ties',
        detail: 'Japan and the Philippines traded across the Pacific for centuries — Japanese merchants operated in Manila before Spanish colonization. Both share a deep respect for rice, abundant seafood, and fermented fish-based umami (Japanese fish sauce and Filipino patis share ancient roots). Soy sauce is a pantry staple in both kitchens.',
        sharedIngredients: ['Rice', 'Soy sauce', 'Seafood', 'Fermented fish sauce', 'Pork belly'],
      },
    ],
  },
  {
    id: 'mexican',
    name: 'Mexican',
    emoji: '🇲🇽',
    tagline: 'Ancient corn civilizations meet Spanish fire and flavor',
    description:
      "Mexican cuisine — a UNESCO Intangible Cultural Heritage — is one of the world's most complex culinary traditions. Built on the \"Three Sisters\" of corn, beans, and squash, it layers indigenous Aztec and Maya traditions with Spanish, Caribbean, and African influences into layers of chile-spiced, slow-cooked brilliance.",
    region: 'North America / Mesoamerica',
    country: 'Mexico',
    commonIngredients: [
      'Corn (masa, tortillas)', 'Dried chile peppers', 'Tomatoes & tomatillos', 'Avocado',
      'Black beans & pinto beans', 'Cilantro', 'Lime', 'Cumin', 'Epazote', 'Mexican oregano',
      'Chocolate (cacao)', 'Pumpkin seeds (pepitas)', 'Chayote', 'Nopales (cactus)', 'Queso fresco',
    ],
    recipeIds: ['tamales', 'mole', 'horchata'],
    geographyNotes:
      'Mexico sits in North America, bordered by the US to the north, the Pacific Ocean to the west, and the Gulf of Mexico and Caribbean Sea to the east. It spans diverse biomes from desert highlands to tropical coasts.',
    foodHistory:
      "Mexican food traces back 9,000 years to ancient Mesoamerican civilizations who domesticated corn. The Aztec empire cultivated cacao, vanilla, and tomatoes unknown to the rest of the world. Spanish conquistadors (1519) merged these with Mediterranean ingredients, creating \"mestizo\" cuisine. Each of Mexico's 32 states has distinct culinary traditions.",
    nutritionThemes: [
      'Complete protein from corn + beans combination',
      'Lycopene-rich tomatoes and tomatillos',
      'Monounsaturated fats from avocado',
      'Antioxidants from dark chocolate and chiles',
      'High fiber from legumes and vegetables',
    ],
    primaryColor: '#006847',
    accentColor: '#CE1126',
    bgGradient: 'from-green-50 to-red-50',
    mapFact: 'Mexico is the 13th largest country by area and home to 68 recognized indigenous languages.',
    languages: ['Spanish', 'Nahuatl', 'Yucatec Maya', 'Zapotec'],
    population: '130 million',
    connections: [
      {
        cultureId: 'filipino',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'Linked by the Manila Galleon',
        detail: "The Manila-Acapulco Galleon Trade (1565–1815) was the world's first transpacific trade route. Mexican silver flowed to Asia; Filipino spices and Chinese goods flowed to Mexico. Annatto (achiote) for color, vinegar-braised meats, and stuffed masa dishes trace this direct exchange.",
        sharedIngredients: ['Annatto seeds', 'Corn', 'Pork', 'Vinegar', 'Chocolate'],
      },
      {
        cultureId: 'southern',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Corn, chiles & African roots',
        detail: 'Both Southern American and Mexican cuisines are built on corn and shaped by African diaspora. Enslaved Africans in both regions transformed Indigenous ingredients. The Gulf Coast border zone blurs into Tex-Mex and Creole — tamales appear in both traditions; chiles crossed into Southern hot sauce culture.',
        sharedIngredients: ['Corn', 'Black-eyed peas', 'Chiles', 'Pork', 'Molasses'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'colonization',
        headline: 'Spanish brought the Mediterranean pantry',
        detail: 'Spanish colonizers who conquered Mexico came from a Mediterranean food tradition. They brought olive oil, wine, wheat, onions, garlic, and livestock (pigs, cattle, chickens) to Mesoamerica — permanently transforming Mexican cuisine and creating "mestizo" cooking.',
        sharedIngredients: ['Garlic', 'Onions', 'Olive oil', 'Wheat', 'Pork'],
      },
    ],
  },
  {
    id: 'vietnamese',
    name: 'Vietnamese',
    emoji: '🇻🇳',
    tagline: 'Fresh herbs, bright broths, and the art of balance',
    description:
      "Vietnamese cuisine is celebrated for its delicate balance of five fundamental tastes: spicy, sour, bitter, salty, and sweet. It emphasizes fresh herbs, minimal oil, and pure flavors. The long, narrow country's geography creates three distinct regional cuisines — northern, central, and southern — each with its own character.",
    region: 'Southeast Asia',
    country: 'Vietnam',
    commonIngredients: [
      'Rice noodles (pho, bun)', 'Fish sauce (nuoc mam)', 'Lemongrass', 'Fresh mint & basil',
      'Bean sprouts', 'Lime', 'Star anise', 'Cinnamon', 'Ginger', 'Shallots',
      'Hoisin sauce', 'Sriracha', 'Shrimp paste', 'Jasmine rice', 'Pork belly',
    ],
    recipeIds: ['pho', 'spring-rolls', 'bun-cha'],
    geographyNotes:
      'Vietnam stretches 1,650 km along the eastern edge of the Indochina Peninsula, bordered by China, Laos, Cambodia, and the South China Sea. Its S-shaped coastline and diverse terrain — from the Red River Delta to the Mekong Delta — shapes regional cuisines.',
    foodHistory:
      'Vietnamese cuisine developed over 4,000 years, strongly influenced by Chinese rule (111 BCE–938 CE), which introduced chopsticks, woks, and soy-based sauces. French colonization (1887–1954) added baguettes, pâté, and coffee culture, visible in bánh mì sandwiches. The Vietnamese concept of yin-yang balance in food — cooling and heating ingredients — remains central today.',
    nutritionThemes: [
      'High in fresh vegetables and herbs',
      'Lean protein from seafood and pork',
      'Probiotic-rich fermented ingredients',
      'Low fat cooking methods (steaming, boiling)',
      'Collagen-rich bone broths',
    ],
    primaryColor: '#DA251D',
    accentColor: '#FFCD00',
    bgGradient: 'from-red-50 to-amber-50',
    mapFact: "Vietnam has over 3,200 km of coastline and is one of the world's top rice exporters.",
    languages: ['Vietnamese', 'Khmer', 'Cham', 'Muong'],
    population: '98 million',
    connections: [
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'France left a baguette behind',
        detail: 'French colonization of Vietnam (1887–1954) permanently altered Vietnamese food. Bánh mì is a Vietnamese baguette. Pâté, coffee culture, and custard (bánh flan) are French-Vietnamese fusions. This is one of history\'s most visible colonial food exchanges — a Southeast Asian street food with a Parisian backbone.',
        sharedIngredients: ['Wheat bread', 'Pâté', 'Coffee', 'Caramel'],
      },
      {
        cultureId: 'filipino',
        strength: 'strong',
        linkType: 'geography',
        headline: 'The fish sauce belt',
        detail: 'Vietnam and the Philippines anchor the Southeast Asian fish sauce tradition. Both cultures ferment small fish into their most essential condiment — nước mắm and patis are nearly identical in process and function. Tamarind souring, coconut-based dishes, and fresh herb garnishes connect both kitchens.',
        sharedIngredients: ['Fish sauce', 'Tamarind', 'Rice noodles', 'Bean sprouts', 'Lemongrass'],
      },
      {
        cultureId: 'persian',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Silk Road spice exchange',
        detail: 'The ancient Silk Road carried Persian saffron, dried fruits, and spice-layering techniques eastward through Central Asia into Chinese and Vietnamese kitchens. Star anise — the defining spice of phở — traveled this route. Vietnamese five-spice blends reflect this historic Central Asian spice corridor.',
        sharedIngredients: ['Star anise', 'Cinnamon', 'Ginger', 'Cardamom'],
      },
      {
        cultureId: 'japanese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'East Asian noodle culture and Buddhist cuisine',
        detail: 'Japan and Vietnam both built celebrated noodle cultures from Chinese roots — ramen and phở are cousins with different characters. Buddhist temple cuisine (shōjin ryōri in Japan, chay in Vietnam) created parallel vegetarian cooking traditions across both countries. Green tea culture, rice-based fermentation, and the five-flavor balancing principle connect both cuisines across centuries of East Asian trade.',
        sharedIngredients: ['Rice noodles', 'Soy sauce', 'Sesame', 'Ginger', 'Green tea', 'Fermented condiments'],
      },
    ],
  },
  {
    id: 'persian',
    name: 'Persian',
    emoji: '🇮🇷',
    tagline: 'Saffron-gilded poetry on a plate from ancient Persia',
    description:
      "Persian cuisine is one of the world's oldest and most sophisticated culinary traditions, dating back 2,500 years to the Achaemenid Empire. It is defined by the artful use of dried fruits, nuts, fragrant rice, and precious spices like saffron, combining sweet and sour notes with incredible complexity and elegance.",
    region: 'Middle East / Central Asia',
    country: 'Iran',
    commonIngredients: [
      'Saffron', 'Rose water', 'Barberries (zereshk)', 'Dried limes (limu omani)',
      'Walnuts', 'Pomegranate molasses', 'Fresh dill, parsley, cilantro, fenugreek',
      'Lamb', 'Long-grain basmati rice', 'Split chickpeas', 'Kashk (whey)',
      'Turmeric', 'Dried apricots', 'Chickpeas', 'Ghee',
    ],
    recipeIds: ['ghormeh-sabzi', 'fesenjan', 'tahdig'],
    geographyNotes:
      'Iran (ancient Persia) spans 1.6 million km² in the Middle East, bordered by Turkey, Iraq, the Caspian Sea, Russia, Turkmenistan, Afghanistan, and Pakistan. Its central plateau, mountain ranges, and diverse climate zones allow extraordinary agricultural diversity.',
    foodHistory:
      'Persian food culture stretches back to the Achaemenid Empire (550–330 BCE), when Persia was the world\'s largest empire. Persian food spread through Silk Road trade routes to influence Indian Mughal cuisine, Ottoman Turkish cooking, and Arab traditions. The concept of the Persian "sofreh" (table spread) as an act of hospitality and generosity remains central to the culture.',
    nutritionThemes: [
      'Rich in omega-3s from walnuts and fish',
      'Antioxidants from pomegranate and saffron',
      'Anti-inflammatory turmeric and herbs',
      'Plant-forward cooking with legumes',
      'Probiotic kashk and fermented dairy',
    ],
    primaryColor: '#239F40',
    accentColor: '#DA0000',
    bgGradient: 'from-green-50 to-rose-50',
    mapFact: 'Iran is home to one of the oldest civilizations on Earth, with settlements dating back 7,000+ years.',
    languages: ['Persian (Farsi)', 'Azerbaijani', 'Kurdish', 'Arabic'],
    population: '87 million',
    connections: [
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'The Mughal Empire merged two cuisines',
        detail: 'The Mughal emperors (1526–1857) were Persian-speaking Central Asians who ruled India for 300 years. They brought Persian rice techniques, saffron, dried fruits, rosewater, and nut-enriched sauces into Indian cooking — and took Indian spices back. Biryani is a direct Persian-Indian fusion. Korma, haleem, and kebab all trace to this empire.',
        sharedIngredients: ['Saffron', 'Basmati rice', 'Ghee', 'Cardamom', 'Rose water', 'Dried fruits'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Ancient empires, shared pantry',
        detail: 'The Persian and Mediterranean worlds overlapped constantly — Persia ruled Greece briefly, Rome traded with Persia, and the Ottoman Empire absorbed both Persian and Mediterranean traditions. Pomegranate, eggplant, lamb, chickpeas, and pistachios flow freely between Persian and Mediterranean kitchens as a result.',
        sharedIngredients: ['Pomegranate', 'Eggplant', 'Lamb', 'Chickpeas', 'Pistachios', 'Lemon'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'The Silk Road ran both ways',
        detail: 'Persia was the commercial hub of the ancient world. Persian merchants carried saffron, dried limes, and layered spice blends east along the Silk Road into Central Asia and eventually into East and Southeast Asian cooking. Star anise traveled west; saffron traveled east. Both kitchens still carry traces of this exchange.',
        sharedIngredients: ['Star anise', 'Cinnamon', 'Cardamom', 'Dried limes', 'Turmeric'],
      },
      {
        cultureId: 'moroccan',
        strength: 'strong',
        linkType: 'empire',
        headline: 'Ottoman and Moorish empires carried Persian flavors west',
        detail: 'Persian culinary philosophy — sweet-sour balance, dried fruit in savory dishes, saffron-gilded rice, nut-enriched sauces — traveled west through the Ottoman Empire and Moorish Andalusia into Morocco. Moroccan pastilla (a sweet-savory pigeon pie with almonds and cinnamon) is a direct Persian-influenced Moorish creation. Preserved lemons echo Persian dried limes; ras el hanout echoes Persian advieh spice blends.',
        sharedIngredients: ['Saffron', 'Dried fruits', 'Almonds', 'Cinnamon', 'Rose water', 'Lamb'],
      },
    ],
  },
  {
    id: 'indian',
    name: 'Indian',
    emoji: '🇮🇳',
    tagline: "A spice-trader's paradise with 5,000 years of flavor",
    description:
      'Indian cuisine is not one cuisine but a vast constellation of regional traditions spanning 28 states, shaped by geography, religion, season, and ancient Ayurvedic principles. From the buttery richness of Punjab to the coconut-laced curries of Kerala, the fiery street food of Mumbai to the delicate vegetarian thalis of Gujarat — India feeds the world\'s culinary imagination.',
    region: 'South Asia',
    country: 'India',
    commonIngredients: [
      'Turmeric', 'Cumin', 'Coriander', 'Cardamom', 'Garam masala', 'Mustard seeds',
      'Ghee', 'Paneer', 'Lentils (dal)', 'Basmati rice', 'Coconut milk', 'Tamarind',
      'Fenugreek seeds', 'Curry leaves', 'Hing (asafoetida)', 'Chana (chickpeas)',
    ],
    recipeIds: ['biryani', 'dal-tadka', 'kheer'],
    geographyNotes:
      'India is the 7th largest country, spanning from the Himalayas in the north to tropical coastlines in the south. The Gangetic Plain, Deccan Plateau, Thar Desert, and coastal regions each produce unique ingredients that define regional cuisines.',
    foodHistory:
      "Indian culinary history spans 5,000+ years, from Indus Valley civilization seeds to Vedic-era cooking texts. The Silk Road brought spices westward to Rome and Europe, making Indian spices the engine of world trade. Mughal emperors (1526–1857) created biryani and korma. British colonization (1858–1947) influenced tea culture. India's independence movement was even partly sparked by salt.",
    nutritionThemes: [
      'Complete protein from dal + rice or roti',
      'Anti-inflammatory spice compounds (curcumin)',
      'Probiotic-rich lassi, yogurt, and fermented dosas',
      'Fiber from legumes and vegetables',
      'Ayurvedic balance of six tastes',
    ],
    primaryColor: '#FF9933',
    accentColor: '#138808',
    bgGradient: 'from-orange-50 to-green-50',
    mapFact: 'India is home to over 22 official languages and more than 1,600 dialects.',
    languages: ['Hindi', 'Bengali', 'Tamil', 'Telugu', 'Marathi', 'Urdu', 'English'],
    population: '1.4 billion',
    connections: [
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'Mughal fusion created North Indian cuisine',
        detail: 'Mughal emperors were Persian in language, culture, and taste — and they ruled India for over 300 years. The result is North Indian cuisine as we know it: biryani (Persian layered rice + Indian spices), korma (Persian braising + Indian aromatics), naan (Persian bread), and kebab culture. This is one of history\'s great culinary fusions.',
        sharedIngredients: ['Saffron', 'Basmati rice', 'Cardamom', 'Rose water', 'Ghee', 'Pistachios'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Ancient spice trade neighbors',
        detail: 'Indian traders were sailing to Southeast Asia millennia before Europeans arrived. They carried tamarind, coconut cultivation techniques, turmeric, and curry concepts to the Philippines and beyond. The Tagalog word for "curry" (kari) is Sanskrit. Coconut milk, tamarind souring, and turmeric coloring appear in both cuisines for this reason.',
        sharedIngredients: ['Tamarind', 'Coconut milk', 'Turmeric', 'Ginger', 'Mustard seeds'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'trade',
        headline: "Rome's most valuable imports came from India",
        detail: "Roman historian Pliny complained that India was draining Rome's treasury through spice purchases. Black pepper, cardamom, and cinnamon — Indian exports — were literally worth more than gold in ancient Rome. This spice trade shaped Mediterranean cooking for 2,000 years and made Indian spices central to European cuisine.",
        sharedIngredients: ['Black pepper', 'Cardamom', 'Cinnamon', 'Turmeric', 'Lentils', 'Chickpeas'],
      },
      {
        cultureId: 'ethiopian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Red Sea trade routes ran for millennia',
        detail: 'The ancient Red Sea trade route — documented in the Periplus of the Erythraean Sea (1st century CE) — directly connected Indian ports to the Ethiopian port of Adulis. India exported cumin, cardamom, turmeric, and ginger, which became central to Ethiopian berbere spice blends. Ethiopia exported ivory, incense (frankincense/myrrh), and gold. This exchange predates the Silk Road.',
        sharedIngredients: ['Cardamom', 'Turmeric', 'Ginger', 'Fenugreek', 'Cumin', 'Lentils', 'Clarified butter'],
      },
    ],
  },
  {
    id: 'southern',
    name: 'Southern American',
    emoji: '🌽',
    tagline: 'Soul food, smoke, and the roots of American cooking',
    description:
      "Southern American cuisine is the deeply soulful cooking tradition born from the American South — a fusion of West African, Native American, and European culinary traditions forged through resilience and community. It's the food of barbecue pits, church potlucks, Sunday suppers, and front-porch storytelling, rich with history and love in every bite.",
    region: 'North America',
    country: 'United States (South)',
    commonIngredients: [
      'Cornmeal & grits', 'Collard greens', 'Black-eyed peas', 'Sweet potatoes', 'Okra',
      'Buttermilk', 'Lard & bacon fat', 'Smoked pork', 'Hot sauce', 'Molasses',
      'Peanuts', 'Peaches', 'Sorghum syrup', 'Cast iron cookware', 'Church lady seasoning',
    ],
    recipeIds: ['fried-chicken', 'shrimp-grits', 'peach-cobbler'],
    geographyNotes:
      'The American South encompasses states from Virginia to Texas, including the Mississippi River Delta, Appalachian Mountains, Gulf Coast, and Atlantic coastal lowlands. Each sub-region has distinct food traditions: Creole Louisiana, Appalachian cooking, Low Country South Carolina, and Texas BBQ.',
    foodHistory:
      'Southern food is inseparable from the history of African enslavement. Enslaved Africans brought okra, black-eyed peas, rice cultivation, and technique to American kitchens, yet were denied credit for centuries. Native Americans contributed corn, beans, squash, and game. West African, Scottish, Irish, and French settlers each added layers. Modern chefs are now rightfully centering Black Southern culinary heritage.',
    nutritionThemes: [
      'High fiber from beans, peas, and greens',
      'Potassium and vitamins from sweet potatoes',
      'Probiotic-rich fermented hot sauces',
      'Plant diversity in seasonal produce',
      'Iron from cast-iron cooking methods',
    ],
    primaryColor: '#8B4513',
    accentColor: '#DAA520',
    bgGradient: 'from-amber-50 to-orange-50',
    mapFact: 'The Mississippi Delta region is called the "cradle of American music and food culture."',
    languages: ['English', 'Gullah Geechee', 'Louisiana Creole'],
    population: '130 million (US South)',
    connections: [
      {
        cultureId: 'mexican',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Corn culture runs deep in both',
        detail: 'Southern American and Mexican cuisine share corn as their foundation — cornbread mirrors tortillas; grits mirror masa. The Gulf Coast border zone created Tex-Mex, and Louisiana Creole cuisine blends Spanish, French, and African traditions with Mexican chile influence. Tamales are made in Mississippi Delta communities to this day.',
        sharedIngredients: ['Corn', 'Chiles', 'Pork', 'Black-eyed peas', 'Molasses'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'colonization',
        headline: 'European settlers shaped the South',
        detail: 'Scottish, Irish, French, and Spanish colonizers brought Mediterranean and Northern European cooking to the American South — cast iron from France, pastry from the British Isles, wine grape cultivation from France and Spain. Southern fried chicken techniques trace partly to Scottish frying traditions brought by Scots-Irish settlers.',
        sharedIngredients: ['Olive oil', 'Wheat', 'Pork', 'Butter', 'Wine'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'ingredient',
        headline: "The African diaspora's global pantry",
        detail: 'Enslaved Africans brought okra, black-eyed peas, rice cultivation, and cooking techniques to the American South — and many of these same ingredients traveled via the African diaspora to Southeast Asia through the Indian Ocean trade. Okra appears in both gumbo and Filipino dishes. Rice paddle technique, coconut use, and fermentation traditions have common African roots.',
        sharedIngredients: ['Okra', 'Rice', 'Coconut', 'Fermented fish paste'],
      },
      {
        cultureId: 'west-african',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Soul food IS West African food',
        detail: "This is the most important food connection in American culinary history. Enslaved West Africans were forced across the Atlantic carrying their crops, techniques, and knowledge. Okra, black-eyed peas, watermelon, rice cultivation, peanuts, and one-pot stew techniques traveled with them. Gumbo derives from the Bantu word \"ki ngombo\" (okra). Black-eyed peas on New Year's Day is a direct West African tradition. Southern food without West African roots simply does not exist.",
        sharedIngredients: ['Okra', 'Black-eyed peas', 'Peanuts', 'Watermelon', 'Rice', 'Corn', 'Sweet potatoes'],
      },
    ],
  },
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    emoji: '🫒',
    tagline: "Olive oil, sunshine, and the world's healthiest diet",
    description:
      "Mediterranean cuisine encompasses the cooking traditions of countries bordering the Mediterranean Sea — Greece, Italy, Spain, Morocco, Lebanon, Turkey, and more. United by olive oil, fresh vegetables, legumes, whole grains, seafood, and wine, it is consistently ranked the world's healthiest dietary pattern and a UNESCO cultural heritage.",
    region: 'Europe / Middle East / North Africa',
    country: 'Multiple (Greece, Italy, Spain, Lebanon, Morocco)',
    commonIngredients: [
      'Extra-virgin olive oil', 'Kalamata olives', 'Feta & halloumi cheese', 'Tomatoes',
      'Eggplant (aubergine)', 'Lamb', 'Chickpeas', 'Tahini', 'Lemon', 'Oregano & thyme',
      "Za'atar", 'Grape leaves', 'Pomegranate', 'Capers', 'Pine nuts',
    ],
    recipeIds: ['greek-salad', 'hummus', 'moussaka'],
    geographyNotes:
      'The Mediterranean Sea is bordered by 21 countries across three continents. The climate — hot, dry summers and mild, wet winters — is perfect for olive trees, grapes, wheat, and citrus. The sea itself provides abundant seafood central to the regional diet.',
    foodHistory:
      'Mediterranean food traces back to ancient Greek and Roman civilizations, which spread olive cultivation, wine production, and bread-making across Europe. The Ottoman Empire unified many of these traditions across Turkey, the Middle East, and North Africa. The Mediterranean Diet was formalized by nutritionist Ancel Keys in the 1960s after he observed lower heart disease rates in Mediterranean populations.',
    nutritionThemes: [
      'Heart-healthy monounsaturated fats from olive oil',
      'Anti-inflammatory polyphenols in olives and wine',
      'Omega-3 fatty acids from fresh fish',
      'High fiber from legumes and whole grains',
      'Antioxidant-rich vegetables and herbs',
    ],
    primaryColor: '#1E6FBF',
    accentColor: '#C0A060',
    bgGradient: 'from-blue-50 to-amber-50',
    mapFact: 'The Mediterranean Sea covers 2.5 million km² and has been a center of world trade for 5,000 years.',
    languages: ['Greek', 'Italian', 'Spanish', 'Arabic', 'Turkish', 'French', 'Hebrew'],
    population: '500 million (Mediterranean basin)',
    connections: [
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Two ancient empires, one pantry',
        detail: 'Persia and the Mediterranean world were deeply entangled for 3,000 years. Persian Wars, Alexander\'s conquest, and Silk Road commerce kept these kitchens in constant dialogue. Pomegranate, eggplant, chickpeas, lamb, saffron, and pistachios cross both cuisines freely. The Ottoman Empire unified Mediterranean and Persian cooking for 600 years.',
        sharedIngredients: ['Pomegranate', 'Eggplant', 'Chickpeas', 'Lamb', 'Saffron', 'Pistachios'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'France bridges Southeast Asia and the Mediterranean',
        detail: "French colonial cuisine created a remarkable bridge: baguettes, café au lait, and crème caramel traveled from France's Mediterranean-influenced culture into Vietnam, creating bánh mì and Vietnamese coffee culture. France itself sits at the crossroads of Mediterranean and Northern European food — and carried that complexity into its colonies.",
        sharedIngredients: ['Wheat bread', 'Coffee', 'Butter', 'Wine', 'Herbs (thyme, bay, parsley)'],
      },
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'The spice trade built both kitchens',
        detail: 'Mediterranean civilization was built partly on the Indian spice trade. Roman cookbooks (Apicius, 1st century AD) call for black pepper in nearly every dish — all imported from India. Arab merchants controlled this trade for centuries, enriching both Mediterranean and Indian cuisine with cross-cultural ingredients. The search for a sea route to India\'s spices launched the Age of Exploration.',
        sharedIngredients: ['Black pepper', 'Cardamom', 'Cinnamon', 'Ginger', 'Lentils', 'Chickpeas'],
      },
      {
        cultureId: 'moroccan',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Two shores of the same sea',
        detail: 'Morocco and the Mediterranean world are separated by just 14 km of water at the Strait of Gibraltar. This closeness drove 3,000 years of exchange: Phoenicians founded Carthage in North Africa; Rome governed Morocco (Mauretania Tingitana); the Moors built the Alhambra in Spain; French colonialism ran in both directions. Olive oil, chickpeas, lamb, saffron, citrus, and almonds are shared across this common sea.',
        sharedIngredients: ['Olive oil', 'Chickpeas', 'Lamb', 'Saffron', 'Lemon', 'Almonds', 'Olives'],
      },
    ],
  },
  {
    id: 'japanese',
    name: 'Japanese',
    emoji: '🇯🇵',
    tagline: 'Umami mastery, seasonal harmony, and the art of impermanence',
    description: 'Japanese cuisine — washoku, a UNESCO Intangible Cultural Heritage — is built on the philosophy of balance, seasonality, and harmony. From ramen to sushi, miso to matcha, Japanese food traditions emphasize quality ingredients prepared simply, achieving incredible depth through fermentation, dashi broth, and the five-taste principle of umami.',
    region: 'East Asia',
    country: 'Japan',
    commonIngredients: [
      'Soy sauce (shoyu)', 'Miso paste', 'Mirin', 'Sake', 'Dashi (kombu + bonito)',
      'Tofu', 'Short-grain rice', 'Nori (seaweed)', 'Wasabi', 'Pickled ginger',
      'Sesame oil', 'Panko breadcrumbs', 'Ramen noodles', 'Tempura batter', 'Matcha',
    ],
    recipeIds: ['ramen', 'onigiri'],
    geographyNotes: 'Japan is an archipelago of 6,852 islands in the Pacific Ocean stretching 3,000 km along East Asia. Surrounded by ocean, Japan developed a profound seafood culture, and its mountainous terrain created distinct regional cooking traditions.',
    foodHistory: 'Japanese cuisine evolved over 2,000 years, influenced by Chinese Buddhism (introducing vegetarian temple food, tofu, and noodles), Korean rice culture, and Portuguese traders who arrived in 1543 (bringing tempura frying technique). The samurai era formalized kaiseki multi-course dining. Meiji Restoration (1868) opened Japan to Western yoshoku dishes like curry rice and croquettes. Modern Japanese cuisine is globally revered for precision and respect for ingredients.',
    nutritionThemes: [
      'Low-calorie, high-nutrient washoku diet associated with longevity',
      'Omega-3 rich seafood and mineral-rich seaweed',
      'Probiotic-rich miso, natto, and tsukemono pickles',
      'Portion mindfulness and variety (ichiju sansai principle)',
      'Anti-aging polyphenols from green tea (catechins)',
    ],
    primaryColor: '#BC002D',
    accentColor: '#F5A623',
    bgGradient: 'from-red-50 to-orange-50',
    mapFact: "Japan has the world's longest life expectancy, partly attributed to the traditional washoku diet.",
    languages: ['Japanese'],
    population: '125 million',
    connections: [
      {
        cultureId: 'korean',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Fermentation neighbors across the strait',
        detail: 'Korea and Japan are separated by just 200 km of ocean and share millennia of cultural exchange. Buddhism traveled Korea→Japan carrying vegetarian temple cuisine. Doenjang (Korean fermented soy paste) and miso (Japanese) use nearly identical fermentation processes. Korean soy sauce (ganjang) and Japanese shoyu share ancient origins. Korea transmitted rice cultivation, chopstick culture, and early pottery techniques to Japan.',
        sharedIngredients: ['Fermented soybean paste', 'Soy sauce', 'Rice', 'Sesame', 'Seaweed', 'Pickled vegetables'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'East Asian noodle culture and Buddhist traditions',
        detail: 'Japan and Vietnam both built celebrated noodle cultures from Chinese roots — ramen and phở are cousins with different personalities. Buddhist temple cuisine (shōjin ryōri in Japan, chay in Vietnam) created similar vegetarian cooking traditions in both countries. Green tea culture, rice-based fermentation, and the principle of balancing flavors connect both cuisines across centuries of East Asian trade.',
        sharedIngredients: ['Rice noodles', 'Soy sauce', 'Sesame', 'Ginger', 'Green tea', 'Fermented condiments'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Pacific neighbors with centuries of trade',
        detail: 'Japan and the Philippines traded across the Pacific for centuries — Japanese merchants operated in Manila before Spanish colonization. Both cuisines share a deep respect for rice, abundant seafood, and fish-based umami (Japanese fish sauce and Filipino patis share ancient roots). Soy sauce is a pantry staple in both kitchens, and pork belly features prominently in celebrations in both cultures.',
        sharedIngredients: ['Rice', 'Soy sauce', 'Seafood', 'Fermented fish sauce', 'Pork belly'],
      },
    ],
  },
  {
    id: 'korean',
    name: 'Korean',
    emoji: '🇰🇷',
    tagline: 'Bold banchan, fermented flavors, and communal table culture',
    description: 'Korean cuisine is a study in contrasts — fiery and cooling, fermented and fresh, intensely flavored yet precisely balanced. It is built around rice, fermented vegetables (kimchi), gochujang chile paste, and the tradition of banchan (small shared side dishes). Korean food is deeply communal: meals are meant to be shared, every dish simultaneously on the table.',
    region: 'East Asia',
    country: 'South Korea / North Korea',
    commonIngredients: [
      'Gochujang (chile paste)', 'Doenjang (fermented soybean paste)', 'Soy sauce (ganjang)',
      'Sesame oil', 'Garlic', 'Ginger', 'Kimchi', 'Short-grain rice', 'Glass noodles (dangmyeon)',
      'Perilla leaves', 'Nori', 'Dried anchovies (myeolchi)', 'Rice wine (makgeolli)', 'Tofu', 'Bean sprouts',
    ],
    recipeIds: ['bibimbap', 'japchae'],
    geographyNotes: "The Korean Peninsula extends southward from northeast China, bordered by the Yellow Sea to the west and the Sea of Japan to the east. Korea's mountainous terrain (70% mountains) shaped a root vegetable and forage-heavy cuisine inland, while coastal communities developed rich seafood and fermented fish traditions.",
    foodHistory: "Korean food culture stretches back 5,000+ years. Buddhism (introduced 372 CE) shaped vegetarian temple cuisine and fermentation traditions. The Joseon Dynasty (1392–1897) codified Korean court cuisine and formalized kimchi-making as a national practice. Japanese occupation (1910–1945) influenced some techniques. South Korea's 1988 Seoul Olympics and later the global K-drama and K-pop wave introduced Korean cuisine to the world. Korean BBQ, fried chicken, and ramen are now global phenomena.",
    nutritionThemes: [
      'Probiotic-rich kimchi and fermented vegetables supporting gut health',
      'Low-fat cooking with abundant plant diversity',
      'Anti-inflammatory gochujang, garlic, and ginger',
      'Mineral-rich seaweed and seafood',
      'High fiber from diverse banchan side dishes',
    ],
    primaryColor: '#003478',
    accentColor: '#CD2E3A',
    bgGradient: 'from-blue-50 to-red-50',
    mapFact: 'South Korea consumes more instant ramen per capita than any other country in the world.',
    languages: ['Korean'],
    population: '52 million (South Korea), 26 million (North Korea)',
    connections: [
      {
        cultureId: 'japanese',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Fermentation neighbors across the strait',
        detail: 'Korea and Japan are separated by just 200 km of ocean, and their cuisines reflect centuries of deep exchange. Doenjang (Korean fermented soy paste) and miso (Japanese) use identical fermentation processes. Buddhism traveled Korea→Japan carrying vegetarian temple food and fermentation knowledge. Korea transmitted rice cultivation, bronze pottery, and chopstick culture to Japan.',
        sharedIngredients: ['Fermented soybean paste', 'Soy sauce', 'Rice', 'Sesame', 'Seaweed', 'Pickled vegetables'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'East Asian fermentation belt',
        detail: "Korea and Vietnam both sit within the East Asian fermentation belt — where rice, soybeans, and seafood are transformed into complex condiments. Korean kimchi parallels Vietnamese dưa cải (pickled mustard greens). Gochujang chile paste echoes the chile-fish sauce combinations of Vietnamese cuisine. Buddhist temple vegetarian cooking traditions developed in parallel in both cultures.",
        sharedIngredients: ['Fermented vegetables', 'Fish sauce', 'Rice', 'Sesame', 'Ginger', 'Chiles'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'geography',
        headline: 'Pacific Rim pantry cousins',
        detail: 'Korea and the Philippines share the Pacific Rim — connected by ocean trade, Buddhist influence, and shared pantry staples. Both cuisines feature pork belly as a celebration meat, fermented shrimp paste (Korean saeujeot mirrors Filipino bagoong), soy sauce as a base condiment, and rice as the foundation of every meal. Korean and Filipino communities share the deepest cultural exchange among Pacific Rim food traditions.',
        sharedIngredients: ['Pork belly', 'Fermented shrimp paste', 'Soy sauce', 'Rice', 'Sesame', 'Ginger'],
      },
    ],
  },
  {
    id: 'west-african',
    name: 'West African',
    emoji: '🌍',
    tagline: 'The pantry that fed the world — bold stews and ancient grains',
    description: "West African cuisine — from Nigeria, Ghana, Senegal, and beyond — is one of the world's most important and underrecognized culinary traditions. Built on ancient grains, tropical produce, and bold one-pot stews, it is the source cuisine of Southern American soul food, Brazilian feijoada, and Caribbean cooking. West African cooks created the okra stew, peanut butter sauce, black-eyed pea dishes, and rice cultivation techniques that define cooking across three continents.",
    region: 'Sub-Saharan Africa',
    country: 'Nigeria, Ghana, Senegal, Ivory Coast',
    commonIngredients: [
      'Palm oil', 'Okra', 'Black-eyed peas', 'Cassava (yuca)', 'Yams', 'Plantains',
      'Groundnuts (peanuts)', 'Scotch bonnet peppers', 'Stockfish (dried cod)', 'Egusi (melon seeds)',
      'Fermented locust beans (dawadawa)', 'Ginger', 'Dried crayfish', 'Corn (maize)', 'Fonio',
    ],
    recipeIds: ['jollof-rice', 'egusi-soup'],
    geographyNotes: 'West Africa spans from Senegal in the northwest to Nigeria in the east, along the Gulf of Guinea coastline. The region ranges from Saharan desert in the north to tropical rainforest and savannas in the south. The Niger River basin shaped agricultural traditions across the region over millennia.',
    foodHistory: "West African food culture is among the world's oldest, with organized agriculture documented 3,000+ years ago. The transatlantic slave trade (1500s–1800s) forcibly carried West African crops, techniques, and cooks across the Atlantic — permanently transforming Southern American, Brazilian, and Caribbean cuisines. Okra, black-eyed peas, rice cultivation, peanuts, watermelon, and one-pot stew techniques all traveled this route. Modern chefs worldwide are now rightfully centering West African cuisine's foundational role in global cooking.",
    nutritionThemes: [
      'Plant-based protein from legumes, seeds, and fermented ingredients',
      'Beta-carotene and Vitamin A from palm oil and orange vegetables',
      'Antioxidant scotch bonnet peppers and ginger',
      'Complex carbohydrates from root vegetables and ancient grains',
      'Omega-3s from dried fish and seafood',
    ],
    primaryColor: '#008751',
    accentColor: '#FCD116',
    bgGradient: 'from-green-50 to-yellow-50',
    mapFact: 'West Africa is home to over 500 distinct ethnic groups, each with their own distinct food traditions.',
    languages: ['Yoruba', 'Igbo', 'Hausa', 'Twi', 'Wolof', 'Fula', 'English', 'French'],
    population: '420 million',
    connections: [
      {
        cultureId: 'southern',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Soul food IS West African food',
        detail: 'This is the most important food connection in American culinary history. Enslaved West Africans were forced across the Atlantic carrying their crops, techniques, and knowledge. Okra, black-eyed peas, watermelon, rice cultivation, peanuts, and one-pot stew techniques traveled with them. Gumbo derives from the Bantu word "ki ngombo" (okra). Black-eyed peas on New Year\'s Day is a direct West African tradition. Southern food without West African roots simply does not exist.',
        sharedIngredients: ['Okra', 'Black-eyed peas', 'Peanuts', 'Watermelon', 'Rice', 'Corn', 'Sweet potatoes'],
      },
      {
        cultureId: 'brazilian',
        strength: 'strong',
        linkType: 'migration',
        headline: 'African diaspora built Brazilian cuisine',
        detail: 'Brazil received more enslaved Africans than any other country in the Americas — over 4.9 million people. Afro-Brazilian cuisine (Bahian cooking especially) directly reflects West African traditions: acarajé (black-eyed pea fritters) mirrors Yoruba akara; feijoada draws on African one-pot bean stews; palm oil (dendê) in moqueca traces to Nigerian palm oil cooking traditions.',
        sharedIngredients: ['Black-eyed peas', 'Palm oil', 'Okra', 'Plantains', 'Dried fish', 'Peanuts'],
      },
      {
        cultureId: 'moroccan',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Trans-Saharan caravans connected West Africa and North Africa',
        detail: 'For over 1,000 years, trans-Saharan trade caravans connected West African empires to Moroccan cities like Fez and Marrakech. Gold, salt, kola nuts, and dried fish moved north; textiles, ceramics, dates, and spices moved south. The Mali Empire and Songhai Empire made Timbuktu a center of this exchange, creating culinary cross-pollination between Sahelian and Maghrebi cuisines.',
        sharedIngredients: ['Dried fish', 'Millet', 'Dates', 'Dried peppers', 'Cumin', 'Chickpeas'],
      },
    ],
  },
  {
    id: 'ethiopian',
    name: 'Ethiopian',
    emoji: '🇪🇹',
    tagline: 'Injera-laden communal feasts from the Horn of Africa',
    description: "Ethiopian cuisine is one of Africa's most sophisticated culinary traditions, built around injera — a spongy, sour sourdough flatbread made from teff — served communally with an array of colorful stews (wats). Ethiopia was never colonized and thus preserved its ancient food traditions intact, including unique spice blends, coffee culture, and fasting cuisine developed over 3,000 years.",
    region: 'East Africa (Horn of Africa)',
    country: 'Ethiopia',
    commonIngredients: [
      'Teff (injera grain)', 'Berbere spice blend', 'Mitmita', 'Niter kibbeh (spiced butter)',
      'Red lentils (misir)', 'Chickpeas (shimbra)', 'Fenugreek', 'Turmeric', 'Cardamom',
      'Ginger', 'Black cumin (tikur azmud)', 'Fava beans (ful)', 'Chicken (doro)', 'Ayib (fresh cheese)',
    ],
    recipeIds: ['misir-wat', 'doro-wat'],
    geographyNotes: "Ethiopia sits on the Horn of Africa, bordered by Eritrea, Djibouti, Somalia, Kenya, South Sudan, and Sudan. The Ethiopian Highlands — one of Africa's most fertile regions — and the Great Rift Valley define its geography. High altitude produces a cool, temperate climate ideal for teff, coffee, and diverse agriculture.",
    foodHistory: "Ethiopia has 3,000 years of recorded culinary history. The ancient Kingdom of Axum (100–940 CE) developed Red Sea trade routes to Arabia and India, introducing spices that now define Ethiopian cooking. Ethiopia is the birthplace of coffee (per legend, discovered by goat herder Kaldi in the 9th century). Orthodox Christian fasting traditions — over 180 fasting days per year — created one of the world's richest vegan cuisines. Ethiopia repelled European colonization (defeating Italy at Battle of Adwa, 1896), preserving its food traditions intact.",
    nutritionThemes: [
      'Iron-rich teff grain (contains more iron than wheat or barley)',
      'Complete protein from diverse legume-forward diet',
      'Probiotic injera sourdough fermentation',
      'Anti-inflammatory berbere spice blend (chiles, ginger, fenugreek)',
      'Exceptionally high fiber from the plant-forward fasting diet',
    ],
    primaryColor: '#078930',
    accentColor: '#FCDD09',
    bgGradient: 'from-green-50 to-yellow-50',
    mapFact: "Ethiopia is the birthplace of coffee and home to some of the world's oldest Christian and Jewish communities.",
    languages: ['Amharic', 'Oromo', 'Somali', 'Tigrinya', 'Sidama'],
    population: '126 million',
    connections: [
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Red Sea trade routes ran for millennia',
        detail: 'The ancient Red Sea trade route (documented in the Periplus of the Erythraean Sea, 1st century CE) directly connected Indian ports to the Ethiopian port of Adulis. India exported cumin, cardamom, turmeric, and ginger — all now central to Ethiopian berbere spice blends. Ethiopia exported ivory, incense (frankincense), and gold. This maritime exchange predates the overland Silk Road and shaped both cuisines for millennia.',
        sharedIngredients: ['Cardamom', 'Turmeric', 'Ginger', 'Fenugreek', 'Cumin', 'Lentils', 'Clarified butter'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Ancient empires met at the Red Sea',
        detail: 'The Roman Empire and its Byzantine successor both traded actively with Ethiopia — the Kingdom of Axum was one of four great powers recognized by Rome (alongside Persia, China, and Rome itself). Wine, olive oil, and Mediterranean ceramics flowed into Ethiopia; ivory, incense, and coffee flowed back. This ancient link explains why olive oil appears in Ethiopian fasting cuisine and why honey wine (tej) echoes Byzantine mead traditions.',
        sharedIngredients: ['Olive oil', 'Lentils', 'Chickpeas', 'Honey wine', 'Herbs', 'Lamb'],
      },
      {
        cultureId: 'moroccan',
        strength: 'moderate',
        linkType: 'geography',
        headline: 'Spice-layered cousins across the continent',
        detail: 'Morocco and Ethiopia share the African tradition of building complexity through many spices combined into characteristic blends — ras el hanout in Morocco, berbere in Ethiopia. Both cuisines are deeply shaped by Islamic and Christian fasting traditions that created rich legume-forward vegetarian cooking. Coffee culture, flatbread traditions, and a love of lamb stews connect these cuisines across the continent.',
        sharedIngredients: ['Berbere spices', 'Lentils', 'Chickpeas', 'Cumin', 'Cinnamon', 'Ginger', 'Lamb'],
      },
    ],
  },
  {
    id: 'brazilian',
    name: 'Brazilian',
    emoji: '🇧🇷',
    tagline: 'Feijoada feasts and tropical abundance from the Amazon',
    description: "Brazilian cuisine is one of the world's great fusion traditions — a three-way convergence of Indigenous Amazonian peoples, West African enslaved cooks, and Portuguese colonizers. The result is staggeringly diverse: from the Afro-Brazilian moqueca and acarajé of Bahia, to the European-influenced churrasco of the south, to the tropical fruit abundance of the Amazon. Brazil is simultaneously African, European, and South American — all at once.",
    region: 'South America',
    country: 'Brazil',
    commonIngredients: [
      'Cassava (mandioca/tapioca)', 'Black beans', 'Rice', 'Palm oil (dendê)', 'Coconut milk',
      'Cachaça (sugarcane spirit)', 'Farofa (toasted cassava flour)', 'Malagueta peppers',
      'Guaraná', 'Hearts of palm', 'Cashews (caju)', 'Cheese bread (pão de queijo)', 'Collard greens',
    ],
    recipeIds: ['feijoada', 'pao-de-queijo'],
    geographyNotes: "Brazil is the largest country in South America, covering nearly half the continent. The Amazon Basin contains the world's largest rainforest and river system. The country spans tropical, savanna, and subtropical climate zones, producing extraordinary agricultural diversity from açaí to coffee to soybeans.",
    foodHistory: "Brazil's food history begins with Indigenous peoples who domesticated cassava 10,000 years ago — now eaten by 800 million people worldwide. Portuguese colonization (1500) introduced livestock, sugar cane, wine, and wheat. The transatlantic slave trade brought over 4.9 million Africans whose food knowledge became the backbone of Brazilian cooking. Japanese immigration (early 1900s) added sushi and tempura influences. Brazil's multicultural food scene is now a celebrated global cuisine.",
    nutritionThemes: [
      'Complete protein from the iconic rice and beans combination',
      'Resistant starch from cassava supporting gut health',
      'Antioxidant-rich tropical fruits (açaí, cupuaçu, caju)',
      'Diverse plant nutrients from Amazon produce',
      'Heart-healthy coconut and olive oils',
    ],
    primaryColor: '#009C3B',
    accentColor: '#FFDF00',
    bgGradient: 'from-green-50 to-yellow-50',
    mapFact: 'Brazil is home to 60% of the Amazon rainforest and approximately 10% of all species on Earth.',
    languages: ['Portuguese', 'Guaraní', 'Japanese', 'Italian', 'German', 'Spanish'],
    population: '215 million',
    connections: [
      {
        cultureId: 'west-african',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Afro-Brazilian cuisine is West African cuisine',
        detail: 'Brazil received more enslaved Africans than any other nation — over 4.9 million people forcibly relocated from West Africa between 1500 and 1888. Afro-Brazilian cuisine from Bahia is essentially West African cooking in a tropical South American setting: acarajé (Yoruba akara), moqueca (palm oil stew), vatapá (peanut-shrimp paste). The word "feijoada" traces to African bean-cooking traditions brought by enslaved cooks.',
        sharedIngredients: ['Black-eyed peas', 'Palm oil (dendê)', 'Okra', 'Peanuts', 'Plantains', 'Dried shrimp'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'colonization',
        headline: "Portugal built Brazil's European pantry",
        detail: 'Portugal colonized Brazil for 322 years (1500–1822), bringing olive oil, wine, wheat, pork, salt cod (bacalhau), and Mediterranean stewing techniques. Portuguese culinary traditions — custard tarts (pastel de nata), salt cod dishes, and rice-based sides — fused with African and Indigenous techniques to create modern Brazilian cuisine. Brazil still consumes more salt cod than any other country.',
        sharedIngredients: ['Salt cod (bacalhau)', 'Olive oil', 'Garlic', 'Pork', 'Wine', 'Wheat'],
      },
      {
        cultureId: 'mexican',
        strength: 'moderate',
        linkType: 'geography',
        headline: 'Twin pillars of Latin American cuisine',
        detail: "Brazil and Mexico are Latin America's two culinary giants — both shaped by Indigenous peoples, Iberian colonization, and African diaspora in different proportions. Both cuisines built on cassava/corn and legumes; both have vibrant street food cultures; both inherited a mestizo food identity from the collision of three worlds. The rice-and-beans foundation unites both national tables.",
        sharedIngredients: ['Cassava/corn', 'Black beans', 'Chiles', 'Plantains', 'Pork', 'Rice'],
      },
    ],
  },
  {
    id: 'moroccan',
    name: 'Moroccan',
    emoji: '🇲🇦',
    tagline: 'Spice-perfumed tagines and the gateway between Africa and Europe',
    description: "Moroccan cuisine is a fragrant crossroads — where Berber, Arab, Andalusian, sub-Saharan African, and Mediterranean flavors converge in one of the world's most complex and aromatic culinary traditions. Built on slow-cooked tagines, fragrant couscous, preserved lemons, and the legendary spice blend ras el hanout, Moroccan food is a journey through 3,000 years of trade, empire, and cultural exchange.",
    region: 'North Africa (Maghreb)',
    country: 'Morocco',
    commonIngredients: [
      'Ras el hanout (spice blend)', 'Preserved lemons', 'Argan oil', 'Harissa paste',
      'Couscous', 'Chickpeas', 'Dates', 'Almonds & pistachios', 'Saffron', 'Cumin',
      'Coriander', 'Cinnamon', 'Honey', 'Orange blossom water', 'Olives & olive oil',
    ],
    recipeIds: ['chicken-tagine', 'harira'],
    geographyNotes: "Morocco sits at the northwest corner of Africa, bordered by the Atlantic Ocean, Mediterranean Sea, Algeria, and Mauritania. The Atlas and Rif Mountains create diverse microclimates from alpine to desert. Its position as a bridge between Africa, Europe, and the Middle East made Morocco a crossroads of civilization for 3,000 years.",
    foodHistory: "Moroccan cuisine developed from Berber (Amazigh) roots, enriched by Arab conquest (7th century) introducing Islam, spice trade networks, and Middle Eastern techniques. The Moors — Muslims and Jews expelled from Spain in 1492 — brought sophisticated Andalusian cuisine back to Morocco, blending European and Islamic traditions. The Ottoman Empire connected Morocco to Persian spice traditions. French colonization (1912–1956) influenced pastry and café culture. Morocco's complex spicing — ras el hanout contains 27+ spices — reflects its position at the intersection of the world's great spice routes.",
    nutritionThemes: [
      'Heart-healthy argan oil (unique to Morocco)',
      'Anti-inflammatory ras el hanout blend (turmeric, ginger, cinnamon)',
      'High fiber from chickpeas, lentils, and seasonal vegetables',
      'Probiotic preserved lemons and fermented condiments',
      'Antioxidant-rich dates, dried fruits, and saffron',
    ],
    primaryColor: '#C1272D',
    accentColor: '#D4AF37',
    bgGradient: 'from-red-50 to-amber-50',
    mapFact: 'Morocco has been continuously inhabited for over 300,000 years and home to some of humanity\'s earliest known settlements.',
    languages: ['Darija (Moroccan Arabic)', 'Amazigh (Berber)', 'French', 'Spanish'],
    population: '37 million',
    connections: [
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Two shores of the same sea',
        detail: 'Morocco and the Mediterranean world are separated by just 14 km of water at the Strait of Gibraltar, driving 3,000 years of exchange. Phoenicians founded Carthage in North Africa; Rome governed Morocco (Mauretania Tingitana); the Moors built the Alhambra in Spain and brought Andalusian cuisine back to Morocco; French colonialism ran in both directions. Olive oil, chickpeas, lamb, saffron, citrus, and almonds are shared ingredients across this common sea.',
        sharedIngredients: ['Olive oil', 'Chickpeas', 'Lamb', 'Saffron', 'Lemon', 'Almonds', 'Olives'],
      },
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'Ottoman and Moorish empires carried Persian flavors west',
        detail: 'Persian culinary philosophy — sweet-sour balance, dried fruit in savory dishes, saffron-gilded rice, nut-enriched sauces — traveled west through the Ottoman Empire and Moorish Andalusia into Morocco. Moroccan pastilla (a sweet-savory pigeon pie with almonds and cinnamon) is a direct Persian-influenced Moorish creation. Preserved lemons echo Persian dried limes; ras el hanout parallels Persian advieh spice blends.',
        sharedIngredients: ['Saffron', 'Dried fruits', 'Almonds', 'Cinnamon', 'Rose water', 'Lamb'],
      },
      {
        cultureId: 'west-african',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Trans-Saharan caravans ran for a millennium',
        detail: "For over 1,000 years, trans-Saharan trade caravans connected Moroccan cities like Fez and Marrakech to the Mali, Songhai, and Ghana empires of West Africa. Gold, salt, kola nuts, and dried fish moved north; cloth, ceramics, dates, and spices moved south. The Mali Empire's capital Timbuktu was a major hub of this exchange, creating lasting culinary cross-pollination between Maghrebi and Sahelian food traditions.",
        sharedIngredients: ['Millet', 'Dried fish', 'Dates', 'Dried peppers', 'Cumin', 'Chickpeas'],
      },
    ],
  },
];

export function getCultureById(id: string): Culture | undefined {
  return cultures.find((c) => c.id === id);
}
