import type { Culture } from './types';

export const cultures: Culture[] = [
  {
    id: 'filipino',
    name: 'Filipino',
    emoji: '🇵🇭',
    tagline: 'The hearty, sour, and savory soul of Southeast Asia',
    description: 'Filipino cuisine is a vibrant blend of Malay, Chinese, Spanish, and American influences, shaped by over 7,000 islands and centuries of trade. It celebrates bold contrasts — sour and salty, sweet and savory — with fermented ingredients, vinegar-braises, and tropical fruits at its core.',
    region: 'Southeast Asia',
    country: 'Philippines',
    commonIngredients: ['Vinegar', 'Soy sauce', 'Garlic', 'Pork belly', 'Fish sauce (patis)', 'Calamansi lime', 'Coconut milk', 'Tamarind', 'Banana blossom', 'Bagoong (shrimp paste)', 'Lemongrass', 'Annatto seeds', 'Longanisa', 'Rice', 'Palm sugar'],
    recipeIds: ['adobo', 'sinigang'],
    geographyNotes: 'The Philippines is an archipelago of 7,641 islands in Southeast Asia, bordered by the South China Sea to the west, the Philippine Sea to the east, and the Celebes Sea to the south.',
    foodHistory: 'Pre-colonial Filipino cuisine centered on rice, seafood, and tropical produce. Spanish colonization (1565–1898) introduced tomatoes, corn, chiles, and stewing techniques. Chinese traders brought noodles, tofu, and soy sauce. American influence added canned goods and fast food culture.',
    nutritionThemes: ['High in protein from fish, pork, and chicken', 'Rich in probiotics from fermented ingredients', 'Abundant tropical fruit antioxidants', 'Complex carbohydrates from rice', 'Heart-healthy coconut'],
    primaryColor: '#D4393B',
    accentColor: '#FCD116',
    bgGradient: 'from-red-50 to-yellow-50',
    mapFact: 'The Philippines spans over 300,000 km² and has more than 175 spoken languages.',
    languages: ['Filipino (Tagalog)', 'English', 'Cebuano', 'Ilocano'],
    population: '115 million',
    connections: [
      {
        cultureId: 'mexican',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'Both colonies of Spain',
        detail: 'Spain ruled the Philippines (1565–1898) and Mexico simultaneously, and the Manila-Acapulco Galleon Trade directly linked the two. Longanisa sausage mirrors Mexican chorizo; adobo mirrors Spanish-Mexican braising techniques.',
        sharedIngredients: ['Vinegar', 'Pork belly', 'Garlic', 'Annatto seeds'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Southeast Asian neighbors',
        detail: 'Filipino and Vietnamese kitchens share the same tropical pantry: fish sauce, tamarind, lemongrass, and coconut milk. Both cuisines use sour and umami contrasts as their backbone.',
        sharedIngredients: ['Fish sauce', 'Tamarind', 'Lemongrass', 'Coconut milk', 'Rice'],
      },
      {
        cultureId: 'indian',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Spice route connections',
        detail: 'Indian traders sailed to the Philippines for centuries before European colonization. Coconut milk, tamarind, and turmeric appear in both kitchens.',
        sharedIngredients: ['Coconut milk', 'Tamarind', 'Turmeric', 'Ginger'],
      },
      {
        cultureId: 'japanese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Pacific neighbors with ancient trade ties',
        detail: 'Japan and the Philippines traded across the Pacific for centuries. Both share a deep respect for rice, abundant seafood, and fermented fish-based umami.',
        sharedIngredients: ['Rice', 'Soy sauce', 'Seafood', 'Fermented fish sauce', 'Pork belly'],
      },
    ],
  },
  {
    id: 'mexican',
    name: 'Mexican',
    emoji: '🇲🇽',
    tagline: 'Ancient corn civilizations meet Spanish fire and flavor',
    description: 'Mexican cuisine — a UNESCO Intangible Cultural Heritage — is one of the world\'s most complex culinary traditions. Built on the "Three Sisters" of corn, beans, and squash, it layers indigenous Aztec and Maya traditions with Spanish, Caribbean, and African influences.',
    region: 'North America / Mesoamerica',
    country: 'Mexico',
    commonIngredients: ['Corn (masa, tortillas)', 'Dried chile peppers', 'Tomatoes & tomatillos', 'Avocado', 'Black beans & pinto beans', 'Cilantro', 'Lime', 'Cumin', 'Epazote', 'Mexican oregano', 'Chocolate (cacao)', 'Pumpkin seeds (pepitas)', 'Chayote', 'Nopales (cactus)', 'Queso fresco'],
    recipeIds: ['tamales', 'mole'],
    geographyNotes: 'Mexico sits in North America, bordered by the US to the north, the Pacific Ocean to the west, and the Gulf of Mexico and Caribbean Sea to the east.',
    foodHistory: 'Mexican food traces back 9,000 years to ancient Mesoamerican civilizations who domesticated corn. The Aztec empire cultivated cacao, vanilla, and tomatoes. Spanish conquistadors (1519) merged these with Mediterranean ingredients, creating "mestizo" cuisine.',
    nutritionThemes: ['Complete protein from corn + beans combination', 'Lycopene-rich tomatoes and tomatillos', 'Monounsaturated fats from avocado', 'Antioxidants from dark chocolate and chiles', 'High fiber from legumes and vegetables'],
    primaryColor: '#006847',
    accentColor: '#CE1126',
    bgGradient: 'from-green-50 to-red-50',
    mapFact: 'Mexico is the 13th largest country by area and home to 68 recognized indigenous languages.',
    languages: ['Spanish', 'Nahuatl', 'Yucatec Maya', 'Zapotec'],
    population: '130 million',
    connections: [
      {
        cultureId: 'filipino',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'Linked by the Manila Galleon',
        detail: 'The Manila-Acapulco Galleon Trade (1565–1815) was the world\'s first transpacific trade route. Mexican silver flowed to Asia; Filipino spices and Chinese goods flowed to Mexico.',
        sharedIngredients: ['Annatto seeds', 'Corn', 'Pork', 'Vinegar', 'Chocolate'],
      },
      {
        cultureId: 'southern',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Corn, chiles & African roots',
        detail: 'Both Southern American and Mexican cuisines are built on corn and shaped by African diaspora. Enslaved Africans in both regions transformed Indigenous ingredients.',
        sharedIngredients: ['Corn', 'Black-eyed peas', 'Chiles', 'Pork', 'Molasses'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'colonization',
        headline: 'Spanish brought the Mediterranean pantry',
        detail: 'Spanish colonizers who conquered Mexico came from a Mediterranean food tradition. They brought olive oil, wine, wheat, onions, garlic, and livestock to Mesoamerica.',
        sharedIngredients: ['Garlic', 'Onions', 'Olive oil', 'Wheat', 'Pork'],
      },
      {
        cultureId: 'brazilian',
        strength: 'moderate',
        linkType: 'geography',
        headline: 'Twin pillars of Latin American cuisine',
        detail: 'Brazil and Mexico are Latin America\'s two culinary giants — both shaped by Indigenous peoples, Iberian colonization, and African diaspora. Both built on cassava/corn and legumes.',
        sharedIngredients: ['Cassava/corn', 'Black beans', 'Chiles', 'Plantains', 'Pork', 'Rice'],
      },
    ],
  },
  {
    id: 'vietnamese',
    name: 'Vietnamese',
    emoji: '🇻🇳',
    tagline: 'Fresh herbs, bright broths, and the art of balance',
    description: 'Vietnamese cuisine is celebrated for its delicate balance of five fundamental tastes: spicy, sour, bitter, salty, and sweet. It emphasizes fresh herbs, minimal oil, and pure flavors.',
    region: 'Southeast Asia',
    country: 'Vietnam',
    commonIngredients: ['Rice noodles (pho, bun)', 'Fish sauce (nuoc mam)', 'Lemongrass', 'Fresh mint & basil', 'Bean sprouts', 'Lime', 'Star anise', 'Cinnamon', 'Ginger', 'Shallots', 'Hoisin sauce', 'Sriracha', 'Shrimp paste', 'Jasmine rice', 'Pork belly'],
    recipeIds: ['pho', 'spring-rolls'],
    geographyNotes: 'Vietnam stretches 1,650 km along the eastern edge of the Indochina Peninsula, bordered by China, Laos, Cambodia, and the South China Sea.',
    foodHistory: 'Vietnamese cuisine developed over 4,000 years, strongly influenced by Chinese rule (111 BCE–938 CE), which introduced chopsticks, woks, and soy-based sauces. French colonization (1887–1954) added baguettes, pâté, and coffee culture.',
    nutritionThemes: ['High in fresh vegetables and herbs', 'Lean protein from seafood and pork', 'Probiotic-rich fermented ingredients', 'Low fat cooking methods (steaming, boiling)', 'Collagen-rich bone broths'],
    primaryColor: '#DA251D',
    accentColor: '#FFCD00',
    bgGradient: 'from-red-50 to-amber-50',
    mapFact: 'Vietnam has over 3,200 km of coastline and is one of the world\'s top rice exporters.',
    languages: ['Vietnamese', 'Khmer', 'Cham', 'Muong'],
    population: '98 million',
    connections: [
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'France left a baguette behind',
        detail: 'French colonization of Vietnam (1887–1954) permanently altered Vietnamese food. Bánh mì is a Vietnamese baguette. Pâté, coffee culture, and custard are French-Vietnamese fusions.',
        sharedIngredients: ['Wheat bread', 'Pâté', 'Coffee', 'Caramel'],
      },
      {
        cultureId: 'filipino',
        strength: 'strong',
        linkType: 'geography',
        headline: 'The fish sauce belt',
        detail: 'Vietnam and the Philippines anchor the Southeast Asian fish sauce tradition. Both cultures ferment small fish into their most essential condiment.',
        sharedIngredients: ['Fish sauce', 'Tamarind', 'Rice noodles', 'Bean sprouts', 'Lemongrass'],
      },
      {
        cultureId: 'persian',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Silk Road spice exchange',
        detail: 'The ancient Silk Road carried Persian saffron, dried fruits, and spice-layering techniques eastward. Star anise — the defining spice of phở — traveled this route.',
        sharedIngredients: ['Star anise', 'Cinnamon', 'Ginger', 'Cardamom'],
      },
      {
        cultureId: 'japanese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'East Asian noodle culture and Buddhist cuisine',
        detail: 'Japan and Vietnam both built celebrated noodle cultures from Chinese roots — ramen and phở are cousins. Buddhist temple cuisine created parallel vegetarian cooking traditions.',
        sharedIngredients: ['Rice noodles', 'Soy sauce', 'Sesame', 'Ginger', 'Green tea', 'Fermented condiments'],
      },
    ],
  },
  {
    id: 'persian',
    name: 'Persian',
    emoji: '🇮🇷',
    tagline: 'Saffron-gilded poetry on a plate from ancient Persia',
    description: 'Persian cuisine is one of the world\'s oldest and most sophisticated culinary traditions, dating back 2,500 years to the Achaemenid Empire. It is defined by the artful use of dried fruits, nuts, fragrant rice, and precious spices like saffron.',
    region: 'Middle East / Central Asia',
    country: 'Iran',
    commonIngredients: ['Saffron', 'Rose water', 'Barberries (zereshk)', 'Dried limes (limu omani)', 'Walnuts', 'Pomegranate molasses', 'Fresh dill, parsley, cilantro, fenugreek', 'Lamb', 'Long-grain basmati rice', 'Split chickpeas', 'Kashk (whey)', 'Turmeric', 'Dried apricots', 'Chickpeas', 'Ghee'],
    recipeIds: ['ghormeh-sabzi', 'tahdig'],
    geographyNotes: 'Iran (ancient Persia) spans 1.6 million km² in the Middle East, bordered by Turkey, Iraq, the Caspian Sea, Afghanistan, and Pakistan.',
    foodHistory: 'Persian food culture stretches back to the Achaemenid Empire (550–330 BCE). Persian food spread through Silk Road trade routes to influence Indian Mughal cuisine, Ottoman Turkish cooking, and Arab traditions.',
    nutritionThemes: ['Rich in omega-3s from walnuts and fish', 'Antioxidants from pomegranate and saffron', 'Anti-inflammatory turmeric and herbs', 'Plant-forward cooking with legumes', 'Probiotic kashk and fermented dairy'],
    primaryColor: '#239F40',
    accentColor: '#DA0000',
    bgGradient: 'from-green-50 to-rose-50',
    mapFact: 'Iran is home to one of the oldest civilizations on Earth, with settlements dating back 7,000+ years.',
    languages: ['Persian (Farsi)', 'Azerbaijani', 'Kurdish', 'Arabic'],
    population: '87 million',
    connections: [
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'The Mughal Empire merged two cuisines',
        detail: 'The Mughal emperors (1526–1857) were Persian-speaking Central Asians who ruled India for 300 years. Biryani is a direct Persian-Indian fusion. Korma, haleem, and kebab all trace to this empire.',
        sharedIngredients: ['Saffron', 'Basmati rice', 'Ghee', 'Cardamom', 'Rose water', 'Dried fruits'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Ancient empires, shared pantry',
        detail: 'The Persian and Mediterranean worlds overlapped constantly. Pomegranate, eggplant, lamb, chickpeas, and pistachios flow freely between Persian and Mediterranean kitchens.',
        sharedIngredients: ['Pomegranate', 'Eggplant', 'Lamb', 'Chickpeas', 'Pistachios', 'Lemon'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'The Silk Road ran both ways',
        detail: 'Persia was the commercial hub of the ancient world. Persian merchants carried saffron, dried limes, and layered spice blends east along the Silk Road. Star anise traveled west; saffron traveled east.',
        sharedIngredients: ['Star anise', 'Cinnamon', 'Cardamom', 'Dried limes', 'Turmeric'],
      },
      {
        cultureId: 'moroccan',
        strength: 'strong',
        linkType: 'empire',
        headline: 'Ottoman and Moorish empires carried Persian flavors west',
        detail: 'Persian culinary philosophy — sweet-sour balance, dried fruit in savory dishes, saffron-gilded rice — traveled west through the Ottoman Empire and Moorish Andalusia into Morocco.',
        sharedIngredients: ['Saffron', 'Dried fruits', 'Almonds', 'Cinnamon', 'Rose water', 'Lamb'],
      },
    ],
  },
  {
    id: 'indian',
    name: 'Indian',
    emoji: '🇮🇳',
    tagline: 'A spice-trader\'s paradise with 5,000 years of flavor',
    description: 'Indian cuisine is not one cuisine but a vast constellation of regional traditions spanning 28 states, shaped by geography, religion, season, and ancient Ayurvedic principles.',
    region: 'South Asia',
    country: 'India',
    commonIngredients: ['Turmeric', 'Cumin', 'Coriander', 'Cardamom', 'Garam masala', 'Mustard seeds', 'Ghee', 'Paneer', 'Lentils (dal)', 'Basmati rice', 'Coconut milk', 'Tamarind', 'Fenugreek seeds', 'Curry leaves', 'Hing (asafoetida)', 'Chana (chickpeas)'],
    recipeIds: ['biryani', 'dal-tadka'],
    geographyNotes: 'India is the 7th largest country, spanning from the Himalayas in the north to tropical coastlines in the south.',
    foodHistory: 'Indian culinary history spans 5,000+ years. The Silk Road brought spices westward to Rome and Europe. Mughal emperors (1526–1857) created biryani and korma. British colonization (1858–1947) influenced tea culture.',
    nutritionThemes: ['Complete protein from dal + rice or roti', 'Anti-inflammatory spice compounds (curcumin)', 'Probiotic-rich lassi, yogurt, and fermented dosas', 'Fiber from legumes and vegetables', 'Ayurvedic balance of six tastes'],
    primaryColor: '#FF9933',
    accentColor: '#138808',
    bgGradient: 'from-orange-50 to-green-50',
    mapFact: 'India is home to over 22 official languages and more than 1,600 dialects.',
    languages: ['Hindi', 'Bengali', 'Tamil', 'Telugu', 'Marathi', 'Urdu', 'English'],
    population: '1.4 billion',
    connections: [
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'Mughal fusion created North Indian cuisine',
        detail: 'Mughal emperors were Persian in language, culture, and taste — and they ruled India for over 300 years. Biryani, korma, naan, and kebab culture all trace to this Persian-Indian fusion.',
        sharedIngredients: ['Saffron', 'Basmati rice', 'Cardamom', 'Rose water', 'Ghee', 'Pistachios'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Ancient spice trade neighbors',
        detail: 'Indian traders were sailing to Southeast Asia millennia before Europeans arrived. The Tagalog word for "curry" (kari) is Sanskrit. Coconut milk, tamarind souring, and turmeric coloring appear in both cuisines.',
        sharedIngredients: ['Tamarind', 'Coconut milk', 'Turmeric', 'Ginger', 'Mustard seeds'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Rome\'s most valuable imports came from India',
        detail: 'Roman historian Pliny complained that India was draining Rome\'s treasury through spice purchases. Black pepper, cardamom, and cinnamon — Indian exports — were worth more than gold in ancient Rome.',
        sharedIngredients: ['Black pepper', 'Cardamom', 'Cinnamon', 'Turmeric', 'Lentils', 'Chickpeas'],
      },
      {
        cultureId: 'ethiopian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Red Sea trade routes ran for millennia',
        detail: 'The ancient Red Sea trade route directly connected Indian ports to the Ethiopian port of Adulis. India exported cumin, cardamom, turmeric, and ginger, which became central to Ethiopian berbere spice blends.',
        sharedIngredients: ['Cardamom', 'Turmeric', 'Ginger', 'Fenugreek', 'Cumin', 'Lentils', 'Clarified butter'],
      },
    ],
  },
  {
    id: 'southern',
    name: 'Southern American',
    emoji: '🌽',
    tagline: 'Soul food, smoke, and the roots of American cooking',
    description: 'Southern American cuisine is the deeply soulful cooking tradition born from the American South — a fusion of West African, Native American, and European culinary traditions forged through resilience and community.',
    region: 'North America',
    country: 'United States (South)',
    commonIngredients: ['Cornmeal & grits', 'Collard greens', 'Black-eyed peas', 'Sweet potatoes', 'Okra', 'Buttermilk', 'Lard & bacon fat', 'Smoked pork', 'Hot sauce', 'Molasses', 'Peanuts', 'Peaches', 'Sorghum syrup', 'Cast iron cookware', 'Church lady seasoning'],
    recipeIds: ['fried-chicken', 'shrimp-grits'],
    geographyNotes: 'The American South encompasses states from Virginia to Texas, including the Mississippi River Delta, Appalachian Mountains, Gulf Coast, and Atlantic coastal lowlands.',
    foodHistory: 'Southern food is inseparable from the history of African enslavement. Enslaved Africans brought okra, black-eyed peas, rice cultivation, and technique to American kitchens. Native Americans contributed corn, beans, squash, and game.',
    nutritionThemes: ['High fiber from beans, peas, and greens', 'Potassium and vitamins from sweet potatoes', 'Probiotic-rich fermented hot sauces', 'Plant diversity in seasonal produce', 'Iron from cast-iron cooking methods'],
    primaryColor: '#8B4513',
    accentColor: '#DAA520',
    bgGradient: 'from-amber-50 to-orange-50',
    mapFact: 'The Mississippi Delta region is called the "cradle of American music and food culture."',
    languages: ['English', 'Gullah Geechee', 'Louisiana Creole'],
    population: '130 million (US South)',
    connections: [
      {
        cultureId: 'mexican',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Corn culture runs deep in both',
        detail: 'Southern American and Mexican cuisine share corn as their foundation — cornbread mirrors tortillas; grits mirror masa. The Gulf Coast border zone created Tex-Mex, and tamales are made in Mississippi Delta communities.',
        sharedIngredients: ['Corn', 'Chiles', 'Pork', 'Black-eyed peas', 'Molasses'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'colonization',
        headline: 'European settlers shaped the South',
        detail: 'Scottish, Irish, French, and Spanish colonizers brought Mediterranean and Northern European cooking to the American South — cast iron from France, pastry from the British Isles.',
        sharedIngredients: ['Olive oil', 'Wheat', 'Pork', 'Butter', 'Wine'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'ingredient',
        headline: "The African diaspora's global pantry",
        detail: 'Enslaved Africans brought okra, black-eyed peas, rice cultivation, and cooking techniques to the American South — and many of these same ingredients traveled via the African diaspora to Southeast Asia.',
        sharedIngredients: ['Okra', 'Rice', 'Coconut', 'Fermented fish paste'],
      },
      {
        cultureId: 'west-african',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Soul food IS West African food',
        detail: 'Enslaved West Africans were forced across the Atlantic carrying their crops, techniques, and knowledge. Okra, black-eyed peas, watermelon, rice cultivation, and peanuts traveled with them. Gumbo derives from the Bantu word "ki ngombo" (okra).',
        sharedIngredients: ['Okra', 'Black-eyed peas', 'Peanuts', 'Watermelon', 'Rice', 'Corn', 'Sweet potatoes'],
      },
    ],
  },
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    emoji: '🫒',
    tagline: 'Olive oil, sunshine, and the world\'s healthiest diet',
    description: 'Mediterranean cuisine encompasses the cooking traditions of countries bordering the Mediterranean Sea — Greece, Italy, Spain, Morocco, Lebanon, Turkey, and more. United by olive oil, fresh vegetables, legumes, whole grains, seafood, and wine.',
    region: 'Europe / Middle East / North Africa',
    country: 'Multiple (Greece, Italy, Spain, Lebanon, Morocco)',
    commonIngredients: ['Extra-virgin olive oil', 'Kalamata olives', 'Feta & halloumi cheese', 'Tomatoes', 'Eggplant (aubergine)', 'Lamb', 'Chickpeas', 'Tahini', 'Lemon', 'Oregano & thyme', "Za'atar", 'Grape leaves', 'Pomegranate', 'Capers', 'Pine nuts'],
    recipeIds: ['hummus', 'shakshuka'],
    geographyNotes: 'The Mediterranean Sea is bordered by 21 countries across three continents. The climate — hot, dry summers and mild, wet winters — is perfect for olive trees, grapes, wheat, and citrus.',
    foodHistory: 'Mediterranean food traces back to ancient Greek and Roman civilizations. The Ottoman Empire unified many traditions across Turkey, the Middle East, and North Africa.',
    nutritionThemes: ['Heart-healthy monounsaturated fats from olive oil', 'Anti-inflammatory polyphenols in olives and wine', 'Omega-3 fatty acids from fresh fish', 'High fiber from legumes and whole grains', 'Antioxidant-rich vegetables and herbs'],
    primaryColor: '#1E6FBF',
    accentColor: '#C0A060',
    bgGradient: 'from-blue-50 to-amber-50',
    mapFact: 'The Mediterranean Sea covers 2.5 million km² and has been a center of world trade for 5,000 years.',
    languages: ['Greek', 'Italian', 'Spanish', 'Arabic', 'Turkish', 'French', 'Hebrew'],
    population: '500 million (Mediterranean basin)',
    connections: [
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Two ancient empires, one pantry',
        detail: 'Persia and the Mediterranean world were deeply entangled for 3,000 years. The Ottoman Empire unified Mediterranean and Persian cooking for 600 years.',
        sharedIngredients: ['Pomegranate', 'Eggplant', 'Chickpeas', 'Lamb', 'Saffron', 'Pistachios'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'France bridges Southeast Asia and the Mediterranean',
        detail: 'French colonial cuisine created a remarkable bridge: baguettes, café au lait, and crème caramel traveled from France\'s Mediterranean-influenced culture into Vietnam.',
        sharedIngredients: ['Wheat bread', 'Coffee', 'Butter', 'Wine', 'Herbs (thyme, bay, parsley)'],
      },
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'The spice trade built both kitchens',
        detail: 'Roman cookbooks call for black pepper in nearly every dish — all imported from India. The search for a sea route to India\'s spices launched the Age of Exploration.',
        sharedIngredients: ['Black pepper', 'Cardamom', 'Cinnamon', 'Ginger', 'Lentils', 'Chickpeas'],
      },
      {
        cultureId: 'moroccan',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Two shores of the same sea',
        detail: 'Morocco and the Mediterranean world are separated by just 14 km of water at the Strait of Gibraltar, driving 3,000 years of exchange.',
        sharedIngredients: ['Olive oil', 'Chickpeas', 'Lamb', 'Saffron', 'Lemon', 'Almonds', 'Olives'],
      },
    ],
  },
  {
    id: 'japanese',
    name: 'Japanese',
    emoji: '🇯🇵',
    tagline: 'Umami mastery, seasonal harmony, and the art of impermanence',
    description: 'Japanese cuisine — washoku, a UNESCO Intangible Cultural Heritage — is built on the philosophy of balance, seasonality, and harmony. It achieves incredible depth through fermentation, dashi broth, and the five-taste principle of umami.',
    region: 'East Asia',
    country: 'Japan',
    commonIngredients: ['Soy sauce (shoyu)', 'Miso paste', 'Mirin', 'Sake', 'Dashi (kombu + bonito)', 'Tofu', 'Short-grain rice', 'Nori (seaweed)', 'Wasabi', 'Pickled ginger', 'Sesame oil', 'Panko breadcrumbs', 'Ramen noodles', 'Tempura batter', 'Matcha'],
    recipeIds: ['ramen', 'onigiri'],
    geographyNotes: 'Japan is an archipelago of 6,852 islands in the Pacific Ocean stretching 3,000 km along East Asia. Surrounded by ocean, Japan developed a profound seafood culture.',
    foodHistory: 'Japanese cuisine evolved over 2,000 years, influenced by Chinese Buddhism (introducing vegetarian temple food, tofu, and noodles), Korean rice culture, and Portuguese traders who arrived in 1543 (bringing tempura frying technique).',
    nutritionThemes: ['Low-calorie, high-nutrient washoku diet associated with longevity', 'Omega-3 rich seafood and mineral-rich seaweed', 'Probiotic-rich miso, natto, and tsukemono pickles', 'Portion mindfulness and variety (ichiju sansai principle)', 'Anti-aging polyphenols from green tea'],
    primaryColor: '#BC002D',
    accentColor: '#F5A623',
    bgGradient: 'from-red-50 to-orange-50',
    mapFact: 'Japan has the world\'s longest life expectancy, partly attributed to the traditional washoku diet.',
    languages: ['Japanese'],
    population: '125 million',
    connections: [
      {
        cultureId: 'korean',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Fermentation neighbors across the strait',
        detail: 'Korea and Japan are separated by just 200 km and share millennia of exchange. Buddhism traveled Korea→Japan carrying vegetarian temple cuisine. Doenjang and miso use identical fermentation processes.',
        sharedIngredients: ['Fermented soybean paste', 'Soy sauce', 'Rice', 'Sesame', 'Seaweed', 'Pickled vegetables'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'East Asian noodle culture and Buddhist traditions',
        detail: 'Japan and Vietnam both built celebrated noodle cultures from Chinese roots — ramen and phở are cousins with different personalities. Buddhist temple cuisine created similar vegetarian traditions in both countries.',
        sharedIngredients: ['Rice noodles', 'Soy sauce', 'Sesame', 'Ginger', 'Green tea', 'Fermented condiments'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Pacific neighbors with centuries of trade',
        detail: 'Japan and the Philippines traded across the Pacific for centuries. Both cuisines share a deep respect for rice, abundant seafood, and fish-based umami.',
        sharedIngredients: ['Rice', 'Soy sauce', 'Seafood', 'Fermented fish sauce', 'Pork belly'],
      },
    ],
  },
  {
    id: 'korean',
    name: 'Korean',
    emoji: '🇰🇷',
    tagline: 'Bold banchan, fermented flavors, and communal table culture',
    description: 'Korean cuisine is a study in contrasts — fiery and cooling, fermented and fresh, intensely flavored yet precisely balanced. It is built around rice, fermented vegetables (kimchi), gochujang chile paste, and the tradition of banchan (small shared side dishes).',
    region: 'East Asia',
    country: 'South Korea / North Korea',
    commonIngredients: ['Gochujang (chile paste)', 'Doenjang (fermented soybean paste)', 'Soy sauce (ganjang)', 'Sesame oil', 'Garlic', 'Ginger', 'Kimchi', 'Short-grain rice', 'Glass noodles (dangmyeon)', 'Perilla leaves', 'Nori', 'Dried anchovies (myeolchi)', 'Rice wine (makgeolli)', 'Tofu', 'Bean sprouts'],
    recipeIds: ['bibimbap', 'japchae'],
    geographyNotes: 'The Korean Peninsula extends southward from northeast China. Korea\'s mountainous terrain shaped a root vegetable and forage-heavy cuisine, while coastal communities developed rich seafood traditions.',
    foodHistory: 'Korean food culture stretches back 5,000+ years. Buddhism (introduced 372 CE) shaped vegetarian temple cuisine. The Joseon Dynasty (1392–1897) codified Korean court cuisine and formalized kimchi-making.',
    nutritionThemes: ['Probiotic-rich kimchi and fermented vegetables supporting gut health', 'Low-fat cooking with abundant plant diversity', 'Anti-inflammatory gochujang, garlic, and ginger', 'Mineral-rich seaweed and seafood', 'High fiber from diverse banchan side dishes'],
    primaryColor: '#003478',
    accentColor: '#CD2E3A',
    bgGradient: 'from-blue-50 to-red-50',
    mapFact: 'South Korea consumes more instant ramen per capita than any other country in the world.',
    languages: ['Korean'],
    population: '52 million (South Korea), 26 million (North Korea)',
    connections: [
      {
        cultureId: 'japanese',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Fermentation neighbors across the strait',
        detail: 'Korea and Japan are separated by just 200 km. Doenjang and miso use identical fermentation processes. Buddhism traveled Korea→Japan carrying vegetarian temple food and fermentation knowledge.',
        sharedIngredients: ['Fermented soybean paste', 'Soy sauce', 'Rice', 'Sesame', 'Seaweed', 'Pickled vegetables'],
      },
      {
        cultureId: 'vietnamese',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'East Asian fermentation belt',
        detail: 'Korea and Vietnam both sit within the East Asian fermentation belt — where rice, soybeans, and seafood are transformed into complex condiments. Korean kimchi parallels Vietnamese dưa cải.',
        sharedIngredients: ['Fermented vegetables', 'Fish sauce', 'Rice', 'Sesame', 'Ginger', 'Chiles'],
      },
      {
        cultureId: 'filipino',
        strength: 'moderate',
        linkType: 'geography',
        headline: 'Pacific Rim pantry cousins',
        detail: 'Korea and the Philippines share the Pacific Rim. Both cuisines feature pork belly as a celebration meat, fermented shrimp paste (Korean saeujeot mirrors Filipino bagoong), and rice as the foundation.',
        sharedIngredients: ['Pork belly', 'Fermented shrimp paste', 'Soy sauce', 'Rice', 'Sesame', 'Ginger'],
      },
    ],
  },
  {
    id: 'west-african',
    name: 'West African',
    emoji: '🌍',
    tagline: 'The pantry that fed the world — bold stews and ancient grains',
    description: 'West African cuisine — from Nigeria, Ghana, Senegal, and beyond — is one of the world\'s most important and underrecognized culinary traditions. It is the source cuisine of Southern American soul food, Brazilian feijoada, and Caribbean cooking.',
    region: 'Sub-Saharan Africa',
    country: 'Nigeria, Ghana, Senegal, Ivory Coast',
    commonIngredients: ['Palm oil', 'Okra', 'Black-eyed peas', 'Cassava (yuca)', 'Yams', 'Plantains', 'Groundnuts (peanuts)', 'Scotch bonnet peppers', 'Stockfish (dried cod)', 'Egusi (melon seeds)', 'Fermented locust beans (dawadawa)', 'Ginger', 'Dried crayfish', 'Corn (maize)', 'Fonio'],
    recipeIds: ['jollof-rice', 'egusi-soup'],
    geographyNotes: 'West Africa spans from Senegal in the northwest to Nigeria in the east, along the Gulf of Guinea coastline.',
    foodHistory: 'The transatlantic slave trade (1500s–1800s) forcibly carried West African crops, techniques, and cooks across the Atlantic — permanently transforming Southern American, Brazilian, and Caribbean cuisines. Okra, black-eyed peas, rice cultivation, and peanuts all traveled this route.',
    nutritionThemes: ['Plant-based protein from legumes, seeds, and fermented ingredients', 'Beta-carotene and Vitamin A from palm oil and orange vegetables', 'Antioxidant scotch bonnet peppers and ginger', 'Complex carbohydrates from root vegetables and ancient grains', 'Omega-3s from dried fish and seafood'],
    primaryColor: '#008751',
    accentColor: '#FCD116',
    bgGradient: 'from-green-50 to-yellow-50',
    mapFact: 'West Africa is home to over 500 distinct ethnic groups, each with their own food traditions.',
    languages: ['Yoruba', 'Igbo', 'Hausa', 'Twi', 'Wolof', 'Fula', 'English', 'French'],
    population: '420 million',
    connections: [
      {
        cultureId: 'southern',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Soul food IS West African food',
        detail: 'Enslaved West Africans were forced across the Atlantic carrying their crops, techniques, and knowledge. Gumbo derives from the Bantu word "ki ngombo" (okra). Black-eyed peas on New Year\'s Day is a direct West African tradition.',
        sharedIngredients: ['Okra', 'Black-eyed peas', 'Peanuts', 'Watermelon', 'Rice', 'Corn', 'Sweet potatoes'],
      },
      {
        cultureId: 'brazilian',
        strength: 'strong',
        linkType: 'migration',
        headline: 'African diaspora built Brazilian cuisine',
        detail: 'Brazil received more enslaved Africans than any other country — over 4.9 million people. Afro-Brazilian cuisine directly reflects West African traditions: acarajé mirrors Yoruba akara; dendê palm oil traces to Nigerian cooking.',
        sharedIngredients: ['Black-eyed peas', 'Palm oil', 'Okra', 'Plantains', 'Dried fish', 'Peanuts'],
      },
      {
        cultureId: 'moroccan',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Trans-Saharan caravans connected West Africa and North Africa',
        detail: 'For over 1,000 years, trans-Saharan trade caravans connected West African empires to Moroccan cities. Gold, salt, kola nuts, and dried fish moved north; textiles, ceramics, dates, and spices moved south.',
        sharedIngredients: ['Dried fish', 'Millet', 'Dates', 'Dried peppers', 'Cumin', 'Chickpeas'],
      },
    ],
  },
  {
    id: 'ethiopian',
    name: 'Ethiopian',
    emoji: '🇪🇹',
    tagline: 'Injera-laden communal feasts from the Horn of Africa',
    description: 'Ethiopian cuisine is one of Africa\'s most sophisticated culinary traditions, built around injera — a spongy, sour sourdough flatbread made from teff — served communally with colorful stews (wats). Ethiopia was never colonized and thus preserved its ancient food traditions intact.',
    region: 'East Africa (Horn of Africa)',
    country: 'Ethiopia',
    commonIngredients: ['Teff (injera grain)', 'Berbere spice blend', 'Mitmita', 'Niter kibbeh (spiced butter)', 'Red lentils (misir)', 'Chickpeas (shimbra)', 'Fenugreek', 'Turmeric', 'Cardamom', 'Ginger', 'Black cumin (tikur azmud)', 'Fava beans (ful)', 'Chicken (doro)', 'Ayib (fresh cheese)'],
    recipeIds: ['misir-wat', 'doro-wat'],
    geographyNotes: 'Ethiopia sits on the Horn of Africa, bordered by Eritrea, Djibouti, Somalia, Kenya, South Sudan, and Sudan. The Ethiopian Highlands are one of Africa\'s most fertile regions.',
    foodHistory: 'Ethiopia has 3,000 years of recorded culinary history. The ancient Kingdom of Axum developed Red Sea trade routes to Arabia and India. Ethiopia is the birthplace of coffee. Orthodox Christian fasting traditions — over 180 fasting days per year — created one of the world\'s richest vegan cuisines.',
    nutritionThemes: ['Iron-rich teff grain (contains more iron than wheat or barley)', 'Complete protein from diverse legume-forward diet', 'Probiotic injera sourdough fermentation', 'Anti-inflammatory berbere spice blend', 'Exceptionally high fiber from the plant-forward fasting diet'],
    primaryColor: '#078930',
    accentColor: '#FCDD09',
    bgGradient: 'from-green-50 to-yellow-50',
    mapFact: 'Ethiopia is the birthplace of coffee and home to some of the world\'s oldest Christian and Jewish communities.',
    languages: ['Amharic', 'Oromo', 'Somali', 'Tigrinya', 'Sidama'],
    population: '126 million',
    connections: [
      {
        cultureId: 'indian',
        strength: 'strong',
        linkType: 'trade',
        headline: 'Red Sea trade routes ran for millennia',
        detail: 'The ancient Red Sea trade route directly connected Indian ports to the Ethiopian port of Adulis. India exported cumin, cardamom, turmeric, and ginger — all now central to Ethiopian berbere spice blends.',
        sharedIngredients: ['Cardamom', 'Turmeric', 'Ginger', 'Fenugreek', 'Cumin', 'Lentils', 'Clarified butter'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Ancient empires met at the Red Sea',
        detail: 'The Roman Empire and its Byzantine successor both traded actively with Ethiopia — the Kingdom of Axum was one of four great powers recognized by Rome.',
        sharedIngredients: ['Olive oil', 'Lentils', 'Chickpeas', 'Honey wine', 'Herbs', 'Lamb'],
      },
      {
        cultureId: 'moroccan',
        strength: 'moderate',
        linkType: 'geography',
        headline: 'Spice-layered cousins across the continent',
        detail: 'Morocco and Ethiopia share the African tradition of building complexity through many spices combined into characteristic blends — ras el hanout in Morocco, berbere in Ethiopia.',
        sharedIngredients: ['Berbere spices', 'Lentils', 'Chickpeas', 'Cumin', 'Cinnamon', 'Ginger', 'Lamb'],
      },
    ],
  },
  {
    id: 'brazilian',
    name: 'Brazilian',
    emoji: '🇧🇷',
    tagline: 'Feijoada feasts and tropical abundance from the Amazon',
    description: 'Brazilian cuisine is one of the world\'s great fusion traditions — a three-way convergence of Indigenous Amazonian peoples, West African enslaved cooks, and Portuguese colonizers. The result is staggeringly diverse and deeply soulful.',
    region: 'South America',
    country: 'Brazil',
    commonIngredients: ['Cassava (mandioca/tapioca)', 'Black beans', 'Rice', 'Palm oil (dendê)', 'Coconut milk', 'Cachaça (sugarcane spirit)', 'Farofa (toasted cassava flour)', 'Malagueta peppers', 'Guaraná', 'Hearts of palm', 'Cashews (caju)', 'Cheese bread (pão de queijo)', 'Collard greens'],
    recipeIds: ['feijoada', 'pao-de-queijo'],
    geographyNotes: 'Brazil is the largest country in South America, covering nearly half the continent. The Amazon Basin contains the world\'s largest rainforest and river system.',
    foodHistory: 'Brazil\'s food history begins with Indigenous peoples who domesticated cassava 10,000 years ago. Portuguese colonization (1500) introduced livestock, sugar cane, and wheat. The transatlantic slave trade brought over 4.9 million Africans whose food knowledge became the backbone of Brazilian cooking.',
    nutritionThemes: ['Complete protein from the iconic rice and beans combination', 'Resistant starch from cassava supporting gut health', 'Antioxidant-rich tropical fruits (açaí, cupuaçu, caju)', 'Diverse plant nutrients from Amazon produce', 'Heart-healthy coconut and olive oils'],
    primaryColor: '#009C3B',
    accentColor: '#FFDF00',
    bgGradient: 'from-green-50 to-yellow-50',
    mapFact: 'Brazil is home to 60% of the Amazon rainforest and approximately 10% of all species on Earth.',
    languages: ['Portuguese', 'Guaraní', 'Japanese', 'Italian', 'German', 'Spanish'],
    population: '215 million',
    connections: [
      {
        cultureId: 'west-african',
        strength: 'strong',
        linkType: 'migration',
        headline: 'Afro-Brazilian cuisine is West African cuisine',
        detail: 'Brazil received more enslaved Africans than any other nation — over 4.9 million people. Afro-Brazilian cuisine from Bahia is essentially West African cooking in a tropical South American setting.',
        sharedIngredients: ['Black-eyed peas', 'Palm oil (dendê)', 'Okra', 'Peanuts', 'Plantains', 'Dried shrimp'],
      },
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'colonization',
        headline: 'Portugal built Brazil\'s European pantry',
        detail: 'Portugal colonized Brazil for 322 years (1500–1822), bringing olive oil, wine, wheat, pork, salt cod (bacalhau), and Mediterranean stewing techniques.',
        sharedIngredients: ['Salt cod (bacalhau)', 'Olive oil', 'Garlic', 'Pork', 'Wine', 'Wheat'],
      },
      {
        cultureId: 'mexican',
        strength: 'moderate',
        linkType: 'geography',
        headline: 'Twin pillars of Latin American cuisine',
        detail: 'Brazil and Mexico are Latin America\'s two culinary giants — both shaped by Indigenous peoples, Iberian colonization, and African diaspora. Both built on cassava/corn and legumes.',
        sharedIngredients: ['Cassava/corn', 'Black beans', 'Chiles', 'Plantains', 'Pork', 'Rice'],
      },
    ],
  },
  {
    id: 'moroccan',
    name: 'Moroccan',
    emoji: '🇲🇦',
    tagline: 'Spice-perfumed tagines and the gateway between Africa and Europe',
    description: 'Moroccan cuisine is a fragrant crossroads — where Berber, Arab, Andalusian, sub-Saharan African, and Mediterranean flavors converge in one of the world\'s most complex and aromatic culinary traditions.',
    region: 'North Africa (Maghreb)',
    country: 'Morocco',
    commonIngredients: ['Ras el hanout (spice blend)', 'Preserved lemons', 'Argan oil', 'Harissa paste', 'Couscous', 'Chickpeas', 'Dates', 'Almonds & pistachios', 'Saffron', 'Cumin', 'Coriander', 'Cinnamon', 'Honey', 'Orange blossom water', 'Olives & olive oil'],
    recipeIds: ['chicken-tagine', 'harira'],
    geographyNotes: 'Morocco sits at the northwest corner of Africa, bordered by the Atlantic Ocean, Mediterranean Sea, Algeria, and Mauritania. Its position as a bridge between Africa, Europe, and the Middle East made it a crossroads of civilization.',
    foodHistory: 'Moroccan cuisine developed from Berber (Amazigh) roots, enriched by Arab conquest (7th century). The Moors — Muslims expelled from Spain in 1492 — brought sophisticated Andalusian cuisine back to Morocco. Morocco\'s complex spicing — ras el hanout contains 27+ spices — reflects its position at the intersection of the world\'s great spice routes.',
    nutritionThemes: ['Heart-healthy argan oil (unique to Morocco)', 'Anti-inflammatory ras el hanout blend', 'High fiber from chickpeas, lentils, and seasonal vegetables', 'Probiotic preserved lemons and fermented condiments', 'Antioxidant-rich dates, dried fruits, and saffron'],
    primaryColor: '#C1272D',
    accentColor: '#D4AF37',
    bgGradient: 'from-red-50 to-amber-50',
    mapFact: 'Morocco has been continuously inhabited for over 300,000 years.',
    languages: ['Darija (Moroccan Arabic)', 'Amazigh (Berber)', 'French', 'Spanish'],
    population: '37 million',
    connections: [
      {
        cultureId: 'mediterranean',
        strength: 'strong',
        linkType: 'geography',
        headline: 'Two shores of the same sea',
        detail: 'Morocco and the Mediterranean world are separated by just 14 km of water at the Strait of Gibraltar, driving 3,000 years of exchange.',
        sharedIngredients: ['Olive oil', 'Chickpeas', 'Lamb', 'Saffron', 'Lemon', 'Almonds', 'Olives'],
      },
      {
        cultureId: 'persian',
        strength: 'strong',
        linkType: 'empire',
        headline: 'Ottoman and Moorish empires carried Persian flavors west',
        detail: 'Persian culinary philosophy — sweet-sour balance, dried fruit in savory dishes, saffron-gilded rice — traveled west through the Ottoman Empire and Moorish Andalusia into Morocco.',
        sharedIngredients: ['Saffron', 'Dried fruits', 'Almonds', 'Cinnamon', 'Rose water', 'Lamb'],
      },
      {
        cultureId: 'west-african',
        strength: 'moderate',
        linkType: 'trade',
        headline: 'Trans-Saharan caravans ran for a millennium',
        detail: 'For over 1,000 years, trans-Saharan trade caravans connected Moroccan cities to the Mali, Songhai, and Ghana empires of West Africa.',
        sharedIngredients: ['Millet', 'Dried fish', 'Dates', 'Dried peppers', 'Cumin', 'Chickpeas'],
      },
    ],
  },
];

export function getCultureById(id: string): Culture | undefined {
  return cultures.find((c) => c.id === id);
}
