import type { MealPlan, GroceryItem } from './types';

export const sampleMealPlan: MealPlan = {
  id: 'filipino-week-1',
  name: 'Filipino Heritage Week',
  cultureId: 'filipino',
  cultureName: 'Filipino',
  weekOf: '2026-06-22',
  estimatedCost: 85,
  servings: 4,
  dietaryNotes: ['Contains pork', 'Contains shellfish', 'Contains soy'],
  homeschoolTheme: 'Island Geography & Preservation Science',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'sinangag', name: 'Sinangag (Garlic Fried Rice)', emoji: '🍳' },
      lunch: { recipeId: 'pancit', name: 'Pancit Canton', emoji: '🍜' },
      dinner: { recipeId: 'adobo', name: 'Chicken Adobo', emoji: '🍗' },
      snack: { recipeId: 'halo-halo', name: 'Fruit & Coconut Snack', emoji: '🥥' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'champorado', name: 'Champorado (Chocolate Rice Porridge)', emoji: '🫙' },
      lunch: { recipeId: 'adobo', name: 'Leftover Adobo Rice Bowl', emoji: '🍗' },
      dinner: { recipeId: 'sinigang', name: 'Sinigang na Baboy', emoji: '🍲' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'eggs-rice', name: 'Eggs & Garlic Rice', emoji: '🥚' },
      lunch: { recipeId: 'sinigang', name: 'Leftover Sinigang', emoji: '🍲' },
      dinner: { recipeId: 'kare-kare', name: 'Simplified Kare-Kare (Peanut Stew)', emoji: '🥜' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'pandesal', name: 'Pandesal with Butter & Jam', emoji: '🍞' },
      lunch: { recipeId: 'pancit', name: 'Pancit Canton', emoji: '🍜' },
      dinner: { recipeId: 'bangus', name: 'Daing na Bangus (Fried Milkfish)', emoji: '🐟' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'tapsilog', name: 'Tapsilog (Tapa + Sinangag + Itlog)', emoji: '🍳' },
      lunch: { recipeId: 'lugaw', name: 'Arroz Caldo (Ginger Rice Soup)', emoji: '🍚' },
      dinner: { recipeId: 'lechon', name: 'Family Celebration — Lechon-style Pork Belly', emoji: '🥩' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'hotsilog', name: 'Hotsilog (Hotdog + Rice + Egg)', emoji: '🌭' },
      lunch: { recipeId: 'sopas', name: 'Sopas (Filipino Creamy Macaroni Soup)', emoji: '🥣' },
      dinner: { recipeId: 'sinigang', name: 'Sinigang (Weekend Feast Version)', emoji: '🍲' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'pandesal', name: 'Pandesal & Coffee/Hot Chocolate', emoji: '☕' },
      lunch: { recipeId: 'kare-kare', name: 'Kare-Kare with Bagoong Rice', emoji: '🥜' },
      dinner: { recipeId: 'adobo', name: 'Sunday Adobo Feast with Family', emoji: '🍗' },
      snack: { recipeId: 'biko', name: 'Biko (Coconut Sticky Rice Cake)', emoji: '🍡' },
    },
  ],
};

export const sampleMexicanPlan: MealPlan = {
  id: 'mexican-week-1',
  name: 'Mexican Heritage Week',
  cultureId: 'mexican',
  cultureName: 'Mexican',
  weekOf: '2026-06-29',
  estimatedCost: 72,
  servings: 4,
  dietaryNotes: ['Vegetarian options available', 'Contains corn', 'Contains dairy'],
  homeschoolTheme: 'Ancient Civilizations & Three Sisters Agriculture',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'huevos-rancheros', name: 'Huevos Rancheros', emoji: '🍳' },
      lunch: { recipeId: 'tacos', name: 'Bean & Cheese Tacos', emoji: '🌮' },
      dinner: { recipeId: 'tamales', name: 'Chicken Tamales', emoji: '🌽' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'atole', name: 'Atole de Vainilla (Warm Corn Drink)', emoji: '☕' },
      lunch: { recipeId: 'tamales', name: 'Leftover Tamales', emoji: '🌽' },
      dinner: { recipeId: 'pozole', name: 'Pozole Rojo', emoji: '🍲' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'horchata', name: 'Horchata + Pan Dulce', emoji: '🥛' },
      lunch: { recipeId: 'sopa', name: 'Sopa de Fideo', emoji: '🍜' },
      dinner: { recipeId: 'enchiladas', name: 'Chicken Enchiladas Verdes', emoji: '🫔' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'chilaquiles', name: 'Chilaquiles Rojos', emoji: '🫔' },
      lunch: { recipeId: 'esquites', name: 'Esquites (Corn Salad)', emoji: '🌽' },
      dinner: { recipeId: 'mole', name: 'Mole Negro with Chicken', emoji: '🫙' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'horchata', name: 'Horchata Smoothie', emoji: '🥛' },
      lunch: { recipeId: 'tostadas', name: 'Tostadas with Refried Beans', emoji: '🫓' },
      dinner: { recipeId: 'birria', name: 'Birria Tacos (simplified)', emoji: '🌮' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'molletes', name: 'Molletes (Bean Toast)', emoji: '🍞' },
      lunch: { recipeId: 'caldo', name: 'Caldo de Pollo', emoji: '🍵' },
      dinner: { recipeId: 'tamales', name: 'Tamale-Making Party', emoji: '🌽' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'pan-dulce', name: 'Pan Dulce Spread', emoji: '🥐' },
      lunch: { recipeId: 'tacos', name: 'Sunday Taco Bar', emoji: '🌮' },
      dinner: { recipeId: 'mole', name: 'Mole Feast with Rice & Beans', emoji: '🫙' },
    },
  ],
};

export const groceryListFromPlan: GroceryItem[] = [
  { name: 'Chicken thighs', amount: '4', unit: 'lbs', category: 'Meat & Seafood', recipeNames: ['Chicken Adobo'] },
  { name: 'Pork ribs', amount: '2', unit: 'lbs', category: 'Meat & Seafood', recipeNames: ['Sinigang na Baboy'] },
  { name: 'Shrimp', amount: '½', unit: 'lb', category: 'Meat & Seafood', recipeNames: ['Pancit Canton'] },
  { name: 'Soy sauce', amount: '1', unit: 'bottle', category: 'Pantry', recipeNames: ['Chicken Adobo', 'Pancit Canton'] },
  { name: 'White cane vinegar', amount: '1', unit: 'bottle', category: 'Pantry', recipeNames: ['Chicken Adobo'] },
  { name: 'Fish sauce (patis)', amount: '1', unit: 'bottle', category: 'Pantry', recipeNames: ['Sinigang na Baboy', 'Pancit Canton'] },
  { name: 'Garlic', amount: '2', unit: 'heads', category: 'Produce', recipeNames: ['Chicken Adobo', 'Pancit Canton'] },
  { name: 'Bay leaves', amount: '1', unit: 'pack', category: 'Pantry', recipeNames: ['Chicken Adobo'] },
  { name: 'Tamarind paste', amount: '1', unit: 'jar', category: 'Pantry', recipeNames: ['Sinigang na Baboy'] },
  { name: 'Tomatoes', amount: '4', unit: 'medium', category: 'Produce', recipeNames: ['Sinigang na Baboy'] },
  { name: 'Onions', amount: '3', unit: 'large', category: 'Produce', recipeNames: ['Sinigang na Baboy', 'Pancit Canton'] },
  { name: 'Long green beans', amount: '1', unit: 'bunch', category: 'Produce', recipeNames: ['Sinigang na Baboy'] },
  { name: 'Eggplant', amount: '1', unit: 'medium', category: 'Produce', recipeNames: ['Sinigang na Baboy'] },
  { name: 'Baby spinach', amount: '1', unit: 'bag', category: 'Produce', recipeNames: ['Sinigang na Baboy'] },
  { name: 'Canton noodles', amount: '8', unit: 'oz', category: 'Pasta & Grains', recipeNames: ['Pancit Canton'] },
  { name: 'Cabbage', amount: '1', unit: 'small head', category: 'Produce', recipeNames: ['Pancit Canton'] },
  { name: 'Carrots', amount: '2', unit: 'medium', category: 'Produce', recipeNames: ['Pancit Canton'] },
  { name: 'Celery', amount: '1', unit: 'bunch', category: 'Produce', recipeNames: ['Pancit Canton'] },
  { name: 'Oyster sauce', amount: '1', unit: 'bottle', category: 'Pantry', recipeNames: ['Pancit Canton'] },
  { name: 'Chicken broth', amount: '2', unit: 'cartons', category: 'Pantry', recipeNames: ['Pancit Canton', 'Sinigang na Baboy'] },
  { name: 'Jasmine rice', amount: '5', unit: 'lbs', category: 'Pasta & Grains', recipeNames: ['Chicken Adobo', 'Sinigang na Baboy', 'Pancit Canton'] },
  { name: 'Neutral cooking oil', amount: '1', unit: 'bottle', category: 'Pantry', recipeNames: ['Chicken Adobo', 'Pancit Canton'] },
  { name: 'Scallions', amount: '1', unit: 'bunch', category: 'Produce', recipeNames: ['Chicken Adobo', 'Pancit Canton'] },
  { name: 'Calamansi limes (or regular limes)', amount: '4', category: 'Produce', recipeNames: ['Pancit Canton'] },
  { name: 'Chicken breast', amount: '1', unit: 'lb', category: 'Meat & Seafood', recipeNames: ['Pancit Canton'] },
];

export const sampleVietnamesePlan: MealPlan = {
  id: 'vietnamese-week-1',
  name: 'Vietnamese Heritage Week',
  cultureId: 'vietnamese',
  cultureName: 'Vietnamese',
  weekOf: '2026-06-29',
  estimatedCost: 68,
  servings: 4,
  dietaryNotes: ['Contains fish sauce', 'Gluten-free options available', 'Contains shellfish'],
  homeschoolTheme: 'Balance of Five Flavors & Mekong Delta Geography',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'banh-mi', name: 'Bánh Mì Trứng (Egg Bánh Mì)', emoji: '🥖' },
      lunch: { recipeId: 'spring-rolls', name: 'Gỏi Cuốn (Fresh Spring Rolls)', emoji: '🫔' },
      dinner: { recipeId: 'pho', name: 'Phở Bò (Beef Noodle Soup)', emoji: '🍜' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'chao', name: 'Cháo Gà (Rice Congee with Chicken)', emoji: '🍚' },
      lunch: { recipeId: 'pho', name: 'Leftover Phở', emoji: '🍜' },
      dinner: { recipeId: 'bun-cha', name: 'Bún Chả (Grilled Pork & Noodles)', emoji: '🍖' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'coffee', name: 'Cà Phê Sữa Đá & Bánh', emoji: '☕' },
      lunch: { recipeId: 'com-tam', name: 'Cơm Tấm (Broken Rice with Pork)', emoji: '🍱' },
      dinner: { recipeId: 'canh-chua', name: 'Canh Chua (Sweet & Sour Soup)', emoji: '🍲' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'xoi', name: 'Xôi Đậu Xanh (Sticky Rice with Mung Bean)', emoji: '🟢' },
      lunch: { recipeId: 'bun-bo-hue', name: 'Bún Bò Huế (Spicy Beef Noodle)', emoji: '🌶️' },
      dinner: { recipeId: 'spring-rolls', name: 'Chả Giò (Crispy Fried Spring Rolls)', emoji: '🥢' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'banh-cuon', name: 'Bánh Cuốn (Steamed Rice Rolls)', emoji: '🫔' },
      lunch: { recipeId: 'bun-cha', name: 'Bún Chả Leftovers', emoji: '🍖' },
      dinner: { recipeId: 'ca-kho-to', name: 'Cá Kho Tộ (Caramelized Fish in Clay Pot)', emoji: '🐟' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'banh-mi', name: 'Bánh Mì Thịt (Deli Meat Bánh Mì)', emoji: '🥖' },
      lunch: { recipeId: 'goi-ga', name: 'Gỏi Gà (Chicken & Cabbage Salad)', emoji: '🥗' },
      dinner: { recipeId: 'pho', name: 'Family Phở Night', emoji: '🍜' },
      snack: { recipeId: 'che', name: 'Chè Ba Màu (Three-Color Dessert)', emoji: '🍨' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'chao', name: 'Cháo Trắng & Pickles', emoji: '🍚' },
      lunch: { recipeId: 'spring-rolls', name: 'Fresh Roll Assembly Party', emoji: '🫔' },
      dinner: { recipeId: 'lau', name: 'Lẩu (Vietnamese Hot Pot)', emoji: '🫕' },
      snack: { recipeId: 'coffee', name: 'Vietnamese Iced Coffee', emoji: '☕' },
    },
  ],
};

export const samplePersianPlan: MealPlan = {
  id: 'persian-week-1',
  name: 'Persian Heritage Week',
  cultureId: 'persian',
  cultureName: 'Persian',
  weekOf: '2026-06-29',
  estimatedCost: 95,
  servings: 4,
  dietaryNotes: ['Halal', 'Nut-heavy dishes present', 'Contains lamb & chicken'],
  homeschoolTheme: 'Silk Road History & Saffron Science',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'noon-panir', name: 'Noon Panir Sabzi (Bread, Feta & Herbs)', emoji: '🧀' },
      lunch: { recipeId: 'ash-reshteh', name: 'Āsh-e Reshteh (Hearty Noodle Soup)', emoji: '🍜' },
      dinner: { recipeId: 'ghormeh-sabzi', name: 'Ghormeh Sabzi with Saffron Rice', emoji: '🌿' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'halim', name: 'Halim (Wheat & Lamb Porridge)', emoji: '🥣' },
      lunch: { recipeId: 'ghormeh-sabzi', name: 'Leftover Ghormeh Sabzi', emoji: '🌿' },
      dinner: { recipeId: 'tahdig', name: 'Tahdig with Mast-o-Khiar', emoji: '🍚' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'omelet', name: 'Kuku Sabzi (Herb Frittata)', emoji: '🥚' },
      lunch: { recipeId: 'salad-shirazi', name: 'Salad Shirazi & Lavash', emoji: '🥗' },
      dinner: { recipeId: 'fesenjan', name: 'Fesenjan (Walnut & Pomegranate Stew)', emoji: '🍇' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'bread', name: 'Sangak Bread with Jam & Walnuts', emoji: '🍞' },
      lunch: { recipeId: 'soup', name: 'Soup-e Jo (Barley Soup)', emoji: '🍵' },
      dinner: { recipeId: 'zereshk-polo', name: 'Zereshk Polo Morgh (Barberry Rice & Chicken)', emoji: '🍗' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'noon-panir', name: 'Persian Breakfast Spread', emoji: '🧀' },
      lunch: { recipeId: 'kabab-koobideh', name: 'Kabab Koobideh Wrap', emoji: '🥙' },
      dinner: { recipeId: 'ghormeh-sabzi', name: 'Friday Ghormeh Sabzi Feast', emoji: '🌿' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'halim', name: 'Halim with Cinnamon & Sugar', emoji: '🥣' },
      lunch: { recipeId: 'dizi', name: 'Dizi (Lamb & Chickpea Stew)', emoji: '🍲' },
      dinner: { recipeId: 'shishlik', name: 'Shish Kebab on the Grill', emoji: '🍢' },
      snack: { recipeId: 'faloodeh', name: 'Faloodeh (Rose Water Sorbet)', emoji: '🍧' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'omelet', name: 'Kuku Sabzi Leftover Wrap', emoji: '🥚' },
      lunch: { recipeId: 'tahdig', name: 'Sunday Tahdig & Stew', emoji: '🍚' },
      dinner: { recipeId: 'abgoosht', name: 'Abgoosht (Lamb Broth & Bread)', emoji: '🍖' },
      snack: { recipeId: 'shole-zard', name: 'Shole Zard (Saffron Rice Pudding)', emoji: '🍮' },
    },
  ],
};

export const sampleIndianPlan: MealPlan = {
  id: 'indian-week-1',
  name: 'Indian Heritage Week',
  cultureId: 'indian',
  cultureName: 'Indian',
  weekOf: '2026-06-29',
  estimatedCost: 78,
  servings: 4,
  dietaryNotes: ['Vegetarian-friendly', 'Contains dairy (ghee, paneer)', 'Gluten-free options'],
  homeschoolTheme: 'Spice Trade History & Ayurvedic Nutrition',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'idli-sambar', name: 'Idli & Sambar', emoji: '🫓' },
      lunch: { recipeId: 'dal-tadka', name: 'Dal Tadka with Roti', emoji: '🫘' },
      dinner: { recipeId: 'biryani', name: 'Chicken Biryani', emoji: '🍛' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'paratha', name: 'Aloo Paratha with Yogurt', emoji: '🫓' },
      lunch: { recipeId: 'biryani', name: 'Leftover Biryani & Raita', emoji: '🍛' },
      dinner: { recipeId: 'palak-paneer', name: 'Palak Paneer with Naan', emoji: '🥬' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'upma', name: 'Upma (Semolina Porridge)', emoji: '🥣' },
      lunch: { recipeId: 'chana-masala', name: 'Chana Masala with Rice', emoji: '🫘' },
      dinner: { recipeId: 'butter-chicken', name: 'Butter Chicken with Garlic Naan', emoji: '🍗' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'dosa', name: 'Masala Dosa with Coconut Chutney', emoji: '🫔' },
      lunch: { recipeId: 'dal-tadka', name: 'Dal & Sabzi Thali', emoji: '🍱' },
      dinner: { recipeId: 'fish-curry', name: 'Kerala Fish Curry with Rice', emoji: '🐟' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'poha', name: 'Poha (Flattened Rice Breakfast)', emoji: '🍚' },
      lunch: { recipeId: 'rajma', name: 'Rajma Chawal (Kidney Bean Curry & Rice)', emoji: '🫘' },
      dinner: { recipeId: 'biryani', name: 'Friday Biryani Feast', emoji: '🍛' },
      snack: { recipeId: 'chai', name: 'Masala Chai & Biscuits', emoji: '☕' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'paratha', name: 'Methi Paratha & Pickle', emoji: '🫓' },
      lunch: { recipeId: 'chole-bhature', name: 'Chole Bhature', emoji: '🍞' },
      dinner: { recipeId: 'rogan-josh', name: 'Rogan Josh with Basmati Rice', emoji: '🍖' },
      snack: { recipeId: 'kheer', name: 'Kheer (Rice Pudding)', emoji: '🍮' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'idli-sambar', name: 'Sunday Idli Brunch', emoji: '🫓' },
      lunch: { recipeId: 'thali', name: 'Grand Thali Spread', emoji: '🍱' },
      dinner: { recipeId: 'dal-makhani', name: 'Dal Makhani with Roti & Sabzi', emoji: '🫘' },
      snack: { recipeId: 'kheer', name: 'Saffron Kheer Dessert', emoji: '🍮' },
    },
  ],
};

export const sampleSouthernPlan: MealPlan = {
  id: 'southern-week-1',
  name: 'Southern American Heritage Week',
  cultureId: 'southern',
  cultureName: 'Southern American',
  weekOf: '2026-06-29',
  estimatedCost: 82,
  servings: 4,
  dietaryNotes: ['Contains pork', 'Contains gluten', 'Contains dairy'],
  homeschoolTheme: 'African American Culinary Heritage & Community Cooking',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'biscuits-gravy', name: 'Buttermilk Biscuits & Sawmill Gravy', emoji: '🍞' },
      lunch: { recipeId: 'collard-greens', name: 'Collard Greens & Cornbread', emoji: '🌽' },
      dinner: { recipeId: 'fried-chicken', name: 'Buttermilk Fried Chicken', emoji: '🍗' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'grits', name: 'Creamy Cheese Grits & Eggs', emoji: '🥣' },
      lunch: { recipeId: 'fried-chicken', name: 'Leftover Chicken & Potato Salad', emoji: '🍗' },
      dinner: { recipeId: 'catfish', name: 'Cornmeal-Crusted Catfish & Hush Puppies', emoji: '🐟' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'french-toast', name: 'Pecan French Toast with Cane Syrup', emoji: '🍞' },
      lunch: { recipeId: 'black-eyed-peas', name: 'Black-Eyed Peas & Rice (Hoppin\' John)', emoji: '🫘' },
      dinner: { recipeId: 'pulled-pork', name: 'Slow-Cooked Pulled Pork & Coleslaw', emoji: '🥩' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'biscuits', name: 'Drop Biscuits with Muscadine Jelly', emoji: '🍞' },
      lunch: { recipeId: 'shrimp-grits', name: 'Shrimp & Grits', emoji: '🦐' },
      dinner: { recipeId: 'gumbo', name: 'Louisiana-Style Chicken & Sausage Gumbo', emoji: '🍲' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'cornbread', name: 'Skillet Cornbread & Sorghum Syrup', emoji: '🌽' },
      lunch: { recipeId: 'soup', name: 'Okra & Tomato Soup', emoji: '🍵' },
      dinner: { recipeId: 'fried-chicken', name: 'Friday Fish Fry & Cornbread', emoji: '🐟' },
      snack: { recipeId: 'sweet-potato-pie', name: 'Sweet Potato Pie Slice', emoji: '🥧' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'grits', name: 'Country Ham & Grits', emoji: '🥣' },
      lunch: { recipeId: 'bbq', name: 'Backyard BBQ Ribs & Baked Beans', emoji: '🍖' },
      dinner: { recipeId: 'fried-chicken', name: 'Church Supper Fried Chicken Feast', emoji: '🍗' },
      snack: { recipeId: 'peach-cobbler', name: 'Peach Cobbler with Vanilla Ice Cream', emoji: '🍑' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'biscuits-gravy', name: 'Sunday Biscuits & Gravy', emoji: '🍞' },
      lunch: { recipeId: 'pot-roast', name: 'Sunday Pot Roast & Root Vegetables', emoji: '🥩' },
      dinner: { recipeId: 'gumbo', name: 'Sunday Supper Gumbo', emoji: '🍲' },
      snack: { recipeId: 'banana-pudding', name: 'Banana Pudding', emoji: '🍌' },
    },
  ],
};

export const sampleMediterraneanPlan: MealPlan = {
  id: 'mediterranean-week-1',
  name: 'Mediterranean Heritage Week',
  cultureId: 'mediterranean',
  cultureName: 'Mediterranean',
  weekOf: '2026-06-29',
  estimatedCost: 90,
  servings: 4,
  dietaryNotes: ['Pescatarian-friendly', 'Contains gluten', 'Contains dairy'],
  homeschoolTheme: 'Ancient Greece, Rome & the Olive Oil Economy',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'greek-yogurt', name: 'Greek Yogurt with Honey & Walnuts', emoji: '🍯' },
      lunch: { recipeId: 'hummus', name: 'Hummus Platter with Pita & Veggies', emoji: '🫙' },
      dinner: { recipeId: 'moussaka', name: 'Moussaka (Greek Eggplant Casserole)', emoji: '🍆' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'toast', name: 'Olive Oil Toast with Za\'atar', emoji: '🍞' },
      lunch: { recipeId: 'greek-salad', name: 'Horiatiki (Classic Greek Salad)', emoji: '🥗' },
      dinner: { recipeId: 'grilled-fish', name: 'Whole Grilled Sea Bass with Lemon', emoji: '🐟' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'shakshuka', name: 'Shakshuka (Eggs in Tomato Sauce)', emoji: '🍳' },
      lunch: { recipeId: 'falafel', name: 'Falafel Wrap with Tzatziki', emoji: '🧆' },
      dinner: { recipeId: 'lamb-chops', name: 'Grilled Lamb Chops with Tabbouleh', emoji: '🍖' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'greek-yogurt', name: 'Labneh & Olive Plate', emoji: '🧀' },
      lunch: { recipeId: 'pasta', name: 'Pasta al Pomodoro (Italian Tomato Pasta)', emoji: '🍝' },
      dinner: { recipeId: 'spanakopita', name: 'Spanakopita (Spinach & Feta Pie)', emoji: '🥬' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'toast', name: 'Pan con Tomate (Spanish Tomato Toast)', emoji: '🍅' },
      lunch: { recipeId: 'hummus', name: 'Mezze Spread with Hummus & Pita', emoji: '🫙' },
      dinner: { recipeId: 'paella', name: 'Seafood Paella', emoji: '🦐' },
      snack: { recipeId: 'baklava', name: 'Baklava & Turkish Tea', emoji: '🍯' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'crepes', name: 'Crêpes with Honey & Figs', emoji: '🫓' },
      lunch: { recipeId: 'greek-salad', name: 'Mezze Lunch Board', emoji: '🥗' },
      dinner: { recipeId: 'moussaka', name: 'Saturday Moussaka Feast', emoji: '🍆' },
      snack: { recipeId: 'loukoumades', name: 'Loukoumades (Greek Honey Donuts)', emoji: '🍩' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'shakshuka', name: 'Sunday Shakshuka Brunch', emoji: '🍳' },
      lunch: { recipeId: 'lamb-chops', name: 'Sunday Lamb & Roasted Vegetables', emoji: '🍖' },
      dinner: { recipeId: 'pasta', name: 'Pasta Night with the Family', emoji: '🍝' },
      snack: { recipeId: 'baklava', name: 'Pistachio Baklava Dessert', emoji: '🍯' },
    },
  ],
};

export function generateGroceryList(mealPlan: MealPlan): GroceryItem[] {
  return groceryListFromPlan;
}

export const sampleJapanesePlan: MealPlan = {
  id: 'japanese-week-1',
  name: 'Japanese Heritage Week',
  cultureId: 'japanese',
  cultureName: 'Japanese',
  weekOf: '2026-06-22',
  estimatedCost: 90,
  servings: 4,
  dietaryNotes: ['Contains soy', 'Contains seafood', 'Contains gluten'],
  homeschoolTheme: 'Umami Science & Japanese Food Philosophy',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'miso-soup', name: 'Miso Soup & Rice', emoji: '🍵' },
      lunch: { recipeId: 'onigiri', name: 'Onigiri Rice Balls', emoji: '🍙' },
      dinner: { recipeId: 'ramen', name: 'Chicken Shoyu Ramen', emoji: '🍜' },
      snack: { recipeId: 'edamame', name: 'Salted Edamame', emoji: '🫘' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'tamago', name: 'Tamagoyaki (Japanese Omelette) & Rice', emoji: '🥚' },
      lunch: { recipeId: 'ramen', name: 'Leftover Ramen', emoji: '🍜' },
      dinner: { recipeId: 'teriyaki', name: 'Chicken Teriyaki with Rice', emoji: '🍗' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'onigiri', name: 'Onigiri Lunchbox', emoji: '🍙' },
      lunch: { recipeId: 'miso-soup', name: 'Miso Soup with Tofu & Vegetables', emoji: '🍵' },
      dinner: { recipeId: 'gyoza', name: 'Pan-Fried Gyoza with Rice', emoji: '🥟' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'okayu', name: 'Okayu (Japanese Rice Porridge)', emoji: '🍚' },
      lunch: { recipeId: 'onigiri', name: 'Salmon Onigiri', emoji: '🍙' },
      dinner: { recipeId: 'ramen', name: 'Vegetable Ramen Bowl', emoji: '🍜' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'toast', name: 'Japanese Milk Toast with Honey', emoji: '🍞' },
      lunch: { recipeId: 'soba', name: 'Cold Soba Noodles with Dipping Sauce', emoji: '🍝' },
      dinner: { recipeId: 'katsu', name: 'Chicken Katsu with Tonkatsu Sauce', emoji: '🍱' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'pancakes', name: 'Japanese Fluffy Pancakes', emoji: '🥞' },
      lunch: { recipeId: 'onigiri', name: 'Tuna Mayo Onigiri Picnic', emoji: '🍙' },
      dinner: { recipeId: 'sukiyaki', name: 'Family Sukiyaki Hot Pot', emoji: '🍲' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'miso-soup', name: 'Traditional Japanese Breakfast — Miso, Rice & Egg', emoji: '🍵' },
      lunch: { recipeId: 'ramen', name: 'Sunday Ramen Feast', emoji: '🍜' },
      dinner: { recipeId: 'sushi', name: 'Family Hand-Roll Sushi Night', emoji: '🍣' },
      snack: { recipeId: 'mochi', name: 'Mochi Ice Cream', emoji: '🍡' },
    },
  ],
};

export const sampleKoreanPlan: MealPlan = {
  id: 'korean-week-1',
  name: 'Korean Heritage Week',
  cultureId: 'korean',
  cultureName: 'Korean',
  weekOf: '2026-06-22',
  estimatedCost: 85,
  servings: 4,
  dietaryNotes: ['Contains soy', 'Contains sesame', 'Kimchi contains fish sauce'],
  homeschoolTheme: 'Fermentation Science & Korean History',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'egg-rice', name: 'Gyeran Bap (Egg Rice Bowl)', emoji: '🥚' },
      lunch: { recipeId: 'bibimbap', name: 'Bibimbap', emoji: '🥗' },
      dinner: { recipeId: 'japchae', name: 'Japchae Glass Noodles', emoji: '🍝' },
      snack: { recipeId: 'kimchi', name: 'Kimchi & Rice Crackers', emoji: '🥬' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'congee', name: 'Juk (Korean Rice Congee)', emoji: '🍚' },
      lunch: { recipeId: 'japchae', name: 'Leftover Japchae', emoji: '🍝' },
      dinner: { recipeId: 'bulgogi', name: 'Beef Bulgogi with Banchan', emoji: '🥩' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'toast', name: 'Korean Street Toast (Egg & Cabbage)', emoji: '🍳' },
      lunch: { recipeId: 'bibimbap', name: 'Leftover Bibimbap', emoji: '🥗' },
      dinner: { recipeId: 'jjigae', name: 'Sundubu Jjigae (Soft Tofu Stew)', emoji: '🍲' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'banana-milk', name: 'Korean Banana Milk & Toast', emoji: '🍌' },
      lunch: { recipeId: 'kimbap', name: 'Kimbap (Korean Rice Rolls)', emoji: '🍱' },
      dinner: { recipeId: 'japchae', name: 'Japchae with Kimchi Banchan', emoji: '🍝' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'hobak-juk', name: 'Hobak Juk (Pumpkin Porridge)', emoji: '🎃' },
      lunch: { recipeId: 'bibimbap', name: 'Dolsot Bibimbap (Sizzling Stone Bowl)', emoji: '🥗' },
      dinner: { recipeId: 'samgyeopsal', name: 'Grilled Pork Belly (Samgyeopsal)', emoji: '🥓' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'pancake', name: 'Pajeon (Korean Scallion Pancake)', emoji: '🥞' },
      lunch: { recipeId: 'japchae', name: 'Japchae Celebration Lunch', emoji: '🍝' },
      dinner: { recipeId: 'galbi', name: 'Galbi (Korean Short Ribs)', emoji: '🍖' },
      snack: { recipeId: 'bingsu', name: 'Bingsu (Shaved Ice Dessert)', emoji: '🧊' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'doenjang', name: 'Doenjang Guk (Soybean Paste Soup) & Rice', emoji: '🍵' },
      lunch: { recipeId: 'bibimbap', name: 'Sunday Family Bibimbap', emoji: '🥗' },
      dinner: { recipeId: 'dakgalbi', name: 'Spicy Stir-Fried Chicken (Dakgalbi)', emoji: '🍗' },
      snack: { recipeId: 'tteok', name: 'Tteok (Rice Cake) Dessert', emoji: '🍡' },
    },
  ],
};

export const sampleWestAfricanPlan: MealPlan = {
  id: 'west-african-week-1',
  name: 'West African Heritage Week',
  cultureId: 'west-african',
  cultureName: 'West African',
  weekOf: '2026-06-22',
  estimatedCost: 80,
  servings: 4,
  dietaryNotes: ['Contains palm oil', 'Contains peanuts', 'Dried fish — check for allergies'],
  homeschoolTheme: 'Diaspora History & West African Culinary Roots',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'akara', name: 'Akara (Black-Eyed Pea Fritters)', emoji: '🫘' },
      lunch: { recipeId: 'jollof-rice', name: 'Jollof Rice', emoji: '🍚' },
      dinner: { recipeId: 'egusi-soup', name: 'Egusi Soup with Fufu', emoji: '🍲' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'ogi', name: 'Ogi (Corn Porridge) with Honey', emoji: '🍯' },
      lunch: { recipeId: 'jollof-rice', name: 'Leftover Jollof Rice with Fried Plantains', emoji: '🍚' },
      dinner: { recipeId: 'peanut-soup', name: 'West African Peanut Soup', emoji: '🥜' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'bread', name: 'Agege Bread with Butter & Tea', emoji: '🍞' },
      lunch: { recipeId: 'egusi-soup', name: 'Leftover Egusi Soup with Rice', emoji: '🍲' },
      dinner: { recipeId: 'jollof-rice', name: 'Party Jollof Rice (smoky pot version)', emoji: '🍚' },
      snack: { recipeId: 'plantains', name: 'Fried Sweet Plantains (Dodo)', emoji: '🍌' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'akara', name: 'Akara with Hot Pepper Sauce', emoji: '🫘' },
      lunch: { recipeId: 'moin-moin', name: 'Moin Moin (Steamed Bean Pudding)', emoji: '🟤' },
      dinner: { recipeId: 'peanut-soup', name: 'Peanut Soup with Yam Balls', emoji: '🥜' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'ogi', name: 'Pap (Ogi) with Moin Moin', emoji: '🍯' },
      lunch: { recipeId: 'jollof-rice', name: 'Jollof Rice with Grilled Chicken', emoji: '🍚' },
      dinner: { recipeId: 'egusi-soup', name: 'Egusi Soup with Pounded Yam', emoji: '🍲' },
      snack: { recipeId: 'chin-chin', name: 'Chin Chin (Fried Dough Snack)', emoji: '🍩' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'toast', name: 'Bread & Eggs with Tomato Stew', emoji: '🍳' },
      lunch: { recipeId: 'suya', name: 'Suya (Spiced Grilled Beef Skewers)', emoji: '🍢' },
      dinner: { recipeId: 'jollof-rice', name: 'Saturday Party Jollof Rice Feast', emoji: '🍚' },
      snack: { recipeId: 'plantains', name: 'Bole (Roasted Plantain) with Peanuts', emoji: '🌽' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'akara', name: 'Sunday Akara & Ogi Breakfast', emoji: '🫘' },
      lunch: { recipeId: 'egusi-soup', name: 'Sunday Egusi Feast with Assorted Meats', emoji: '🍲' },
      dinner: { recipeId: 'jollof-rice', name: 'Sunday Jollof with Fried Fish', emoji: '🍚' },
      snack: { recipeId: 'puff-puff', name: 'Puff Puff (Nigerian Doughnuts)', emoji: '🍩' },
    },
  ],
};

export const sampleEthiopianPlan: MealPlan = {
  id: 'ethiopian-week-1',
  name: 'Ethiopian Heritage Week',
  cultureId: 'ethiopian',
  cultureName: 'Ethiopian',
  weekOf: '2026-06-22',
  estimatedCost: 75,
  servings: 4,
  dietaryNotes: ['Vegan-friendly fasting dishes', 'Contains berbere (spicy)', 'Teff in injera'],
  homeschoolTheme: 'Ancient Trade Routes & Ethiopian Orthodox Fasting Traditions',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'firfir', name: 'Injera Firfir (Leftover Injera with Berbere)', emoji: '🫓' },
      lunch: { recipeId: 'misir-wat', name: 'Misir Wat with Injera', emoji: '🫘' },
      dinner: { recipeId: 'doro-wat', name: 'Doro Wat with Injera', emoji: '🍗' },
      snack: { recipeId: 'coffee', name: 'Ethiopian Coffee Ceremony', emoji: '☕' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'genfo', name: 'Genfo (Barley Porridge with Spiced Butter)', emoji: '🍵' },
      lunch: { recipeId: 'doro-wat', name: 'Leftover Doro Wat', emoji: '🍗' },
      dinner: { recipeId: 'tibs', name: 'Sautéed Lamb Tibs with Injera', emoji: '🥩' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'firfir', name: 'Shiro Firfir (Chickpea Injera Breakfast)', emoji: '🫓' },
      lunch: { recipeId: 'misir-wat', name: 'Misir Wat & Gomen (Collard Greens)', emoji: '🫘' },
      dinner: { recipeId: 'doro-wat', name: 'Doro Wat Feast Night', emoji: '🍗' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'breakfast-injera', name: 'Injera with Honey & Spiced Butter', emoji: '🍯' },
      lunch: { recipeId: 'shiro', name: 'Shiro Wat (Chickpea Stew) with Injera', emoji: '🟡' },
      dinner: { recipeId: 'misir-wat', name: 'Misir Wat & Ayib Cheese Plate', emoji: '🫘' },
      snack: { recipeId: 'popcorn', name: 'Ethiopian Popcorn (Pop Corn with Butter)', emoji: '🍿' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'genfo', name: 'Genfo with Berbere Butter', emoji: '🍵' },
      lunch: { recipeId: 'misir-wat', name: 'Fasting Plate — Misir + Gomen + Tikil Gomen', emoji: '🫘' },
      dinner: { recipeId: 'doro-wat', name: 'Friday Doro Wat Special', emoji: '🍗' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'fuul', name: 'Fuul (Fava Bean Breakfast)', emoji: '🫘' },
      lunch: { recipeId: 'kitfo', name: 'Kitfo (Ethiopian Steak Tartare) with Injera', emoji: '🥩' },
      dinner: { recipeId: 'doro-wat', name: 'Saturday Celebration Doro Wat', emoji: '🍗' },
      snack: { recipeId: 'coffee', name: 'Full Ethiopian Coffee Ceremony', emoji: '☕' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'firfir', name: 'Sunday Morning Firfir', emoji: '🫓' },
      lunch: { recipeId: 'misir-wat', name: 'Vegetarian Fasting Plate with 4 Wats', emoji: '🫘' },
      dinner: { recipeId: 'doro-wat', name: 'Sunday Feast — Full Ethiopian Spread', emoji: '🍗' },
      snack: { recipeId: 'himbasha', name: 'Himbasha (Ethiopian Celebration Bread)', emoji: '🍞' },
    },
  ],
};

export const sampleBrazilianPlan: MealPlan = {
  id: 'brazilian-week-1',
  name: 'Brazilian Heritage Week',
  cultureId: 'brazilian',
  cultureName: 'Brazilian',
  weekOf: '2026-06-22',
  estimatedCost: 88,
  servings: 4,
  dietaryNotes: ['Contains pork', 'Contains dairy (pão de queijo)', 'Gluten-free options available'],
  homeschoolTheme: 'Amazon Biodiversity & Three Cultures of Brazil',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'pao-de-queijo', name: 'Pão de Queijo with Coffee', emoji: '🧀' },
      lunch: { recipeId: 'rice-beans', name: 'Arroz e Feijão (Rice & Beans)', emoji: '🍚' },
      dinner: { recipeId: 'feijoada', name: 'Feijoada', emoji: '🫕' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'acai', name: 'Açaí Bowl with Granola & Banana', emoji: '🫐' },
      lunch: { recipeId: 'feijoada', name: 'Leftover Feijoada with Farofa', emoji: '🫕' },
      dinner: { recipeId: 'moqueca', name: 'Moqueca (Coconut Fish Stew)', emoji: '🐟' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'pao-de-queijo', name: 'Fresh Pão de Queijo (second batch)', emoji: '🧀' },
      lunch: { recipeId: 'coxinha', name: 'Coxinha (Chicken Croquettes)', emoji: '🍗' },
      dinner: { recipeId: 'feijoada', name: 'Feijoada with Collard Greens & Orange', emoji: '🫕' },
      snack: { recipeId: 'caipirinha-juice', name: 'Fresh Lime Juice (Caipirinha-style, non-alcoholic)', emoji: '🍹' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'mingau', name: 'Mingau de Aveia (Oat Porridge Brazilian Style)', emoji: '🥣' },
      lunch: { recipeId: 'rice-beans', name: 'Rice & Beans with Vinagrete Salsa', emoji: '🍚' },
      dinner: { recipeId: 'churrasco', name: 'Churrasco (Brazilian BBQ Skewers)', emoji: '🥩' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'pao-de-queijo', name: 'Pão de Queijo & Fresh Fruit', emoji: '🧀' },
      lunch: { recipeId: 'caldo', name: 'Caldo Verde (Collard Green Soup)', emoji: '🥬' },
      dinner: { recipeId: 'feijoada', name: 'Friday Feijoada with the Family', emoji: '🫕' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'tapioca', name: 'Tapioca Crepe with Cheese & Honey', emoji: '🫓' },
      lunch: { recipeId: 'feijoada', name: 'Saturday Feijoada — the National Meal', emoji: '🫕' },
      dinner: { recipeId: 'churrasco', name: 'Backyard Churrasco Night', emoji: '🥩' },
      snack: { recipeId: 'brigadeiro', name: 'Brigadeiro (Chocolate Truffles)', emoji: '🍫' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'pao-de-queijo', name: 'Pão de Queijo & Café com Leite', emoji: '🧀' },
      lunch: { recipeId: 'rice-beans', name: 'Sunday Arroz e Feijão with Farofa', emoji: '🍚' },
      dinner: { recipeId: 'feijoada', name: 'Grand Sunday Feijoada Feast', emoji: '🫕' },
      snack: { recipeId: 'pudim', name: 'Pudim de Leite (Brazilian Flan)', emoji: '🍮' },
    },
  ],
};

export const sampleMoroccanPlan: MealPlan = {
  id: 'moroccan-week-1',
  name: 'Moroccan Heritage Week',
  cultureId: 'moroccan',
  cultureName: 'Moroccan',
  weekOf: '2026-06-22',
  estimatedCost: 82,
  servings: 4,
  dietaryNotes: ['Contains lamb and chicken', 'Harissa is spicy', 'Gluten in couscous and bread'],
  homeschoolTheme: 'Spice Trade History & Moroccan Architecture',
  days: [
    {
      day: 'Monday',
      breakfast: { recipeId: 'msemen', name: 'Msemen (Moroccan Flatbread) with Honey', emoji: '🫓' },
      lunch: { recipeId: 'harira', name: 'Harira Soup with Dates', emoji: '🍵' },
      dinner: { recipeId: 'chicken-tagine', name: 'Chicken Tagine with Preserved Lemon', emoji: '🏺' },
    },
    {
      day: 'Tuesday',
      breakfast: { recipeId: 'baghrir', name: 'Baghrir (Honeycomb Pancakes) with Butter', emoji: '🥞' },
      lunch: { recipeId: 'chicken-tagine', name: 'Leftover Tagine with Couscous', emoji: '🏺' },
      dinner: { recipeId: 'couscous', name: 'Seven-Vegetable Couscous', emoji: '🍲' },
    },
    {
      day: 'Wednesday',
      breakfast: { recipeId: 'msemen', name: 'Msemen with Argan Oil & Amlou', emoji: '🫓' },
      lunch: { recipeId: 'harira', name: 'Leftover Harira', emoji: '🍵' },
      dinner: { recipeId: 'chicken-tagine', name: 'Chicken Tagine with Olives', emoji: '🏺' },
      snack: { recipeId: 'sfenj', name: 'Sfenj (Moroccan Doughnuts)', emoji: '🍩' },
    },
    {
      day: 'Thursday',
      breakfast: { recipeId: 'beghrir', name: 'Moroccan Mint Tea & Biscuits', emoji: '🍵' },
      lunch: { recipeId: 'zaalouk', name: 'Zaalouk (Eggplant & Tomato Salad) with Bread', emoji: '🍆' },
      dinner: { recipeId: 'harira', name: 'Harira & Stuffed Dates', emoji: '🍵' },
    },
    {
      day: 'Friday',
      breakfast: { recipeId: 'msemen', name: 'Msemen & Mint Tea', emoji: '🫓' },
      lunch: { recipeId: 'chicken-tagine', name: 'Friday Tagine Lunch', emoji: '🏺' },
      dinner: { recipeId: 'couscous', name: 'Friday Couscous (traditional weekly meal)', emoji: '🍲' },
    },
    {
      day: 'Saturday',
      breakfast: { recipeId: 'chebakia', name: 'Chebakia (Honey Sesame Cookies) & Coffee', emoji: '🍪' },
      lunch: { recipeId: 'harira', name: 'Harira with Lemon & Cilantro', emoji: '🍵' },
      dinner: { recipeId: 'chicken-tagine', name: 'Saturday Celebration Tagine', emoji: '🏺' },
      snack: { recipeId: 'pastilla', name: 'Bastilla (Sweet-Savory Pigeon Pie)', emoji: '🥧' },
    },
    {
      day: 'Sunday',
      breakfast: { recipeId: 'msemen', name: 'Sunday Msemen Brunch', emoji: '🫓' },
      lunch: { recipeId: 'harira', name: 'Grand Harira Soup with Bread & Dates', emoji: '🍵' },
      dinner: { recipeId: 'chicken-tagine', name: 'Sunday Family Tagine Feast', emoji: '🏺' },
      snack: { recipeId: 'kaab-el-ghzal', name: "Kaab El Ghzal (Gazelle Horn Cookies)", emoji: '🌙' },
    },
  ],
};

export const mealPlans = [
  sampleMealPlan,
  sampleMexicanPlan,
  sampleVietnamesePlan,
  samplePersianPlan,
  sampleIndianPlan,
  sampleSouthernPlan,
  sampleMediterraneanPlan,
  sampleJapanesePlan,
  sampleKoreanPlan,
  sampleWestAfricanPlan,
  sampleEthiopianPlan,
  sampleBrazilianPlan,
  sampleMoroccanPlan,
];
