import type { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: 'adobo',
    name: 'Chicken Adobo',
    cultureId: 'filipino',
    cultureName: 'Filipino',
    emoji: '🍗',
    description: 'The unofficial national dish of the Philippines — chicken braised in vinegar, soy sauce, garlic, and bay leaves until tender and deeply savory.',
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    difficulty: 'easy',
    tags: ['dinner', 'braised', 'savory', 'gluten-free-option'],
    isFeatured: true,
    ingredients: [
      { name: 'Chicken thighs', amount: '2', unit: 'lbs', notes: 'bone-in, skin-on' },
      { name: 'Soy sauce', amount: '⅓', unit: 'cup' },
      { name: 'White cane vinegar', amount: '⅓', unit: 'cup', notes: 'or apple cider vinegar' },
      { name: 'Garlic cloves', amount: '8', notes: 'smashed' },
      { name: 'Bay leaves', amount: '4' },
      { name: 'Black peppercorns', amount: '1', unit: 'tsp', notes: 'whole' },
      { name: 'Water', amount: '½', unit: 'cup' },
      { name: 'Neutral oil', amount: '2', unit: 'tbsp' },
      { name: 'Brown sugar', amount: '1', unit: 'tsp', notes: 'optional, for balance' },
    ],
    steps: [
      { step: 1, instruction: 'Combine chicken, soy sauce, vinegar, garlic, bay leaves, peppercorns, and water in a pot. Let marinate 30 minutes if time allows.', tip: 'Don\'t stir once you add vinegar — it helps the acid cook off evenly.' },
      { step: 2, instruction: 'Bring to a boil over high heat, then reduce to medium-low. Simmer uncovered for 30 minutes, turning chicken halfway.' },
      { step: 3, instruction: 'Remove chicken and reserve the braising liquid. Pat chicken dry.' },
      { step: 4, instruction: 'Heat oil in a skillet over medium-high. Sear chicken skin-side down for 3–4 minutes until golden and crispy.', tip: 'This step is optional but creates incredible texture.' },
      { step: 5, instruction: 'Pour reserved liquid back over chicken, simmer 5 more minutes until sauce reduces and coats the chicken.' },
      { step: 6, instruction: 'Serve over steamed jasmine rice. Garnish with sliced scallions.' },
    ],
    kidHelperTasks: [
      'Smash garlic cloves with the flat of a butter knife (supervised)',
      'Count out the bay leaves and peppercorns',
      'Measure and pour the vinegar and soy sauce',
      'Stir the marinade ingredients together',
      'Wash and slice scallions with a butter knife',
    ],
    nutritionNotes: 'Chicken adobo is rich in protein and the vinegar acts as a natural preservative. The garlic provides allicin, a powerful antioxidant compound. Use low-sodium soy sauce to reduce salt content.',
    nutritionFacts: { calories: 380, protein: 32, carbs: 6, fat: 24, fiber: 0 },
    culturalHistory: 'Adobo comes from the Spanish word "adobar" meaning "to marinate," but the dish predates Spanish arrival in 1565. Indigenous Filipinos already used vinegar and salt to preserve meats in the tropical heat. The Spanish simply gave it a name. Every Filipino family has their own adobo recipe — some add coconut milk (adobo sa gata), others use turmeric (adobong dilaw). It is the food that tastes like home.',
    homeschoolLesson: {
      subject: 'Science + History',
      ageRange: '6–14',
      duration: 30,
      activity: 'Explore how vinegar preserves food. Leave a piece of chicken in vinegar vs. plain water overnight and observe the difference. Discuss how preservation techniques shaped history.',
      discussion: [
        'Why did people need to preserve food before refrigerators?',
        'How does acid (vinegar) prevent bacteria from growing?',
        'Why might preservation techniques develop differently in hot vs. cold climates?',
        'How did trade routes spread ingredients like vinegar and soy sauce?',
      ],
      funFacts: [
        'The Philippines has over 7,641 islands — each with its own adobo variation!',
        'Vinegar was used as medicine in ancient times.',
        'The word "Philippines" comes from King Philip II of Spain.',
        'Adobo can last 3–4 days at room temperature in a tropical climate because of the acid.',
      ],
      vocabulary: [
        { word: 'Archipelago', definition: 'A group of many islands — the Philippines has over 7,641' },
        { word: 'Marinade', definition: 'A seasoned liquid used to flavor and tenderize food' },
        { word: 'Preservation', definition: 'Techniques used to keep food from spoiling' },
        { word: 'Colonization', definition: 'When one country takes political control of another' },
      ],
    },
    aiHint: 'Personalize this recipe with the family\'s preferred protein, spice level, and any dietary restrictions. Generate a kid-friendly story about a Filipino fishing village.',
  },
  {
    id: 'sinigang',
    name: 'Sinigang na Baboy',
    cultureId: 'filipino',
    cultureName: 'Filipino',
    emoji: '🍲',
    description: 'A comforting sour tamarind broth soup with tender pork ribs and fresh vegetables — the ultimate Filipino comfort food.',
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: 'medium',
    tags: ['dinner', 'soup', 'sour', 'comfort-food'],
    ingredients: [
      { name: 'Pork ribs or belly', amount: '2', unit: 'lbs', notes: 'cut into pieces' },
      { name: 'Tamarind paste or soup mix', amount: '3', unit: 'tbsp' },
      { name: 'Tomatoes', amount: '2', unit: 'medium', notes: 'quartered' },
      { name: 'Onion', amount: '1', unit: 'large', notes: 'quartered' },
      { name: 'Water', amount: '8', unit: 'cups' },
      { name: 'Long green beans', amount: '1', unit: 'cup', notes: 'cut in 2-inch pieces' },
      { name: 'Eggplant', amount: '1', unit: 'medium', notes: 'sliced' },
      { name: 'Taro (gabi)', amount: '2', unit: 'medium', notes: 'peeled and quartered', isCommon: false },
      { name: 'Water spinach (kangkong)', amount: '2', unit: 'cups', notes: 'or baby spinach' },
      { name: 'Fish sauce (patis)', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      { step: 1, instruction: 'Bring water to a boil. Add pork, tomatoes, and onion. Boil 10 minutes, skimming foam from the top.' },
      { step: 2, instruction: 'Reduce heat to medium-low. Add taro if using. Simmer 30 minutes until pork is nearly tender.' },
      { step: 3, instruction: 'Add tamarind paste. Stir and taste — adjust sourness to preference.' },
      { step: 4, instruction: 'Add eggplant and long beans. Cook 5 minutes.' },
      { step: 5, instruction: 'Add water spinach. Season with fish sauce and cook 2 more minutes.' },
      { step: 6, instruction: 'Serve hot with steamed rice. Offer fish sauce and chili on the side.' },
    ],
    kidHelperTasks: [
      'Wash all vegetables',
      'Break green beans into 2-inch pieces by hand',
      'Help measure the tamarind paste',
      'Skim foam from the top of the broth with a ladle',
    ],
    nutritionNotes: 'Sinigang is rich in vitamins C and K from kangkong, fiber from vegetables, and collagen from slow-cooked pork bones. Tamarind is high in tartaric acid and antioxidants.',
    nutritionFacts: { calories: 290, protein: 24, carbs: 18, fat: 14, fiber: 4 },
    culturalHistory: 'Sinigang is considered the most distinctly Filipino dish — its souring agents (tamarind, calamansi, guava, kamias) are all native to the Philippines. The dish varies by region: Tagalog versions use tamarind, Visayan versions may use guava. The sour flavor is thought to represent the Filipino character — resilient, surprising, and deeply nourishing.',
    homeschoolLesson: {
      subject: 'Geography + Biology',
      ageRange: '7–14',
      duration: 25,
      activity: 'Map the journey of tamarind from Africa to Asia to the Americas. Grow tamarind seeds in a cup and track growth over two weeks.',
      discussion: [
        'Why might a hot, tropical climate make sour flavors appealing?',
        'How do plants travel around the world?',
        'What does "souring agent" mean in cooking and chemistry?',
      ],
      funFacts: [
        'Tamarind originated in Africa and spread to Asia via ancient trade routes.',
        'The word "tamarind" comes from Arabic "tamar hindi" meaning "Indian date."',
        'Filipino regions use 6 different fruits to make sinigang sour!',
      ],
      vocabulary: [
        { word: 'Souring agent', definition: 'An acidic ingredient that makes food taste sour' },
        { word: 'Broth', definition: 'A flavorful liquid made by simmering meat, bones, or vegetables' },
        { word: 'Tropical', definition: 'Related to the warm, humid region near the equator' },
      ],
    },
  },
  {
    id: 'pancit',
    name: 'Pancit Canton',
    cultureId: 'filipino',
    cultureName: 'Filipino',
    emoji: '🍜',
    description: 'Stir-fried egg noodles with vegetables and meat — a Filipino birthday tradition symbolizing long life.',
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    difficulty: 'easy',
    tags: ['dinner', 'noodles', 'birthday', 'stir-fry'],
    ingredients: [
      { name: 'Canton noodles (egg noodles)', amount: '8', unit: 'oz' },
      { name: 'Chicken breast', amount: '1', unit: 'lb', notes: 'thinly sliced' },
      { name: 'Shrimp', amount: '½', unit: 'lb', notes: 'peeled and deveined' },
      { name: 'Garlic', amount: '4', unit: 'cloves', notes: 'minced' },
      { name: 'Onion', amount: '1', unit: 'medium', notes: 'sliced' },
      { name: 'Cabbage', amount: '2', unit: 'cups', notes: 'shredded' },
      { name: 'Carrots', amount: '1', unit: 'medium', notes: 'julienned' },
      { name: 'Celery', amount: '2', unit: 'stalks', notes: 'sliced' },
      { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'Oyster sauce', amount: '2', unit: 'tbsp' },
      { name: 'Chicken broth', amount: '1', unit: 'cup' },
    ],
    steps: [
      { step: 1, instruction: 'Soak noodles in warm water for 5 minutes until slightly softened. Drain.' },
      { step: 2, instruction: 'Heat oil in a wok over high heat. Sauté garlic and onion until fragrant, 2 minutes.' },
      { step: 3, instruction: 'Add chicken, cook 3–4 minutes. Add shrimp, cook 2 minutes until pink.' },
      { step: 4, instruction: 'Add carrots and celery, stir-fry 2 minutes. Add cabbage, cook 1 minute.' },
      { step: 5, instruction: 'Add noodles, soy sauce, oyster sauce, and broth. Toss everything together over high heat for 3–4 minutes until noodles absorb the liquid.' },
      { step: 6, instruction: 'Taste and adjust seasoning. Serve with calamansi or lemon wedges.' },
    ],
    kidHelperTasks: [
      'Help shred cabbage into thin strips',
      'Measure soy sauce and oyster sauce',
      'Peel shrimp (with supervision)',
      'Squeeze calamansi over finished dish',
    ],
    nutritionNotes: 'Pancit provides a good balance of carbohydrates from noodles, protein from chicken and shrimp, and micronutrients from the vegetables. Cabbage is high in vitamin C and K.',
    nutritionFacts: { calories: 340, protein: 28, carbs: 38, fat: 8, fiber: 3 },
    culturalHistory: 'Noodles were brought to the Philippines by Chinese traders ("Sangley") who settled in Manila\'s Binondo district (the world\'s oldest Chinatown, founded 1594). "Pancit" comes from the Hokkien "pian i sit" meaning "something conveniently cooked." Filipinos serve pancit at birthdays because long noodles symbolize a long life — never cut them before serving!',
    homeschoolLesson: {
      subject: 'Math + History',
      ageRange: '5–12',
      duration: 20,
      activity: 'Measure noodle lengths and calculate averages. Discuss the Silk Road and how noodles traveled from China to the Philippines. Chart the trade route on a map.',
      discussion: [
        'Why do you think long noodles became a symbol of long life?',
        'How did Chinese traders change Filipino food forever?',
        'What other foods can you think of that have special meaning on birthdays or holidays?',
      ],
      funFacts: [
        'Binondo in Manila is the world\'s oldest Chinatown, founded in 1594!',
        'The world\'s longest noodle ever made was 3,084 meters long.',
        'Noodles were invented in China over 4,000 years ago.',
      ],
      vocabulary: [
        { word: 'Trade route', definition: 'A path used by merchants to travel and exchange goods' },
        { word: 'Immigrant', definition: 'A person who moves to a new country to live' },
        { word: 'Symbol', definition: 'Something that represents or stands for something else' },
      ],
    },
  },
  {
    id: 'tamales',
    name: 'Chicken Tamales',
    cultureId: 'mexican',
    cultureName: 'Mexican',
    emoji: '🌽',
    description: 'Masa dough filled with tender chicken and red chile sauce, wrapped in corn husks and steamed — a communal labor of love and tradition.',
    prepTime: 90,
    cookTime: 90,
    servings: 24,
    difficulty: 'hard',
    tags: ['dinner', 'holiday', 'masa', 'steamed', 'communal'],
    isFeatured: true,
    ingredients: [
      { name: 'Masa harina', amount: '4', unit: 'cups' },
      { name: 'Chicken broth (warm)', amount: '2½', unit: 'cups' },
      { name: 'Lard or vegetable shortening', amount: '1', unit: 'cup' },
      { name: 'Baking powder', amount: '1½', unit: 'tsp' },
      { name: 'Salt', amount: '1½', unit: 'tsp' },
      { name: 'Dried corn husks', amount: '30', notes: 'soaked in warm water 1 hour' },
      { name: 'Cooked chicken', amount: '3', unit: 'cups', notes: 'shredded' },
      { name: 'Dried guajillo chiles', amount: '6', notes: 'stemmed and seeded' },
      { name: 'Dried ancho chiles', amount: '3', notes: 'stemmed and seeded' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
    ],
    steps: [
      { step: 1, instruction: 'Toast dried chiles in a dry skillet 30 seconds per side. Soak in hot water 20 minutes. Blend with garlic, cumin, and 1 cup soaking liquid into a smooth sauce.', tip: 'Don\'t skip toasting — it wakes up the chile flavor dramatically.' },
      { step: 2, instruction: 'Season shredded chicken with the red chile sauce. Set aside.' },
      { step: 3, instruction: 'Beat lard/shortening until fluffy, 5 minutes. Mix masa harina with baking powder and salt, then add warm broth gradually. Beat into lard until dough floats when a pinch is dropped in water.' },
      { step: 4, instruction: 'Spread 2 tbsp masa onto the smooth side of a soaked corn husk, leaving borders. Add 2 tbsp chicken filling in center.' },
      { step: 5, instruction: 'Fold husk sides over filling, then fold bottom up. Stand upright in a steamer basket, open end up.' },
      { step: 6, instruction: 'Steam over simmering water 75–90 minutes, adding water as needed. Tamales are done when masa pulls cleanly from husk.' },
    ],
    kidHelperTasks: [
      'Soak corn husks in the sink (supervise)',
      'Spread masa on husks with the back of a spoon',
      'Add a spoonful of filling to each tamale',
      'Fold the corn husks (with guidance)',
      'Stack tamales in the steamer pot',
    ],
    nutritionNotes: 'Tamales made with masa provide nixtamalized corn, which has significantly higher niacin and amino acid availability than regular corn. The process of nixtamalization was one of ancient Mesoamerica\'s greatest nutritional discoveries.',
    nutritionFacts: { calories: 220, protein: 10, carbs: 28, fat: 9, fiber: 2 },
    culturalHistory: 'Tamales date back to at least 8000–5000 BCE in ancient Mesoamerica. Aztec and Maya warriors carried them as portable food during battles. They were offered to gods in religious ceremonies. "Tamalada" — a tamale-making gathering — remains a central family tradition across Latin America, especially at Christmas. Making tamales is slow, communal, and full of stories.',
    homeschoolLesson: {
      subject: 'Science + Ancient History',
      ageRange: '7–14',
      duration: 40,
      activity: 'Learn about nixtamalization — the ancient process of soaking corn in lime water to release nutrients. Compare nutrition labels of regular cornmeal vs. masa harina.',
      discussion: [
        'Why was corn so important to ancient civilizations?',
        'How did nixtamalization prevent malnutrition diseases like pellagra?',
        'What does "communal cooking" teach us about how people lived together?',
        'Why is it important to preserve traditional food knowledge?',
      ],
      funFacts: [
        'Nixtamalization was discovered over 3,500 years ago — one of humanity\'s great nutritional discoveries.',
        'The Aztec word for tamale was "tamalli."',
        'NASA has considered tamales as space food because they travel so well!',
        'In the 1800s, tamale sellers in American cities helped introduce Mexican food to the US.',
      ],
      vocabulary: [
        { word: 'Nixtamalization', definition: 'Ancient process of soaking corn in alkaline lime water to improve nutrition' },
        { word: 'Masa', definition: 'Dough made from nixtamalized corn, used in tamales and tortillas' },
        { word: 'Mesoamerica', definition: 'Historical region covering southern Mexico and Central America' },
        { word: 'Communal', definition: 'Shared by or involving a group of people' },
      ],
    },
  },
  {
    id: 'mole',
    name: 'Mole Negro',
    cultureId: 'mexican',
    cultureName: 'Mexican',
    emoji: '🫙',
    description: 'The crown jewel of Mexican cuisine — a complex, dark sauce with 20+ ingredients including chocolate, dried chiles, and spices, slow-cooked for hours.',
    prepTime: 60,
    cookTime: 120,
    servings: 8,
    difficulty: 'hard',
    tags: ['dinner', 'sauce', 'complex', 'holiday', 'chocolate'],
    ingredients: [
      { name: 'Dried mulato chiles', amount: '4' },
      { name: 'Dried pasilla chiles', amount: '4' },
      { name: 'Dried ancho chiles', amount: '3' },
      { name: 'Chipotle in adobo', amount: '2' },
      { name: 'Mexican chocolate (Ibarra)', amount: '2', unit: 'oz', notes: 'chopped' },
      { name: 'Tomatoes', amount: '3', unit: 'medium', notes: 'charred' },
      { name: 'Tomatillos', amount: '3', notes: 'charred' },
      { name: 'Onion', amount: '1', unit: 'large', notes: 'charred' },
      { name: 'Garlic', amount: '6', unit: 'cloves', notes: 'charred' },
      { name: 'Sesame seeds', amount: '¼', unit: 'cup', notes: 'toasted' },
      { name: 'Pumpkin seeds (pepitas)', amount: '¼', unit: 'cup', notes: 'toasted' },
      { name: 'Raisins', amount: '¼', unit: 'cup' },
      { name: 'Cinnamon stick', amount: '1' },
      { name: 'Cumin seeds', amount: '1', unit: 'tsp' },
      { name: 'Black peppercorns', amount: '6' },
      { name: 'Chicken broth', amount: '4', unit: 'cups' },
      { name: 'Lard or oil', amount: '3', unit: 'tbsp' },
    ],
    steps: [
      { step: 1, instruction: 'Toast all dried chiles in a dry skillet until fragrant. Soak in hot water 30 minutes. Save soaking water.' },
      { step: 2, instruction: 'Char tomatoes, tomatillos, onion, and garlic directly over a flame or under a broiler until blackened in spots.' },
      { step: 3, instruction: 'Toast cinnamon, cumin, peppercorns, sesame seeds, and pepitas in a dry skillet until fragrant.' },
      { step: 4, instruction: 'Working in batches, blend all chiles, charred vegetables, toasted spices, raisins, and some broth until very smooth.' },
      { step: 5, instruction: 'Heat lard in a large pot over high heat. Pour in blended mole carefully — it will spatter. Fry the mole, stirring constantly, 5 minutes.' },
      { step: 6, instruction: 'Add remaining broth and chocolate. Simmer on low heat 45–60 minutes, stirring frequently, until mole is thick and deeply flavored. Season with salt.' },
    ],
    kidHelperTasks: [
      'Count out the dried chile peppers',
      'Help toast sesame and pumpkin seeds (supervised)',
      'Measure raisins and add to blender',
      'Stir the mole with a long wooden spoon (supervised)',
    ],
    nutritionNotes: 'Mole is nutritionally dense with minerals from seeds, antioxidants from chiles and chocolate, and healthy fats. Dark chocolate (cacao) contains flavonoids that support heart health.',
    nutritionFacts: { calories: 180, protein: 5, carbs: 22, fat: 10, fiber: 5 },
    culturalHistory: 'Mole (from Nahuatl "molli" meaning sauce) is considered the pinnacle of Mexican culinary art. Oaxaca is famous for seven distinct moles. Legend says mole negro was created by a nun at a Puebla convent who, in a panic before a bishop\'s visit, ground together everything in her pantry including chocolate. Whether true or not, the dish represents Mexican culinary creativity at its most profound.',
    homeschoolLesson: {
      subject: 'History + Chemistry',
      ageRange: '9–16',
      duration: 35,
      activity: 'Study cacao\'s journey from Mesoamerican ceremonial drink to global chocolate. Make a simple cacao-spice drink (tejate) and compare flavors with modern hot chocolate.',
      discussion: [
        'How did Europeans change cacao when they brought it home from the Americas?',
        'Why were cacao beans used as currency by the Aztecs?',
        'What is the Maillard reaction and how does it affect the flavor of toasted chiles?',
      ],
      funFacts: [
        'Aztec emperor Moctezuma reportedly drank 50 cups of cacao a day.',
        'Real mole negro can have over 30 ingredients.',
        'Making mole in Oaxaca can take 3 days of preparation.',
        'Mexico exports cacao to over 60 countries.',
      ],
      vocabulary: [
        { word: 'Nahuatl', definition: 'The language spoken by the Aztec people, still spoken by 1.7 million people in Mexico' },
        { word: 'Maillard reaction', definition: 'A chemical reaction between amino acids and sugars that creates complex flavors when food is toasted or browned' },
        { word: 'Currency', definition: 'A system of money used in a particular country or community' },
      ],
    },
  },
  {
    id: 'horchata',
    name: 'Horchata de Arroz',
    cultureId: 'mexican',
    cultureName: 'Mexican',
    emoji: '🥛',
    description: 'A sweet, creamy rice-and-cinnamon drink — cool, refreshing, and a perfect kid-friendly Mexican agua fresca.',
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    difficulty: 'easy',
    tags: ['drink', 'sweet', 'kid-friendly', 'no-cook', 'breakfast'],
    ingredients: [
      { name: 'Long-grain white rice', amount: '1', unit: 'cup', notes: 'uncooked' },
      { name: 'Water (for soaking)', amount: '2', unit: 'cups' },
      { name: 'Water (for serving)', amount: '4', unit: 'cups' },
      { name: 'Cinnamon sticks', amount: '2' },
      { name: 'Sugar', amount: '⅔', unit: 'cup' },
      { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
      { name: 'Milk or plant milk', amount: '1', unit: 'cup', notes: 'optional for creaminess' },
    ],
    steps: [
      { step: 1, instruction: 'Combine rice, cinnamon sticks, and 2 cups water. Soak at least 4 hours or overnight.' },
      { step: 2, instruction: 'Blend rice mixture (including soaking water and cinnamon) for 2 full minutes until very smooth.' },
      { step: 3, instruction: 'Strain through a fine-mesh strainer or cheesecloth into a pitcher, pressing to extract all liquid.' },
      { step: 4, instruction: 'Add remaining 4 cups water, sugar, vanilla, and milk if using. Stir until sugar dissolves.' },
      { step: 5, instruction: 'Chill in refrigerator at least 1 hour. Serve over ice with a sprinkle of cinnamon.' },
    ],
    kidHelperTasks: [
      'Measure and pour rice into bowl for soaking',
      'Add cinnamon sticks to soaking water',
      'Watch and listen to the blender (with adult operating)',
      'Stir in sugar and vanilla',
      'Sprinkle cinnamon on top of each glass',
    ],
    nutritionNotes: 'Traditional horchata is a treat best enjoyed in moderation due to sugar content. You can reduce sugar by half and add unsweetened almond milk for a lighter version rich in vitamin E.',
    nutritionFacts: { calories: 140, protein: 2, carbs: 32, fat: 1, fiber: 0 },
    culturalHistory: 'Horchata originated in Valencia, Spain — made from tiger nuts (chufa). Spanish colonizers brought it to Mexico, where rice replaced tiger nuts since it was more abundant. Today, Mexican horchata de arroz is wildly different from Spanish horchata but equally beloved. It\'s the quintessential agua fresca served at street taco stands across Mexico and Mexican-American communities worldwide.',
    homeschoolLesson: {
      subject: 'Geography + Math',
      ageRange: '5–10',
      duration: 20,
      activity: 'Trace the journey of horchata from Spain to Mexico on a world map. Practice fractions by measuring ingredients (½ cup, ⅔ cup). Taste the difference between with and without cinnamon.',
      discussion: [
        'How did colonization change the way food was made?',
        'What happens when you adapt a recipe with local ingredients?',
        'Can you think of other foods that changed when they traveled to a new country?',
      ],
      funFacts: [
        'Spanish horchata is made from tiger nuts, not rice!',
        'Horchata is now sold in grocery stores across the United States.',
        'The word "horchata" may come from the Latin "hordeata" meaning barley water.',
      ],
      vocabulary: [
        { word: 'Agua fresca', definition: 'Mexican chilled drink made from fruit, seeds, or grains blended with water and sugar' },
        { word: 'Adapt', definition: 'To change something to suit new conditions or needs' },
        { word: 'Colonization', definition: 'The process of a country taking control of another and establishing settlers there' },
      ],
    },
  },
  {
    id: 'pho',
    name: 'Beef Pho (Phở Bò)',
    cultureId: 'vietnamese',
    cultureName: 'Vietnamese',
    emoji: '🍜',
    description: 'Vietnam\'s iconic spiced beef broth soup with rice noodles, tender beef slices, and a symphony of fresh herb toppings.',
    prepTime: 30,
    cookTime: 240,
    servings: 6,
    difficulty: 'hard',
    tags: ['dinner', 'soup', 'broth', 'beef', 'weekend-project'],
    isFeatured: true,
    ingredients: [
      { name: 'Beef bones (knuckle/marrow)', amount: '3', unit: 'lbs' },
      { name: 'Beef brisket or chuck', amount: '1', unit: 'lb' },
      { name: 'Onions', amount: '2', unit: 'large', notes: 'halved and charred' },
      { name: 'Ginger', amount: '3', unit: 'inches', notes: 'halved and charred' },
      { name: 'Star anise', amount: '6', unit: 'pods' },
      { name: 'Cinnamon stick', amount: '1' },
      { name: 'Cloves', amount: '5' },
      { name: 'Coriander seeds', amount: '1', unit: 'tbsp' },
      { name: 'Fish sauce', amount: '3', unit: 'tbsp' },
      { name: 'Rock sugar', amount: '1', unit: 'oz', notes: 'or brown sugar' },
      { name: 'Flat rice noodles (banh pho)', amount: '1', unit: 'lb' },
      { name: 'Bean sprouts', amount: '2', unit: 'cups' },
      { name: 'Fresh Thai basil', amount: '1', unit: 'bunch' },
      { name: 'Lime wedges', amount: '2', unit: 'limes' },
      { name: 'Hoisin sauce and sriracha', amount: 'to serve' },
    ],
    steps: [
      { step: 1, instruction: 'Blanch bones in boiling water 10 minutes. Drain and rinse thoroughly. This removes impurities for a clear broth.', tip: 'This step is not optional — it\'s the secret to clean, beautiful pho.' },
      { step: 2, instruction: 'Char onion and ginger halves directly over a gas flame or under a broiler until blackened in spots, 5 minutes.' },
      { step: 3, instruction: 'Toast star anise, cinnamon, cloves, and coriander seeds in a dry skillet until fragrant, 2 minutes.' },
      { step: 4, instruction: 'Combine blanched bones, charred onion and ginger, toasted spices, brisket, and 12 cups water. Bring to a boil, then reduce to a gentle simmer for 3–4 hours.' },
      { step: 5, instruction: 'Remove brisket after 1.5 hours or when tender. Slice thinly against the grain. Continue simmering bones.' },
      { step: 6, instruction: 'Strain broth through a fine-mesh strainer. Season with fish sauce, rock sugar, and salt. Skim off excess fat.' },
      { step: 7, instruction: 'Cook noodles according to package. Divide into bowls. Add brisket slices. Ladle piping hot broth over everything.' },
      { step: 8, instruction: 'Serve with bean sprouts, basil, lime, hoisin, and sriracha on the side for each person to customize.' },
    ],
    kidHelperTasks: [
      'Wash and arrange fresh herb plate (basil, lime, sprouts)',
      'Squeeze lime wedges',
      'Arrange chopsticks and spoons',
      'Add toppings to their own bowl',
    ],
    nutritionNotes: 'Pho broth is rich in collagen, gelatin, and minerals from slow-simmered bones. The fresh herbs add vitamins A, C, and K. Fish sauce provides umami without needing excess salt.',
    nutritionFacts: { calories: 320, protein: 26, carbs: 38, fat: 7, fiber: 2 },
    culturalHistory: 'Pho originated in northern Vietnam (Nam Dinh province) in the early 20th century, likely influenced by French pot-au-feu and Chinese noodle soups. It migrated south with Vietnamese refugees after the country\'s partition in 1954, evolving into the herb-laden southern style. The Vietnam War brought it to America through refugee communities. Today pho represents Vietnamese national identity — its smell is the smell of home.',
    homeschoolLesson: {
      subject: 'History + Sensory Science',
      ageRange: '7–14',
      duration: 35,
      activity: 'Make a simple spice blend and identify each aroma. Map Vietnam\'s geography and discuss how the north-south partition of 1954 changed Vietnamese culture and food.',
      discussion: [
        'Why do aromas have such strong connections to memory and emotion?',
        'How did war and migration change Vietnamese cuisine?',
        'What does pho tell us about French and Chinese influence in Vietnam?',
      ],
      funFacts: [
        'Vietnamese people eat pho for breakfast, lunch, and dinner.',
        'Hanoi pho (northern style) uses fewer herbs than Saigon pho (southern style).',
        'The word "pho" may come from the French "pot-au-feu."',
        'The global pho industry is worth over $1 billion annually.',
      ],
      vocabulary: [
        { word: 'Umami', definition: 'One of the five basic tastes — savory and deeply satisfying, common in fermented foods' },
        { word: 'Refugee', definition: 'A person forced to leave their country due to war, persecution, or disaster' },
        { word: 'Partition', definition: 'The division of a country into separate, independent states' },
        { word: 'Aromatic', definition: 'Having a strong, pleasant smell — used to describe herbs and spices' },
      ],
    },
  },
  {
    id: 'spring-rolls',
    name: 'Fresh Spring Rolls (Gỏi Cuốn)',
    cultureId: 'vietnamese',
    cultureName: 'Vietnamese',
    emoji: '🌿',
    description: 'Translucent rice paper rolls filled with shrimp, herbs, vermicelli noodles, and crunchy vegetables — served with peanut dipping sauce.',
    prepTime: 30,
    cookTime: 10,
    servings: 4,
    difficulty: 'easy',
    tags: ['lunch', 'fresh', 'no-cook', 'kid-friendly', 'healthy'],
    ingredients: [
      { name: 'Rice paper wrappers (bánh tráng)', amount: '12' },
      { name: 'Cooked shrimp', amount: '½', unit: 'lb', notes: 'halved lengthwise' },
      { name: 'Rice vermicelli', amount: '4', unit: 'oz', notes: 'cooked and cooled' },
      { name: 'Butter lettuce leaves', amount: '8' },
      { name: 'Fresh mint', amount: '1', unit: 'cup' },
      { name: 'Fresh Thai basil', amount: '1', unit: 'cup' },
      { name: 'Cucumber', amount: '1', notes: 'julienned' },
      { name: 'Carrots', amount: '2', notes: 'julienned' },
      { name: 'Hoisin sauce', amount: '¼', unit: 'cup', notes: 'for dipping' },
      { name: 'Peanut butter', amount: '2', unit: 'tbsp', notes: 'for dipping sauce' },
      { name: 'Lime juice', amount: '1', unit: 'tbsp' },
      { name: 'Sriracha', amount: 'to taste' },
    ],
    steps: [
      { step: 1, instruction: 'Set up a rolling station: a shallow dish of warm water, and all fillings arranged.' },
      { step: 2, instruction: 'Dip one rice paper wrapper in warm water for 10–15 seconds until just pliable (not fully soft). Lay on a clean surface.' },
      { step: 3, instruction: 'In the bottom third of the wrapper, layer: 2 shrimp halves (cut side up), lettuce, a small bundle of noodles, herbs, cucumber, and carrot.' },
      { step: 4, instruction: 'Fold the bottom edge over the filling, then fold in the sides, then roll up tightly like a burrito.', tip: 'Work quickly — rice paper becomes sticky as it dries.' },
      { step: 5, instruction: 'Mix hoisin, peanut butter, lime juice, and sriracha for dipping sauce. Thin with a splash of water if needed.' },
      { step: 6, instruction: 'Serve rolls immediately or wrapped in damp paper towel for up to 2 hours.' },
    ],
    kidHelperTasks: [
      'Wash and pick herbs from their stems',
      'Arrange the ingredient "station" on the table',
      'Dip rice paper in water',
      'Add ingredients to the wrapper',
      'Roll their own spring roll',
    ],
    nutritionNotes: 'Fresh spring rolls are one of the most nutritious wrapped foods — high in vegetables, lean protein, and fresh herbs. Rice paper is lower in calories than flour tortillas. The mint and basil provide antioxidants.',
    nutritionFacts: { calories: 180, protein: 14, carbs: 24, fat: 3, fiber: 2 },
    culturalHistory: 'Gỏi cuốn are a distinctly southern Vietnamese creation from Ho Chi Minh City (Saigon). While the Chinese-influenced fried spring rolls (chả giò) are found across Vietnam, the fresh rice-paper version reflects the south\'s abundance of fresh produce, herbs, and seafood from the Mekong Delta. Rolling spring rolls together is a family activity that teaches patience and care.',
    homeschoolLesson: {
      subject: 'Health + Fine Motor Skills',
      ageRange: '4–12',
      duration: 30,
      activity: 'Roll spring rolls together as a family. Discuss the five food groups and identify which group each ingredient belongs to. Practice measuring and identifying fresh herbs by smell.',
      discussion: [
        'What food groups can you find in this spring roll?',
        'Why do you think Vietnamese cuisine uses so many fresh herbs?',
        'How does the Mekong Delta\'s geography make it perfect for growing fresh produce?',
      ],
      funFacts: [
        'The Mekong Delta produces 50% of Vietnam\'s food supply.',
        'Vietnam exports more black pepper than any other country.',
        'Rice paper is made by soaking and grinding rice, then spreading it thin to dry in the sun.',
      ],
      vocabulary: [
        { word: 'Delta', definition: 'A triangular area of land where a river splits into smaller streams before entering the sea' },
        { word: 'Translucent', definition: 'Allowing light to pass through, but not completely transparent' },
        { word: 'Protein', definition: 'A nutrient found in meat, fish, beans, and nuts that helps build muscle' },
      ],
    },
  },
  {
    id: 'ghormeh-sabzi',
    name: 'Ghormeh Sabzi',
    cultureId: 'persian',
    cultureName: 'Persian',
    emoji: '🌿',
    description: 'Iran\'s beloved national herb stew — deeply fragrant with fenugreek, parsley, and dried limes, slow-cooked with kidney beans and lamb.',
    prepTime: 30,
    cookTime: 150,
    servings: 6,
    difficulty: 'medium',
    tags: ['dinner', 'stew', 'herbs', 'slow-cooked', 'persian-new-year'],
    isFeatured: true,
    ingredients: [
      { name: 'Lamb shoulder or beef chuck', amount: '1.5', unit: 'lbs', notes: 'cubed' },
      { name: 'Fresh parsley', amount: '3', unit: 'bunches', notes: 'finely chopped' },
      { name: 'Fresh cilantro', amount: '1', unit: 'bunch', notes: 'finely chopped' },
      { name: 'Fresh fenugreek leaves (or dried)', amount: '1', unit: 'cup', notes: '3 tbsp if dried' },
      { name: 'Dried Persian limes (limu omani)', amount: '4', notes: 'pierced with fork' },
      { name: 'Kidney beans', amount: '1', unit: 'can', notes: '15 oz, drained' },
      { name: 'Onion', amount: '1', unit: 'large', notes: 'diced' },
      { name: 'Turmeric', amount: '1', unit: 'tsp' },
      { name: 'Dried fenugreek seeds', amount: '½', unit: 'tsp' },
      { name: 'Saffron', amount: '¼', unit: 'tsp', notes: 'dissolved in 2 tbsp hot water' },
      { name: 'Beef broth', amount: '2', unit: 'cups' },
      { name: 'Vegetable oil', amount: '4', unit: 'tbsp' },
    ],
    steps: [
      { step: 1, instruction: 'Fry chopped herbs in 2 tbsp oil over medium heat for 15–20 minutes, stirring constantly, until very dark green and fragrant. Set aside.', tip: 'This step creates the soul of the dish — don\'t rush it and don\'t burn it.' },
      { step: 2, instruction: 'In the same pot, sauté onion until golden, 8 minutes. Add meat and brown on all sides.' },
      { step: 3, instruction: 'Add turmeric, fenugreek seeds. Cook 2 minutes. Add broth and bring to a boil.' },
      { step: 4, instruction: 'Add fried herbs, dried limes, and kidney beans. Reduce heat to very low.' },
      { step: 5, instruction: 'Simmer covered for 2–2.5 hours until meat is fall-apart tender and stew is very dark.', tip: 'The longer it cooks, the deeper the flavor. Persian cooks say 3 hours is better.' },
      { step: 6, instruction: 'Add saffron water in last 15 minutes. Adjust salt and lime flavor. Serve over Persian rice (tahdig).' },
    ],
    kidHelperTasks: [
      'Wash and pick herbs from stems',
      'Open and drain the kidney beans',
      'Pierce dried limes with a fork',
      'Stir the herbs while they fry (supervised)',
    ],
    nutritionNotes: 'Ghormeh sabzi is nutritionally outstanding — high in plant-based iron from dark leafy herbs, protein from legumes and meat, and vitamin C (which helps absorb iron). The dried limes are rich in vitamin C.',
    nutritionFacts: { calories: 310, protein: 28, carbs: 18, fat: 14, fiber: 7 },
    culturalHistory: 'Ghormeh sabzi is one of Iran\'s oldest dishes, dating back 2,000+ years. "Ghormeh" means "fried herbs" and "sabzi" means "greens" — its essence is simple but profound. It is the dish every Iranian mother makes, the food of Nowruz (Persian New Year), and the dish that homesick Iranians crave most. The smell of herbs frying in oil is the smell of Iran.',
    homeschoolLesson: {
      subject: 'Science + World Cultures',
      ageRange: '8–14',
      duration: 30,
      activity: 'Explore iron absorption: pair iron-rich foods with vitamin C sources and discuss why. Map the ancient Persian Empire on a globe and trace the Silk Road trade routes.',
      discussion: [
        'Why is iron important for the body, especially for children?',
        'How did the Persian Empire spread food and culture across the world?',
        'What makes fenugreek leaves taste so unique?',
        'Why is Nowruz (Persian New Year) celebrated with particular foods?',
      ],
      funFacts: [
        'The Persian Empire was the largest empire in history at its peak in 480 BCE, stretching from Egypt to India.',
        'Saffron is worth more than gold by weight — Iran produces 90% of the world\'s supply.',
        'Persian New Year (Nowruz) is celebrated by 300 million people across many countries.',
        'Dried Persian limes are created by boiling fresh limes in salt water, then drying them in the sun.',
      ],
      vocabulary: [
        { word: 'Nowruz', definition: 'Persian New Year, celebrated on the spring equinox — one of the world\'s oldest celebrations' },
        { word: 'Silk Road', definition: 'Ancient network of trade routes connecting China to the Mediterranean' },
        { word: 'Saffron', definition: 'The world\'s most expensive spice — made from the dried stigmas of crocus flowers' },
        { word: 'Legume', definition: 'A plant family including beans, lentils, and peas — high in protein and fiber' },
      ],
    },
  },
  {
    id: 'biryani',
    name: 'Chicken Biryani',
    cultureId: 'indian',
    cultureName: 'Indian',
    emoji: '🍛',
    description: 'India\'s grandest rice dish — fragrant basmati layered with spiced chicken, saffron, fried onions, and fresh herbs in a sealed pot.',
    prepTime: 45,
    cookTime: 60,
    servings: 6,
    difficulty: 'hard',
    tags: ['dinner', 'rice', 'celebration', 'spiced', 'layered'],
    isFeatured: true,
    ingredients: [
      { name: 'Basmati rice', amount: '2', unit: 'cups' },
      { name: 'Chicken pieces', amount: '2', unit: 'lbs' },
      { name: 'Yogurt', amount: '1', unit: 'cup', notes: 'full-fat' },
      { name: 'Onions', amount: '3', unit: 'large', notes: '2 sliced thin for frying, 1 diced' },
      { name: 'Ginger-garlic paste', amount: '2', unit: 'tbsp' },
      { name: 'Garam masala', amount: '2', unit: 'tsp' },
      { name: 'Cumin seeds', amount: '1', unit: 'tsp' },
      { name: 'Bay leaves', amount: '3' },
      { name: 'Green cardamom pods', amount: '6' },
      { name: 'Saffron strands', amount: '¼', unit: 'tsp', notes: 'soaked in 3 tbsp warm milk' },
      { name: 'Fresh mint leaves', amount: '½', unit: 'cup' },
      { name: 'Fresh cilantro', amount: '½', unit: 'cup' },
      { name: 'Ghee or oil', amount: '4', unit: 'tbsp' },
      { name: 'Whole cloves and star anise', amount: '4', unit: 'each' },
    ],
    steps: [
      { step: 1, instruction: 'Marinate chicken in yogurt, ginger-garlic paste, garam masala, chili powder, and salt for at least 2 hours.', tip: 'Overnight marination is ideal for maximum flavor penetration.' },
      { step: 2, instruction: 'Deep-fry sliced onions in oil until golden brown and crispy. Drain on paper towels — they will crisp up more as they cool.' },
      { step: 3, instruction: 'Parboil basmati rice with whole spices (bay leaves, cardamom, cloves, star anise) until 70% cooked — al dente. Drain.' },
      { step: 4, instruction: 'Cook marinated chicken in a heavy pot with diced onion until nearly done, 20 minutes.' },
      { step: 5, instruction: 'Layer: chicken at bottom, then rice, then mint and cilantro, then fried onions, then saffron milk. Repeat layers.' },
      { step: 6, instruction: 'Seal pot with foil then the lid. Cook on low heat (dum) for 25–30 minutes. The steam inside finishes cooking everything.', tip: 'This "dum" technique is the secret of biryani — never open the lid during cooking.' },
      { step: 7, instruction: 'Open at the table for the full aromatic effect. Mix gently from the sides. Serve with raita (yogurt sauce).' },
    ],
    kidHelperTasks: [
      'Wash and soak basmati rice for 30 minutes',
      'Pick mint and cilantro leaves',
      'Measure spices into small bowls',
      'Layer rice and herbs (supervised)',
    ],
    nutritionNotes: 'Biryani provides complete protein from chicken, complex carbohydrates from basmati rice, and anti-inflammatory compounds from turmeric, garam masala, and saffron. Yogurt adds probiotics.',
    nutritionFacts: { calories: 450, protein: 35, carbs: 48, fat: 14, fiber: 2 },
    culturalHistory: 'Biryani\'s origin is debated — some trace it to Persia via Mughal emperors, others claim it developed independently in south India. The word may come from Persian "birinj" (rice) or "biryān" (to fry before cooking). Mughal Emperor Shah Jahan\'s royal kitchens reportedly employed 800+ cooks. Today, India has over 50 regional biryani styles — Hyderabadi, Lucknowi, Kolkata, Dindigul — each fiercely loved.',
    homeschoolLesson: {
      subject: 'History + Chemistry',
      ageRange: '9–15',
      duration: 35,
      activity: 'Examine how the Mughal Empire blended Persian and Indian cultures. Conduct a spice identification experiment — blindfolded, identify cardamom, cloves, cinnamon, and star anise by smell.',
      discussion: [
        'What is the "Mughal Empire" and how did it influence Indian culture?',
        'How can smell trigger memories — and why is that scientifically?',
        'Why do you think India produces more spice varieties than any other country?',
      ],
      funFacts: [
        'The Mughal Empire ruled India for over 300 years (1526–1857) and created iconic monuments like the Taj Mahal.',
        'India produces 70% of the world\'s spices.',
        'Saffron requires 75,000 crocus flowers to produce just one pound.',
        'There are over 50 distinct regional biryani styles across India.',
      ],
      vocabulary: [
        { word: 'Dum', definition: 'Persian cooking technique of slow-cooking food in a sealed vessel using steam pressure' },
        { word: 'Mughal', definition: 'Muslim dynasty that ruled most of India from 1526 to 1857, leaving a lasting cultural legacy' },
        { word: 'Basmati', definition: 'Long-grain aromatic rice from the foothills of the Himalayas, known for its fragrance' },
        { word: 'Marinate', definition: 'To soak food in a seasoned liquid before cooking to add flavor and tenderize' },
      ],
    },
  },
  {
    id: 'fried-chicken',
    name: 'Buttermilk Fried Chicken',
    cultureId: 'southern',
    cultureName: 'Southern American',
    emoji: '🍗',
    description: 'Crispy, juicy fried chicken soaked in seasoned buttermilk and coated in a perfectly spiced crust — the crown jewel of Southern cooking.',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: 'medium',
    tags: ['dinner', 'fried', 'sunday-supper', 'crispy', 'comfort-food'],
    isFeatured: true,
    ingredients: [
      { name: 'Whole chicken', amount: '1', notes: 'cut into 8 pieces, or 4 lbs pieces' },
      { name: 'Buttermilk', amount: '2', unit: 'cups' },
      { name: 'Hot sauce', amount: '1', unit: 'tbsp', notes: 'added to buttermilk' },
      { name: 'All-purpose flour', amount: '2', unit: 'cups' },
      { name: 'Cornstarch', amount: '¼', unit: 'cup', notes: 'for extra crunch' },
      { name: 'Garlic powder', amount: '2', unit: 'tsp' },
      { name: 'Onion powder', amount: '1', unit: 'tsp' },
      { name: 'Smoked paprika', amount: '2', unit: 'tsp' },
      { name: 'Cayenne pepper', amount: '½', unit: 'tsp' },
      { name: 'Black pepper', amount: '1', unit: 'tsp' },
      { name: 'Salt', amount: '2', unit: 'tsp' },
      { name: 'Vegetable oil', amount: '4', unit: 'cups', notes: 'for frying' },
    ],
    steps: [
      { step: 1, instruction: 'Submerge chicken in buttermilk + hot sauce. Refrigerate at least 4 hours or overnight.', tip: 'The acid in buttermilk tenderizes the chicken — longer is always better.' },
      { step: 2, instruction: 'Whisk together flour, cornstarch, and all spices in a shallow dish.' },
      { step: 3, instruction: 'Remove chicken from buttermilk (don\'t shake off excess). Dredge in seasoned flour, pressing firmly to adhere. Let rest on a rack 15 minutes.' },
      { step: 4, instruction: 'Heat oil in a cast-iron skillet or Dutch oven to 325°F. Use a thermometer.', tip: 'Low and slow frying keeps chicken juicy inside while achieving a golden crust.' },
      { step: 5, instruction: 'Fry chicken in batches without crowding, 8–12 minutes per side for bone-in pieces, until golden brown and internal temp reaches 165°F.' },
      { step: 6, instruction: 'Drain on a wire rack (never paper towels — the steam makes crust soggy). Rest 5 minutes before serving.' },
    ],
    kidHelperTasks: [
      'Mix the spice blend for the flour coating',
      'Press chicken into flour coating',
      'Watch the temperature thermometer (safety only, no hot oil contact)',
      'Set the table with napkins — it\'s gonna get messy!',
    ],
    nutritionNotes: 'Fried chicken is a celebratory food best enjoyed occasionally. Dark meat provides more iron and zinc than white meat. The skin contains most of the fat. Removing skin significantly reduces calorie content.',
    nutritionFacts: { calories: 520, protein: 38, carbs: 32, fat: 26, fiber: 1 },
    culturalHistory: 'Fried chicken\'s roots in America are West African — enslaved people from West Africa brought the technique and seasoning traditions that defined Southern cooking. Scottish immigrants also had a tradition of frying chicken, but the spice and seasoning came from African hands. For generations, fried chicken was Sunday supper after church, a dish of community and celebration. It\'s also a dish with a painful history of racial stereotype that the food world is actively reckoning with.',
    homeschoolLesson: {
      subject: 'History + Science',
      ageRange: '9–16',
      duration: 35,
      activity: 'Explore the real history of Southern food and African American culinary contributions. Conduct a science experiment: fry one piece with and without the resting step to see how it affects the crust.',
      discussion: [
        'Why is it important to know who really created the dishes we love?',
        'What is the Maillard reaction and how does it make fried food golden?',
        'How do you think it feels when your cultural contributions are erased from history?',
        'What chefs today are working to reclaim Black Southern food heritage?',
      ],
      funFacts: [
        'Cast-iron skillets were the original "non-stick" pans — still used by Southern cooks today.',
        'The Maillard reaction happens at 280–330°F and creates hundreds of new flavor compounds.',
        'Chef Edna Lewis was called "the grande dame of Southern cooking" and helped define American food.',
        'The buttermilk soak was originally used to tenderize older, tougher chickens.',
      ],
      vocabulary: [
        { word: 'Maillard reaction', definition: 'Chemical browning reaction between amino acids and sugars that creates complex flavors in cooked foods' },
        { word: 'Dredge', definition: 'To coat food in flour or breadcrumbs before cooking' },
        { word: 'Heritage', definition: 'Values, traditions, and culture passed down through generations' },
        { word: 'Reckoning', definition: 'A time when society takes responsibility for past wrongs and works toward justice' },
      ],
    },
  },
  {
    id: 'hummus',
    name: 'Classic Hummus',
    cultureId: 'mediterranean',
    cultureName: 'Mediterranean',
    emoji: '🫘',
    description: 'Silky, rich chickpea and tahini dip — the beloved spread of the Mediterranean world, made from the simplest ingredients.',
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    difficulty: 'easy',
    tags: ['appetizer', 'dip', 'no-cook', 'vegan', 'kid-friendly'],
    isFeatured: true,
    ingredients: [
      { name: 'Cooked chickpeas', amount: '2', unit: 'cans (30 oz)', notes: 'or 3 cups cooked from dried, reserve liquid' },
      { name: 'Tahini (sesame paste)', amount: '⅓', unit: 'cup', notes: 'well-stirred' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
      { name: 'Lemon juice', amount: '¼', unit: 'cup', notes: 'fresh squeezed' },
      { name: 'Ice water', amount: '3–5', unit: 'tbsp', notes: 'for smooth texture' },
      { name: 'Cumin', amount: '½', unit: 'tsp' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
      { name: 'Olive oil', amount: '3', unit: 'tbsp', notes: 'for drizzling' },
      { name: 'Smoked paprika', amount: '½', unit: 'tsp', notes: 'for garnish' },
      { name: 'Fresh parsley', amount: '2', unit: 'tbsp', notes: 'for garnish' },
    ],
    steps: [
      { step: 1, instruction: 'If using canned chickpeas, peel off the skins for ultra-smooth hummus — just pinch each chickpea and the skin slides off. Reserve 2 tbsp chickpeas for garnish.', tip: 'Peeling is optional but makes a remarkable difference in texture.' },
      { step: 2, instruction: 'Process garlic and salt in food processor until minced.' },
      { step: 3, instruction: 'Add tahini and lemon juice. Process 2 minutes — the mixture will thicken and turn lighter.' },
      { step: 4, instruction: 'Add chickpeas and cumin. Process 3–4 minutes, adding ice water tablespoon by tablespoon, until very smooth and creamy.' },
      { step: 5, instruction: 'Taste and adjust: more lemon for brightness, more tahini for richness, salt as needed.' },
      { step: 6, instruction: 'Spread in a wide bowl, making a well in the center. Drizzle with olive oil, sprinkle paprika, add parsley and reserved chickpeas.' },
    ],
    kidHelperTasks: [
      'Drain and rinse chickpeas',
      'Squeeze lemons for fresh juice',
      'Add ingredients to the food processor',
      'Decorate the finished hummus with paprika and parsley',
      'Dip and taste test throughout!',
    ],
    nutritionNotes: 'Hummus is a nutritional powerhouse: protein and fiber from chickpeas, calcium from tahini, heart-healthy fats from olive oil, and vitamin C from lemon. It\'s one of the best plant-based protein sources.',
    nutritionFacts: { calories: 160, protein: 6, carbs: 18, fat: 8, fiber: 4 },
    culturalHistory: 'Hummus (Arabic for "chickpeas") has been eaten across the Middle East for centuries. Its earliest written recipe appears in a 13th-century Egyptian cookbook. Today, hummus is simultaneously claimed by Lebanon, Israel, Palestine, Greece, and Turkey — making it both a delicious food and a complicated political flashpoint. Its global popularity has transformed it from regional staple to international grocery store staple.',
    homeschoolLesson: {
      subject: 'Social Studies + Nutrition',
      ageRange: '5–14',
      duration: 25,
      activity: 'Map the countries that claim hummus as their national food. Discuss cultural ownership and food politics. Calculate the protein content of hummus vs. other dips. Make hummus and compare texture with and without tahini.',
      discussion: [
        'Can food belong to more than one culture at once?',
        'Why do people sometimes argue about where food "comes from"?',
        'What is tahini and what country does sesame come from originally?',
        'Why are legumes (beans and chickpeas) considered a "superfood"?',
      ],
      funFacts: [
        'Chickpeas have been grown in the Middle East for at least 10,000 years.',
        'The world\'s largest plate of hummus weighed 10,452 kg and was made in Lebanon in 2010.',
        'Sesame seeds were one of the first plants cultivated for oil — 5,500 years ago.',
        'Tahini is simply ground sesame seeds — you can make it at home in a food processor.',
      ],
      vocabulary: [
        { word: 'Legume', definition: 'A family of plants including beans, chickpeas, and lentils — excellent protein sources' },
        { word: 'Cultural heritage', definition: 'Traditions, practices, and creations passed down through generations within a culture' },
        { word: 'Tahini', definition: 'A paste made from ground sesame seeds, used throughout Middle Eastern cooking' },
        { word: 'Mediterranean', definition: 'Relating to the Mediterranean Sea and the lands surrounding it' },
      ],
    },
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}

export function getRecipesByCulture(cultureId: string): Recipe[] {
  return recipes.filter((r) => r.cultureId === cultureId);
}

export function getFeaturedRecipes(): Recipe[] {
  return recipes.filter((r) => r.isFeatured);
}
