import type { Recipe } from './types';

export const adoboRecipe: Recipe = {
  id: 'adobo', name: 'Chicken Adobo', cultureId: 'filipino', cultureName: 'Filipino',
  emoji: '🍗', isFeatured: true, difficulty: 'easy', prepTime: 10, cookTime: 45, servings: 4,
  description: 'The unofficial national dish of the Philippines — braised in soy sauce, vinegar, and garlic.',
  tags: ['chicken', 'braised', 'savory', 'one-pot'],
  ingredients: [
    { name: 'Chicken thighs', amount: '2', unit: 'lbs' },
    { name: 'Soy sauce', amount: '1/3', unit: 'cup' },
    { name: 'White vinegar', amount: '1/3', unit: 'cup' },
    { name: 'Garlic cloves', amount: '6', notes: 'smashed' },
    { name: 'Bay leaves', amount: '3' },
    { name: 'Black peppercorns', amount: '1', unit: 'tsp' },
    { name: 'Sugar', amount: '1', unit: 'tsp' },
    { name: 'Oil', amount: '1', unit: 'tbsp' },
  ],
  steps: [
    { step: 1, instruction: 'Combine soy sauce, vinegar, garlic, bay leaves, and peppercorns in a bowl. Add chicken and marinate 30 min.', tip: 'Longer marinating = deeper flavor' },
    { step: 2, instruction: 'Heat oil in a large pan over medium-high. Brown chicken 3 min per side, remove.' },
    { step: 3, instruction: 'Pour marinade into pan, bring to boil. Return chicken, cover and simmer 30 min.' },
    { step: 4, instruction: 'Uncover, add sugar, increase heat. Reduce sauce until glossy, 5–8 min.' },
    { step: 5, instruction: 'Serve over jasmine rice with the sauce drizzled on top.' },
  ],
  kidHelperTasks: ['Measure soy sauce and vinegar', 'Smash garlic with the back of a spoon', 'Stir the marinade'],
  nutritionNotes: 'High protein, moderate sodium. Use low-sodium soy sauce to reduce salt.',
  nutritionFacts: { calories: 380, protein: 32, carbs: 8, fat: 22, fiber: 0 },
  culturalHistory: 'Adobo predates Spanish colonization — Filipinos preserved meat in vinegar and salt long before Spain arrived in 1565. The Spanish gave it its current name. Every Filipino family has their own version.',
  aiHint: 'The vinegar-soy balance is what makes adobo unique; do not skip the reduction step.',
  homeschoolLesson: {
    subject: 'Science: Food Preservation', ageRange: '6-12', duration: 30,
    activity: 'Discuss how vinegar preserves food before refrigerators existed. Test pH of vinegar vs water with litmus paper.',
    discussion: ['Why did Filipinos use vinegar before refrigerators?', 'What other foods use vinegar to preserve?', 'How does salt preserve food?'],
    funFacts: ['Adobo can last 5 days at room temp thanks to vinegar', 'Every Filipino province has its own adobo variation', 'Spain named it but didn\'t invent it'],
    vocabulary: [{ word: 'Marinate', definition: 'Soaking food in seasoned liquid before cooking' }, { word: 'Preservation', definition: 'Keeping food from spoiling' }, { word: 'Colonization', definition: 'When one country takes control of another' }],
  },
};

export const sinigangRecipe: Recipe = {
  id: 'sinigang', name: 'Pork Sinigang', cultureId: 'filipino', cultureName: 'Filipino',
  emoji: '🍲', isFeatured: false, difficulty: 'medium', prepTime: 15, cookTime: 60, servings: 4,
  description: 'Sour tamarind broth soup with tender pork ribs and fresh vegetables.',
  tags: ['soup', 'pork', 'sour', 'tamarind'],
  ingredients: [
    { name: 'Pork ribs', amount: '2', unit: 'lbs' },
    { name: 'Tamarind paste', amount: '3', unit: 'tbsp' },
    { name: 'Tomatoes', amount: '3', notes: 'quartered' },
    { name: 'Onion', amount: '1', notes: 'quartered' },
    { name: 'Fish sauce', amount: '2', unit: 'tbsp' },
    { name: 'Bok choy', amount: '1', unit: 'bunch' },
    { name: 'Long beans', amount: '1', unit: 'cup', notes: 'cut into 2-inch pieces' },
    { name: 'Water', amount: '8', unit: 'cups' },
  ],
  steps: [
    { step: 1, instruction: 'Boil ribs in water with onion and tomatoes for 45 min, skimming foam.' },
    { step: 2, instruction: 'Add tamarind paste and fish sauce. Taste and adjust sourness.' },
    { step: 3, instruction: 'Add long beans, cook 5 min.' },
    { step: 4, instruction: 'Add bok choy, cook 2 min. Serve with rice.' },
  ],
  kidHelperTasks: ['Wash vegetables', 'Cut bok choy with child-safe scissors', 'Taste the broth and describe it'],
  nutritionNotes: 'Rich in collagen from bones, vitamin C from tamarind and vegetables.',
  nutritionFacts: { calories: 420, protein: 28, carbs: 12, fat: 28, fiber: 3 },
  culturalHistory: 'Sinigang is comfort food across the Philippines. The sourness from tamarind reflects the Filipino love of sour flavors (asim). It\'s one of the most searched Filipino recipes worldwide.',
  aiHint: 'Use fresh tamarind pods simmered and strained for the most authentic sour flavor.',
  homeschoolLesson: {
    subject: 'Geography: Philippine Archipelago', ageRange: '6-12', duration: 30,
    activity: 'Find the Philippines on a map. Count its 7,600+ islands. Draw your own island and name it.',
    discussion: ['What is an archipelago?', 'How does living on islands affect what people eat?', 'What other island nations can you find?'],
    funFacts: ['Philippines has 7,641 islands', 'Tamarind trees can live 200+ years', 'Sinigang means "to cook in sour broth"'],
    vocabulary: [{ word: 'Archipelago', definition: 'A group of islands' }, { word: 'Tamarind', definition: 'A tropical fruit pod with sour pulp' }, { word: 'Broth', definition: 'Liquid made by simmering meat or vegetables' }],
  },
};

export const tamalesRecipe: Recipe = {
  id: 'tamales', name: 'Chicken Tamales', cultureId: 'mexican', cultureName: 'Mexican',
  emoji: '🫔', isFeatured: true, difficulty: 'hard', prepTime: 60, cookTime: 90, servings: 12,
  description: 'Masa dough filled with spiced chicken, wrapped in corn husks and steamed.',
  tags: ['masa', 'steamed', 'corn husks', 'holiday'],
  ingredients: [
    { name: 'Masa harina', amount: '4', unit: 'cups' },
    { name: 'Chicken broth', amount: '2.5', unit: 'cups', notes: 'warm' },
    { name: 'Lard or shortening', amount: '1', unit: 'cup' },
    { name: 'Cooked shredded chicken', amount: '3', unit: 'cups' },
    { name: 'Red chile sauce', amount: '1', unit: 'cup' },
    { name: 'Dried corn husks', amount: '24', notes: 'soaked 30 min' },
    { name: 'Baking powder', amount: '1', unit: 'tsp' },
    { name: 'Salt', amount: '1.5', unit: 'tsp' },
  ],
  steps: [
    { step: 1, instruction: 'Beat lard until fluffy. Mix masa harina, baking powder, and salt. Combine with broth and lard into soft dough.' },
    { step: 2, instruction: 'Mix shredded chicken with red chile sauce.' },
    { step: 3, instruction: 'Spread 2 tbsp masa on a soaked corn husk. Add 1 tbsp filling. Fold and tie closed.' },
    { step: 4, instruction: 'Stand tamales upright in a steamer. Steam 75–90 min until masa pulls away from husk.', tip: 'Keep water level up and don\'t peek for first hour' },
  ],
  kidHelperTasks: ['Spread masa on husks', 'Add filling', 'Help fold the tamales', 'Stack tamales in the pot'],
  nutritionNotes: 'Corn masa provides complex carbs. High calorie — a satisfying main dish.',
  nutritionFacts: { calories: 280, protein: 14, carbs: 35, fat: 10, fiber: 3 },
  culturalHistory: 'Tamales are 8,000+ years old, made by the Aztec, Maya, and Olmec civilizations. They were portable food for warriors and travelers. Making tamales is a community event called a tamalada.',
  aiHint: 'The masa is ready when a small ball floats in a glass of water.',
  homeschoolLesson: {
    subject: 'History: Aztec Civilization', ageRange: '6-12', duration: 45,
    activity: 'Research what the Aztecs ate. Compare their diet to modern Mexican food. Draw an Aztec market.',
    discussion: ['Why were tamales perfect food for travelers?', 'What crops did the Aztecs grow?', 'How is a tamalada like a community event today?'],
    funFacts: ['Aztec warriors carried tamales on long journeys', 'Tamales appear in 8000-year-old Mayan texts', 'Over 500 tamale varieties exist in Mexico'],
    vocabulary: [{ word: 'Masa', definition: 'Dough made from nixtamalized corn' }, { word: 'Tamalada', definition: 'A tamale-making party' }, { word: 'Nixtamalization', definition: 'Soaking corn in lime water to improve nutrition' }],
  },
};

export const moleRecipe: Recipe = {
  id: 'mole', name: 'Mole Negro', cultureId: 'mexican', cultureName: 'Mexican',
  emoji: '🍫', isFeatured: false, difficulty: 'hard', prepTime: 30, cookTime: 120, servings: 6,
  description: 'Complex Oaxacan sauce with 20+ ingredients including dark chocolate and dried chilies.',
  tags: ['sauce', 'chocolate', 'chilies', 'Oaxacan'],
  ingredients: [
    { name: 'Dried ancho chilies', amount: '4', notes: 'seeded' },
    { name: 'Dried mulato chilies', amount: '3', notes: 'seeded' },
    { name: 'Dark chocolate', amount: '2', unit: 'oz', notes: '70% cacao' },
    { name: 'Tomatoes', amount: '3', notes: 'roasted' },
    { name: 'Onion', amount: '1', notes: 'charred' },
    { name: 'Garlic', amount: '6', unit: 'cloves', notes: 'roasted' },
    { name: 'Sesame seeds', amount: '2', unit: 'tbsp', notes: 'toasted' },
    { name: 'Chicken broth', amount: '3', unit: 'cups' },
    { name: 'Cumin', amount: '1', unit: 'tsp' },
    { name: 'Cinnamon', amount: '1/2', unit: 'tsp' },
  ],
  steps: [
    { step: 1, instruction: 'Toast dried chilies in dry pan 30 seconds per side. Soak in hot water 20 min.' },
    { step: 2, instruction: 'Blend soaked chilies, roasted tomatoes, onion, garlic, and spices.' },
    { step: 3, instruction: 'Fry blended mixture in oil, stirring constantly for 10 min.' },
    { step: 4, instruction: 'Add broth gradually, simmer 45 min. Add chocolate and sesame seeds.' },
    { step: 5, instruction: 'Blend until very smooth. Adjust salt. Serve over turkey or chicken.' },
  ],
  kidHelperTasks: ['Count the ingredients', 'Toast sesame seeds (with help)', 'Stir the sauce'],
  nutritionNotes: 'Rich in antioxidants from chilies and dark chocolate. High flavor, moderate calories.',
  nutritionFacts: { calories: 180, protein: 5, carbs: 18, fat: 11, fiber: 4 },
  culturalHistory: 'Mole negro is from Oaxaca, Mexico\'s culinary capital. Legend says nuns created it for a visiting archbishop, combining indigenous and Spanish ingredients. Some families keep their mole recipe secret for generations.',
  aiHint: 'Char the onion and garlic directly over a flame for authentic smoky depth.',
  homeschoolLesson: {
    subject: 'Math: Recipe Scaling', ageRange: '6-12', duration: 30,
    activity: 'Scale the mole recipe to serve 12, then 24. Practice fractions with measuring cups.',
    discussion: ['Why does mole have so many ingredients?', 'How do chilies and chocolate taste together?', 'What makes a recipe a family secret?'],
    funFacts: ['Mole negro has 36+ ingredients in traditional recipes', 'Chocolate was used in savory dishes by the Aztecs first', 'Oaxaca is called "the land of seven moles"'],
    vocabulary: [{ word: 'Mole', definition: 'A complex Mexican sauce from Nahuatl word meaning sauce' }, { word: 'Cacao', definition: 'The plant chocolate comes from' }, { word: 'Indigenous', definition: 'Native to a region, the original inhabitants' }],
  },
};

export const phoRecipe: Recipe = {
  id: 'pho', name: 'Beef Pho', cultureId: 'vietnamese', cultureName: 'Vietnamese',
  emoji: '🍜', isFeatured: true, difficulty: 'hard', prepTime: 20, cookTime: 180, servings: 4,
  description: 'Rich, fragrant bone broth noodle soup with spices, thin beef slices, and fresh herbs.',
  tags: ['soup', 'noodles', 'beef', 'aromatic'],
  ingredients: [
    { name: 'Beef bones', amount: '3', unit: 'lbs', notes: 'knuckle and neck' },
    { name: 'Ginger', amount: '3-inch', unit: 'piece', notes: 'charred' },
    { name: 'Onion', amount: '1', unit: 'large', notes: 'charred' },
    { name: 'Star anise', amount: '4' },
    { name: 'Cinnamon stick', amount: '1' },
    { name: 'Fish sauce', amount: '3', unit: 'tbsp' },
    { name: 'Rice noodles', amount: '12', unit: 'oz' },
    { name: 'Beef sirloin', amount: '8', unit: 'oz', notes: 'thinly sliced raw' },
    { name: 'Bean sprouts', amount: '2', unit: 'cups' },
    { name: 'Fresh basil', amount: '1', unit: 'bunch' },
    { name: 'Lime', amount: '2', notes: 'wedged' },
  ],
  steps: [
    { step: 1, instruction: 'Blanch bones in boiling water 10 min, drain and rinse.' },
    { step: 2, instruction: 'Char ginger and onion directly over flame or under broiler.' },
    { step: 3, instruction: 'Simmer bones with charred aromatics, star anise, and cinnamon for 3 hours. Skim regularly.', tip: 'Low, gentle simmer = clear broth' },
    { step: 4, instruction: 'Strain broth. Season with fish sauce and salt.' },
    { step: 5, instruction: 'Cook noodles per package. Divide into bowls.' },
    { step: 6, instruction: 'Pour very hot broth over noodles and raw beef — the heat cooks the beef. Top with herbs.' },
  ],
  kidHelperTasks: ['Add herbs to the bowl', 'Squeeze lime juice', 'Count the star anise'],
  nutritionNotes: 'Bone broth is rich in collagen and minerals. Customize add-ins to preference.',
  nutritionFacts: { calories: 420, protein: 35, carbs: 42, fat: 10, fiber: 2 },
  culturalHistory: 'Pho originated in northern Vietnam in the early 20th century, likely influenced by French pot-au-feu and Chinese rice noodles. It became Vietnam\'s national dish and spread worldwide after the Vietnam War.',
  aiHint: 'Charring the ginger and onion is non-negotiable — it creates the signature smoky sweetness.',
  homeschoolLesson: {
    subject: 'History: Vietnam & French Colonialism', ageRange: '6-12', duration: 35,
    activity: 'Research how French colonialism influenced Vietnamese food. Make a T-chart of French vs Vietnamese ingredients in pho.',
    discussion: ['How did France change Vietnamese food?', 'Why do people bring their home country\'s food when they move?', 'What does pho taste like to you?'],
    funFacts: ['Vietnam was a French colony for nearly 100 years', 'Pho restaurants are called "phở" shops — open from 5am', 'One billion bowls of pho are eaten in Vietnam each year'],
    vocabulary: [{ word: 'Colonialism', definition: 'When one country controls another country' }, { word: 'Umami', definition: 'The fifth taste — savory and rich' }, { word: 'Aromatic', definition: 'Ingredients that add fragrance and flavor' }],
  },
};

export const springRollsRecipe: Recipe = {
  id: 'spring-rolls', name: 'Fresh Spring Rolls (Gỏi Cuốn)', cultureId: 'vietnamese', cultureName: 'Vietnamese',
  emoji: '🥢', isFeatured: false, difficulty: 'easy', prepTime: 30, cookTime: 10, servings: 4,
  description: 'Rice paper rolls filled with shrimp, vermicelli noodles, herbs, and peanut dipping sauce.',
  tags: ['fresh', 'no-cook', 'shrimp', 'healthy'],
  ingredients: [
    { name: 'Rice paper wrappers', amount: '12' },
    { name: 'Cooked shrimp', amount: '24', notes: 'halved lengthwise' },
    { name: 'Rice vermicelli', amount: '4', unit: 'oz', notes: 'cooked' },
    { name: 'Butter lettuce', amount: '12', unit: 'leaves' },
    { name: 'Fresh mint', amount: '1/2', unit: 'cup' },
    { name: 'Fresh basil', amount: '1/2', unit: 'cup' },
    { name: 'Cucumber', amount: '1', notes: 'julienned' },
    { name: 'Peanut butter', amount: '3', unit: 'tbsp', notes: 'for dipping sauce' },
    { name: 'Hoisin sauce', amount: '2', unit: 'tbsp' },
    { name: 'Lime juice', amount: '1', unit: 'tbsp' },
  ],
  steps: [
    { step: 1, instruction: 'Mix peanut butter, hoisin, lime juice, and 2 tbsp water for dipping sauce.' },
    { step: 2, instruction: 'Fill a wide dish with warm water. Dip rice paper 10 seconds until pliable.' },
    { step: 3, instruction: 'Lay on flat surface. Add lettuce, noodles, herbs, cucumber.' },
    { step: 4, instruction: 'Add 2 shrimp halves near the bottom edge.', tip: 'Place shrimp so they show through the wrapper' },
    { step: 5, instruction: 'Roll tightly from bottom, fold in sides, continue rolling. Serve with peanut sauce.' },
  ],
  kidHelperTasks: ['Dip rice paper in water', 'Place ingredients on wrapper', 'Practice rolling', 'Mix the dipping sauce'],
  nutritionNotes: 'Light and fresh. High protein from shrimp. Herbs add vitamins.',
  nutritionFacts: { calories: 220, protein: 18, carbs: 28, fat: 5, fiber: 2 },
  culturalHistory: 'Gỏi cuốn (fresh spring rolls) are distinct from the fried chả giò. They\'re a summer food from southern Vietnam, where fresh herbs grow abundantly. Each region has its own dipping sauce.',
  aiHint: 'Work quickly — rice paper sticks to itself. Keep rolls covered with a damp cloth.',
  homeschoolLesson: {
    subject: 'Science: Plant Herbs', ageRange: '6-12', duration: 30,
    activity: 'Taste each herb separately (mint, basil, cilantro). Describe the flavor. Then plant your own herb seeds.',
    discussion: ['How do herbs change the flavor of food?', 'Which herb do you like best?', 'Why do warm climates grow more fresh herbs?'],
    funFacts: ['Vietnam uses over 50 herbs in cooking', 'Rice paper is made from just rice flour and water', 'Southern Vietnam is warmer and uses more fresh herbs than the north'],
    vocabulary: [{ word: 'Herb', definition: 'A plant used for flavor or medicine' }, { word: 'Vermicelli', definition: 'Very thin noodles, from Italian meaning "little worms"' }, { word: 'Pliable', definition: 'Soft and easy to bend without breaking' }],
  },
};

export const ghormehSabziRecipe: Recipe = {
  id: 'ghormeh-sabzi', name: 'Ghormeh Sabzi', cultureId: 'persian', cultureName: 'Persian',
  emoji: '🌿', isFeatured: true, difficulty: 'medium', prepTime: 20, cookTime: 120, servings: 4,
  description: 'Persian herb stew with kidney beans, dried limes, and lamb — Iran\'s most beloved dish.',
  tags: ['stew', 'herbs', 'lamb', 'dried limes'],
  ingredients: [
    { name: 'Lamb shoulder', amount: '1.5', unit: 'lbs', notes: 'cubed' },
    { name: 'Fresh parsley', amount: '2', unit: 'cups', notes: 'finely chopped' },
    { name: 'Fresh fenugreek', amount: '1', unit: 'cup', notes: 'or 2 tbsp dried' },
    { name: 'Green onions', amount: '1', unit: 'bunch', notes: 'finely chopped' },
    { name: 'Dried limes (limu omani)', amount: '4', notes: 'pierced with a knife' },
    { name: 'Kidney beans', amount: '1', unit: 'can', notes: 'drained' },
    { name: 'Turmeric', amount: '1', unit: 'tsp' },
    { name: 'Onion', amount: '1', notes: 'diced' },
  ],
  steps: [
    { step: 1, instruction: 'Fry herbs in 3 tbsp oil over medium heat for 20 min, stirring often, until very dark and fragrant.', tip: 'This step is critical — undercooked herbs make the stew bitter' },
    { step: 2, instruction: 'Brown lamb with onion and turmeric.' },
    { step: 3, instruction: 'Combine lamb, fried herbs, dried limes in a pot. Cover with 3 cups water. Simmer 1.5 hours.' },
    { step: 4, instruction: 'Add kidney beans, simmer 20 more min. Serve with tahdig.' },
  ],
  kidHelperTasks: ['Drain the kidney beans', 'Stir the herbs (with supervision)', 'Pierce the dried limes'],
  nutritionNotes: 'High in iron and protein. Fresh herbs provide significant vitamin K.',
  nutritionFacts: { calories: 460, protein: 38, carbs: 22, fat: 24, fiber: 7 },
  culturalHistory: 'Ghormeh sabzi has been made in Persia for over 2,000 years. It is considered the national dish of Iran. The dried lime (limu omani) gives it a unique sour-smoky flavor found nowhere else.',
  aiHint: 'Frying the herbs dark is not burning them — this step develops the stew\'s signature deep flavor.',
  homeschoolLesson: {
    subject: 'History: Persian Empire', ageRange: '6-12', duration: 35,
    activity: 'Map the Persian Empire at its peak. Compare its size to your country. Discuss trade routes that spread herbs and spices.',
    discussion: ['Why was the Persian Empire so powerful?', 'How did trade spread food across the world?', 'What other civilizations did Persia influence?'],
    funFacts: ['The Persian Empire was the largest in ancient history at its peak', 'Iran has one of the world\'s oldest cuisines — 2,500+ years', 'Dried limes are unique to Persian and Gulf cooking'],
    vocabulary: [{ word: 'Fenugreek', definition: 'An herb with a slightly bitter, maple-like flavor' }, { word: 'Simmer', definition: 'Cooking just below boiling point' }, { word: 'Empire', definition: 'A large group of nations ruled by one power' }],
  },
};

export const tahdigRecipe: Recipe = {
  id: 'tahdig', name: 'Tahdig (Crispy Rice)', cultureId: 'persian', cultureName: 'Persian',
  emoji: '🍚', isFeatured: false, difficulty: 'medium', prepTime: 10, cookTime: 60, servings: 4,
  description: 'The coveted golden crust formed at the bottom of the Persian rice pot — crispy, saffron-scented perfection.',
  tags: ['rice', 'crispy', 'saffron', 'vegetarian'],
  ingredients: [
    { name: 'Basmati rice', amount: '2', unit: 'cups' },
    { name: 'Saffron', amount: '1/2', unit: 'tsp', notes: 'bloomed in 2 tbsp hot water' },
    { name: 'Butter', amount: '3', unit: 'tbsp' },
    { name: 'Oil', amount: '3', unit: 'tbsp' },
    { name: 'Salt', amount: '1', unit: 'tbsp', notes: 'for parboiling' },
    { name: 'Yogurt', amount: '2', unit: 'tbsp', notes: 'optional — for yogurt tahdig' },
  ],
  steps: [
    { step: 1, instruction: 'Rinse rice until clear. Parboil in salted water 7 min. Drain.' },
    { step: 2, instruction: 'Heat oil and butter in pot. Mix 1 cup parboiled rice with saffron water and yogurt. Spread in pot bottom.' },
    { step: 3, instruction: 'Mound remaining rice on top. Poke 5–6 holes with spoon handle to the bottom. Drizzle with melted butter.' },
    { step: 4, instruction: 'Cover with wrapped lid (use a kitchen towel under lid to absorb steam). Cook on low 45 min.', tip: 'The towel absorbs steam and makes the crust crispier' },
    { step: 5, instruction: 'Invert onto a platter. The golden crust comes out on top. Serve immediately.' },
  ],
  kidHelperTasks: ['Bloom saffron in hot water', 'Poke the steam holes', 'Help invert the pot (with adult help)'],
  nutritionNotes: 'Complex carbs. Saffron adds color and mood-boosting compounds.',
  nutritionFacts: { calories: 320, protein: 5, carbs: 58, fat: 8, fiber: 1 },
  culturalHistory: 'Tahdig means "bottom of the pot" in Farsi. The crispy rice crust is so beloved in Iran that fighting for the last piece is a family tradition. Every Persian cook is judged by their tahdig.',
  aiHint: 'Never lift the lid during cooking — the steam is what creates the perfect crust.',
  homeschoolLesson: {
    subject: 'Science: Steam and Heat Transfer', ageRange: '6-12', duration: 25,
    activity: 'Experiment with steam — observe how a towel under a pot lid absorbs moisture. Discuss how heat transfers from pot to rice.',
    discussion: ['Why does the rice turn golden and crispy?', 'What is steam?', 'Why do we use a towel under the lid?'],
    funFacts: ['Saffron is the world\'s most expensive spice by weight', 'The word tahdig means "bottom of the pot"', 'Persian rice technique is called "polow" and has specific rules'],
    vocabulary: [{ word: 'Saffron', definition: 'A spice made from crocus flower stigmas' }, { word: 'Parboil', definition: 'To partially cook by boiling' }, { word: 'Steam', definition: 'Water in gas form, created by heating water' }],
  },
};

export const biryaniRecipe: Recipe = {
  id: 'biryani', name: 'Chicken Biryani', cultureId: 'indian', cultureName: 'Indian',
  emoji: '🍛', isFeatured: true, difficulty: 'hard', prepTime: 30, cookTime: 90, servings: 6,
  description: 'Aromatic layered rice dish with marinated chicken, whole spices, caramelized onions, and saffron.',
  tags: ['rice', 'chicken', 'layered', 'saffron', 'aromatic'],
  ingredients: [
    { name: 'Basmati rice', amount: '3', unit: 'cups' },
    { name: 'Chicken pieces', amount: '2.5', unit: 'lbs' },
    { name: 'Yogurt', amount: '1', unit: 'cup' },
    { name: 'Onions', amount: '3', notes: 'thinly sliced' },
    { name: 'Saffron', amount: '1/2', unit: 'tsp', notes: 'in 1/4 cup warm milk' },
    { name: 'Garam masala', amount: '2', unit: 'tsp' },
    { name: 'Ginger-garlic paste', amount: '2', unit: 'tbsp' },
    { name: 'Whole spices', amount: '1', unit: 'set', notes: 'bay leaf, cardamom, cloves, cinnamon' },
    { name: 'Fresh mint', amount: '1/2', unit: 'cup' },
    { name: 'Ghee', amount: '4', unit: 'tbsp' },
  ],
  steps: [
    { step: 1, instruction: 'Marinate chicken in yogurt, ginger-garlic paste, garam masala, and salt for 2 hours.' },
    { step: 2, instruction: 'Fry onions in ghee until deep golden brown, 20–25 min. Remove and set aside.' },
    { step: 3, instruction: 'Cook marinated chicken in the same pan until half-done, 15 min.' },
    { step: 4, instruction: 'Parboil rice with whole spices until 70% cooked. Drain.' },
    { step: 5, instruction: 'Layer: chicken, rice, fried onions, mint, saffron milk. Repeat. Seal pot with dough or foil.', tip: 'The seal traps steam for the "dum" technique' },
    { step: 6, instruction: 'Cook on lowest heat 30 min. Open at the table for the full aroma effect.' },
  ],
  kidHelperTasks: ['Measure spices', 'Layer the ingredients', 'Pick mint leaves', 'Bloom saffron in milk'],
  nutritionNotes: 'Complete meal with protein and carbs. Whole spices have anti-inflammatory properties.',
  nutritionFacts: { calories: 580, protein: 38, carbs: 62, fat: 18, fiber: 3 },
  culturalHistory: 'Biryani came to India with the Mughal Empire (1526–1857). The Mughals brought Persian-influenced rice cooking from Central Asia. Today there are 26+ regional biryani styles across India.',
  aiHint: 'Dum cooking (sealed steam) is the secret — don\'t rush it or open the pot early.',
  homeschoolLesson: {
    subject: 'History: Mughal Empire', ageRange: '6-12', duration: 40,
    activity: 'Draw a Mughal emperor\'s feast. Research Mughal architecture (Taj Mahal) and connect it to the culture\'s love of beauty and craft.',
    discussion: ['What did the Mughals bring to India?', 'Why do empires blend cultures?', 'What is the Taj Mahal and who built it?'],
    funFacts: ['The Mughal Empire ruled India for 300+ years', 'Biryani was served at Mughal royal courts', 'There are 26+ regional biryani styles across India'],
    vocabulary: [{ word: 'Mughal', definition: 'A Muslim empire that ruled much of India from 1526–1857' }, { word: 'Dum', definition: 'A cooking technique that slow-steams in a sealed pot' }, { word: 'Saffron', definition: 'A golden spice from crocus flowers, very expensive' }],
  },
};

export const dalTadkaRecipe: Recipe = {
  id: 'dal-tadka', name: 'Dal Tadka', cultureId: 'indian', cultureName: 'Indian',
  emoji: '🫘', isFeatured: false, difficulty: 'easy', prepTime: 10, cookTime: 40, servings: 4,
  description: 'Yellow lentils tempered with cumin, mustard seeds, turmeric, and ghee — Indian comfort food.',
  tags: ['lentils', 'vegetarian', 'comfort food', 'quick'],
  ingredients: [
    { name: 'Yellow lentils (toor dal)', amount: '1.5', unit: 'cups' },
    { name: 'Ghee', amount: '2', unit: 'tbsp' },
    { name: 'Cumin seeds', amount: '1', unit: 'tsp' },
    { name: 'Mustard seeds', amount: '1/2', unit: 'tsp' },
    { name: 'Onion', amount: '1', notes: 'diced' },
    { name: 'Tomatoes', amount: '2', notes: 'diced' },
    { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
    { name: 'Garam masala', amount: '1', unit: 'tsp' },
    { name: 'Fresh cilantro', amount: '1/4', unit: 'cup' },
  ],
  steps: [
    { step: 1, instruction: 'Cook lentils with turmeric in 4 cups water until soft, 25 min. Mash slightly.' },
    { step: 2, instruction: 'In a separate pan, heat ghee until shimmering. Add cumin and mustard seeds — they will splutter.', tip: 'Cover the pan when seeds go in to avoid splatter' },
    { step: 3, instruction: 'Add onion, cook until golden. Add tomatoes, cook 5 min.' },
    { step: 4, instruction: 'Pour tempering over lentils, add garam masala. Stir and simmer 5 min.' },
    { step: 5, instruction: 'Garnish with cilantro. Serve with rice or naan.' },
  ],
  kidHelperTasks: ['Rinse lentils', 'Stir the lentils as they cook', 'Pick cilantro leaves', 'Measure spices'],
  nutritionNotes: 'Excellent plant-based protein. Lentils are high in iron and folate.',
  nutritionFacts: { calories: 280, protein: 16, carbs: 38, fat: 7, fiber: 10 },
  culturalHistory: 'Dal (lentils) has been eaten in India for 4,000+ years. It is the most widely eaten food across all of India\'s regions and is considered the backbone of vegetarian Indian diet. "Tadka" means tempering — blooming spices in hot fat.',
  aiHint: 'The tadka (tempering) is poured over at the end — this final sizzle is what makes the dish.',
  homeschoolLesson: {
    subject: 'Nutrition: Plant Proteins', ageRange: '6-12', duration: 25,
    activity: 'Compare protein in lentils vs meat. Create a protein sources chart. Try sprouting lentils at home.',
    discussion: ['Why do vegetarians eat lots of lentils?', 'What is protein and why do we need it?', 'What other legumes can you name?'],
    funFacts: ['Lentils have been grown in India for 4,000+ years', 'India grows 50% of the world\'s lentils', 'Tadka technique is also used in Mexican cooking (similar to a sofrito)'],
    vocabulary: [{ word: 'Legume', definition: 'A plant whose seeds grow in pods — like lentils and beans' }, { word: 'Tempering', definition: 'Blooming spices in hot oil to release their flavor' }, { word: 'Ghee', definition: 'Clarified butter with milk solids removed' }],
  },
};

export const friedChickenRecipe: Recipe = {
  id: 'fried-chicken', name: 'Southern Fried Chicken', cultureId: 'southern', cultureName: 'Southern American',
  emoji: '🍗', isFeatured: true, difficulty: 'medium', prepTime: 20, cookTime: 30, servings: 4,
  description: 'Buttermilk-brined chicken with seasoned flour crust, pan-fried until deeply golden.',
  tags: ['chicken', 'crispy', 'comfort food', 'Southern'],
  ingredients: [
    { name: 'Chicken pieces', amount: '3', unit: 'lbs' },
    { name: 'Buttermilk', amount: '2', unit: 'cups' },
    { name: 'All-purpose flour', amount: '2', unit: 'cups' },
    { name: 'Paprika', amount: '2', unit: 'tsp' },
    { name: 'Garlic powder', amount: '1', unit: 'tsp' },
    { name: 'Cayenne', amount: '1/2', unit: 'tsp' },
    { name: 'Salt and pepper', amount: '2', unit: 'tsp each' },
    { name: 'Vegetable oil', amount: '2', unit: 'cups', notes: 'for frying' },
  ],
  steps: [
    { step: 1, instruction: 'Soak chicken in buttermilk with 1 tsp salt overnight or at least 4 hours.' },
    { step: 2, instruction: 'Mix flour with paprika, garlic powder, cayenne, salt, and pepper.' },
    { step: 3, instruction: 'Let chicken drip from buttermilk, dredge in seasoned flour. Press firmly.', tip: 'Double-dredge for extra crust: buttermilk again, then flour again' },
    { step: 4, instruction: 'Heat oil to 325°F in a cast iron skillet. Fry chicken in batches, 8–10 min per side.' },
    { step: 5, instruction: 'Drain on rack (not paper towels). Rest 5 min before serving.' },
  ],
  kidHelperTasks: ['Measure flour and spices', 'Stir the flour mixture', 'Press flour onto chicken (with gloves)'],
  nutritionNotes: 'High protein. Buttermilk brine tenderizes and adds a subtle tang. Baking is a lighter option.',
  nutritionFacts: { calories: 520, protein: 42, carbs: 32, fat: 22, fiber: 1 },
  culturalHistory: 'Fried chicken in the American South blends West African frying techniques (brought by enslaved people) with Scottish immigrants\' tradition of frying chicken in fat. African American cooks perfected it in the 1800s.',
  aiHint: 'A cast iron skillet at 325°F (not 375°F) cooks the crust and interior at the same rate.',
  homeschoolLesson: {
    subject: 'History: African American Culinary Heritage', ageRange: '6-12', duration: 35,
    activity: 'Research African American chefs and cooks who shaped American cuisine. Discuss how food tells the story of a people.',
    discussion: ['Who really invented fried chicken?', 'How does food preserve culture?', 'What other American foods came from African traditions?'],
    funFacts: ['Enslaved African cooks ran the kitchens of most Southern plantations', 'West African cooking commonly used frying techniques', 'James Hemings, enslaved by Thomas Jefferson, introduced mac and cheese to America'],
    vocabulary: [{ word: 'Brine', definition: 'A salty liquid used to soak and flavor meat' }, { word: 'Dredge', definition: 'To coat food in flour or breadcrumbs' }, { word: 'Cast iron', definition: 'A heavy metal pan that holds heat evenly' }],
  },
};

export const shrimpGritsRecipe: Recipe = {
  id: 'shrimp-grits', name: 'Shrimp & Grits', cultureId: 'southern', cultureName: 'Southern American',
  emoji: '🍤', isFeatured: false, difficulty: 'medium', prepTime: 15, cookTime: 30, servings: 4,
  description: 'Creamy stone-ground grits topped with Cajun-spiced shrimp in a smoky, buttery sauce.',
  tags: ['shrimp', 'grits', 'Cajun', 'coastal'],
  ingredients: [
    { name: 'Stone-ground grits', amount: '1', unit: 'cup' },
    { name: 'Large shrimp', amount: '1.5', unit: 'lbs', notes: 'peeled, deveined' },
    { name: 'Chicken broth', amount: '4', unit: 'cups' },
    { name: 'Butter', amount: '4', unit: 'tbsp' },
    { name: 'Sharp cheddar', amount: '1', unit: 'cup', notes: 'shredded' },
    { name: 'Bacon', amount: '4', unit: 'strips', notes: 'diced' },
    { name: 'Cajun seasoning', amount: '1', unit: 'tbsp' },
    { name: 'Garlic', amount: '3', unit: 'cloves', notes: 'minced' },
    { name: 'Green onions', amount: '4', notes: 'sliced' },
  ],
  steps: [
    { step: 1, instruction: 'Bring broth to boil. Whisk in grits slowly. Reduce heat, cook 20 min stirring often.', tip: 'Stone-ground grits take longer than instant but have far better flavor' },
    { step: 2, instruction: 'Remove from heat, stir in butter, cheese, salt. Keep warm.' },
    { step: 3, instruction: 'Cook bacon until crispy. Remove. Sauté garlic in bacon fat.' },
    { step: 4, instruction: 'Season shrimp with Cajun seasoning. Add to pan, cook 2 min per side.' },
    { step: 5, instruction: 'Serve shrimp over grits. Top with bacon and green onions.' },
  ],
  kidHelperTasks: ['Shred cheese', 'Stir the grits', 'Slice green onions (with kid-safe knife)'],
  nutritionNotes: 'High protein from shrimp. Grits are a whole grain when stone-ground.',
  nutritionFacts: { calories: 480, protein: 34, carbs: 38, fat: 20, fiber: 2 },
  culturalHistory: 'Grits come from the Muscogee (Creek) people who ground hominy corn — a technique adopted by Southern colonists. Shrimp and grits became a staple of the South Carolina Lowcountry and Gullah Geechee culture.',
  aiHint: 'Never use instant grits — stone-ground is the whole point of this dish.',
  homeschoolLesson: {
    subject: 'History: Gullah Geechee Culture', ageRange: '6-12', duration: 30,
    activity: 'Research the Gullah Geechee people of the South Carolina coast. Listen to Gullah language recordings. Map their homeland.',
    discussion: ['Who are the Gullah Geechee people?', 'How did coastal geography shape their food?', 'What is hominy and how is it made?'],
    funFacts: ['Gullah Geechee are descendants of enslaved West Africans on the Sea Islands', 'Grits come from the Muscogee word "sofka"', 'South Carolina is the shrimp capital of the East Coast'],
    vocabulary: [{ word: 'Grits', definition: 'Ground hominy corn, cooked into a porridge' }, { word: 'Hominy', definition: 'Corn treated with an alkaline solution to remove the hull' }, { word: 'Lowcountry', definition: 'The coastal plain region of South Carolina and Georgia' }],
  },
};

export const hummusRecipe: Recipe = {
  id: 'hummus', name: 'Classic Hummus', cultureId: 'mediterranean', cultureName: 'Mediterranean',
  emoji: '🫘', isFeatured: true, difficulty: 'easy', prepTime: 15, cookTime: 0, servings: 6,
  description: 'Silky blended chickpeas with tahini, lemon, and garlic — the most eaten dip in the world.',
  tags: ['dip', 'vegetarian', 'vegan', 'no-cook', 'chickpeas'],
  ingredients: [
    { name: 'Canned chickpeas', amount: '2', unit: 'cans', notes: 'drained, liquid reserved' },
    { name: 'Tahini', amount: '1/3', unit: 'cup' },
    { name: 'Lemon juice', amount: '3', unit: 'tbsp', notes: 'fresh' },
    { name: 'Garlic', amount: '2', unit: 'cloves' },
    { name: 'Ice water', amount: '3', unit: 'tbsp' },
    { name: 'Olive oil', amount: '2', unit: 'tbsp', notes: 'plus more for serving' },
    { name: 'Salt', amount: '1', unit: 'tsp' },
    { name: 'Paprika', amount: '1/2', unit: 'tsp', notes: 'for garnish' },
  ],
  steps: [
    { step: 1, instruction: 'Blend chickpeas alone for 1 min until powdery. Add tahini, lemon, garlic, and salt. Blend 1 min.' },
    { step: 2, instruction: 'With blender running, drizzle in ice water. Blend 3–5 min until ultra smooth.', tip: 'Ice water is the secret to ultra-creamy hummus' },
    { step: 3, instruction: 'Taste and adjust lemon and salt.' },
    { step: 4, instruction: 'Swirl onto plate, drizzle with olive oil, dust with paprika. Serve with pita or vegetables.' },
  ],
  kidHelperTasks: ['Drain chickpeas', 'Squeeze lemons', 'Press the blender button', 'Swirl hummus onto plate'],
  nutritionNotes: 'Excellent plant protein and fiber. Healthy fats from tahini and olive oil.',
  nutritionFacts: { calories: 180, protein: 8, carbs: 20, fat: 9, fiber: 5 },
  culturalHistory: 'Hummus (Hebrew/Arabic for "chickpea") has been eaten across the Middle East for centuries. Its exact origin is debated between Israel, Lebanon, Palestine, and Egypt. It\'s a dish of shared culture across the entire region.',
  aiHint: 'Blend much longer than you think — 5 full minutes makes it restaurant-smooth.',
  homeschoolLesson: {
    subject: 'Social Studies: Shared Cultures', ageRange: '6-12', duration: 25,
    activity: 'Map the countries that claim hummus as their own. Discuss how foods can be shared across cultures. Make a "foods we share" world map.',
    discussion: ['Why do multiple countries claim hummus?', 'What other foods are shared across cultures?', 'How do neighbors influence each other\'s cooking?'],
    funFacts: ['The largest hummus plate ever weighed 23,042 lbs (made in Lebanon)', 'Chickpeas have been farmed for 10,000 years', 'Hummus is technically spelled "ḥummuṣ" in Arabic'],
    vocabulary: [{ word: 'Tahini', definition: 'Ground sesame seed paste' }, { word: 'Legume', definition: 'Plants with seeds in pods, like chickpeas and lentils' }, { word: 'Mediterranean', definition: 'Region around the Mediterranean Sea, connecting Europe, Africa, and Asia' }],
  },
};

export const shakshukaRecipe: Recipe = {
  id: 'shakshuka', name: 'Shakshuka', cultureId: 'mediterranean', cultureName: 'Mediterranean',
  emoji: '🍳', isFeatured: false, difficulty: 'easy', prepTime: 10, cookTime: 25, servings: 4,
  description: 'Eggs poached in spiced tomato-pepper sauce — a North African and Middle Eastern staple.',
  tags: ['eggs', 'tomatoes', 'one-pan', 'breakfast', 'vegetarian'],
  ingredients: [
    { name: 'Eggs', amount: '6' },
    { name: 'Canned crushed tomatoes', amount: '28', unit: 'oz' },
    { name: 'Red bell peppers', amount: '2', notes: 'diced' },
    { name: 'Onion', amount: '1', notes: 'diced' },
    { name: 'Garlic', amount: '4', unit: 'cloves', notes: 'minced' },
    { name: 'Cumin', amount: '1', unit: 'tsp' },
    { name: 'Paprika', amount: '1', unit: 'tsp' },
    { name: 'Cayenne', amount: '1/4', unit: 'tsp' },
    { name: 'Feta cheese', amount: '1/2', unit: 'cup', notes: 'crumbled' },
    { name: 'Fresh parsley', amount: '1/4', unit: 'cup' },
  ],
  steps: [
    { step: 1, instruction: 'Sauté onion and peppers in olive oil until soft, 8 min. Add garlic and spices, 1 min.' },
    { step: 2, instruction: 'Add tomatoes, simmer 10 min until thick.' },
    { step: 3, instruction: 'Make 6 wells in the sauce. Crack an egg into each well.', tip: 'Crack eggs into a small cup first to avoid shells' },
    { step: 4, instruction: 'Cover and cook until whites are set but yolks are still runny, 5–7 min.' },
    { step: 5, instruction: 'Scatter feta and parsley on top. Serve in the pan with crusty bread.' },
  ],
  kidHelperTasks: ['Crack eggs into a cup', 'Stir the sauce', 'Crumble feta', 'Pick parsley leaves'],
  nutritionNotes: 'High protein from eggs. Lycopene-rich tomatoes. Low calorie complete meal.',
  nutritionFacts: { calories: 240, protein: 16, carbs: 18, fat: 12, fiber: 4 },
  culturalHistory: 'Shakshuka originated in North Africa (Tunisia) and is eaten across the Middle East and Israel. The word may come from the Tunisian Arabic for "mixture." It was brought to Israel by Tunisian and Libyan Jewish immigrants.',
  aiHint: 'Watch the eggs carefully at the end — 30 seconds too long and the yolks harden.',
  homeschoolLesson: {
    subject: 'Science: Egg Chemistry', ageRange: '6-12', duration: 25,
    activity: 'Observe how egg whites and yolks cook at different rates. Compare raw vs cooked protein under magnifying glass.',
    discussion: ['Why do egg whites turn white when they cook?', 'What is protein denaturation?', 'Why do we eat eggs from so many cultures?'],
    funFacts: ['Eggs are one of the most complete proteins in nature', 'The Sahara Desert is larger than the entire United States', 'Tunisia is where shakshuka likely originated — a small country in North Africa'],
    vocabulary: [{ word: 'Simmer', definition: 'Cooking just below boiling with small bubbles' }, { word: 'Poach', definition: 'Cooking gently in hot liquid' }, { word: 'Denaturation', definition: 'When heat changes the structure of protein' }],
  },
};

export const ramenRecipe: Recipe = {
  id: 'ramen', name: 'Shoyu Ramen', cultureId: 'japanese', cultureName: 'Japanese',
  emoji: '🍜', isFeatured: false, difficulty: 'hard', prepTime: 30, cookTime: 180, servings: 4,
  description: 'Soy-based broth with tender chashu pork, soft-boiled marinated eggs, nori, and bamboo shoots.',
  tags: ['soup', 'noodles', 'pork', 'umami'],
  ingredients: [
    { name: 'Pork belly', amount: '1', unit: 'lb', notes: 'for chashu' },
    { name: 'Chicken bones', amount: '2', unit: 'lbs' },
    { name: 'Soy sauce', amount: '1/4', unit: 'cup' },
    { name: 'Mirin', amount: '2', unit: 'tbsp' },
    { name: 'Sake', amount: '2', unit: 'tbsp' },
    { name: 'Ginger', amount: '2-inch', unit: 'piece' },
    { name: 'Green onions', amount: '4' },
    { name: 'Ramen noodles', amount: '12', unit: 'oz', notes: 'fresh or dried' },
    { name: 'Soft-boiled eggs', amount: '4', notes: 'marinated in soy-mirin' },
    { name: 'Nori sheets', amount: '4' },
    { name: 'Bamboo shoots', amount: '1', unit: 'cup' },
  ],
  steps: [
    { step: 1, instruction: 'Roll pork belly tightly and tie. Braise in soy, mirin, sake, and water for 2 hours at 325°F.' },
    { step: 2, instruction: 'Simmer chicken bones with ginger and green onions for 3 hours.' },
    { step: 3, instruction: 'Strain broth. Season with soy sauce and pork braising liquid.' },
    { step: 4, instruction: 'Marinate peeled soft-boiled eggs (7 min cook) in remaining pork braise for 1+ hour.' },
    { step: 5, instruction: 'Cook noodles per package. Divide into bowls.' },
    { step: 6, instruction: 'Ladle hot broth. Add sliced chashu, egg, bamboo shoots, and nori.' },
  ],
  kidHelperTasks: ['Choose toppings', 'Add nori to bowls', 'Help arrange ingredients beautifully'],
  nutritionNotes: 'High sodium — use low-sodium soy sauce. Rich in collagen from pork and bones.',
  nutritionFacts: { calories: 580, protein: 38, carbs: 55, fat: 22, fiber: 2 },
  culturalHistory: 'Ramen was introduced to Japan by Chinese immigrants in the 1880s and became Japan\'s own. After WWII, cheap American wheat was used to make ramen widely available. Today ramen has 4 major regional styles.',
  aiHint: 'Make the chashu and marinated eggs the day before — both improve overnight.',
  homeschoolLesson: {
    subject: 'History: Japanese Innovation', ageRange: '6-12', duration: 35,
    activity: 'Trace how ramen went from Chinese noodles to Japanese icon to global phenomenon. Map the ramen journey on a world map.',
    discussion: ['How did ramen change when it came to Japan?', 'What is "Japanification"?', 'Why did instant ramen become famous after WWII?'],
    funFacts: ['There are 10,000+ ramen restaurants in Tokyo alone', 'Momofuku Ando invented instant ramen in 1958', 'Each Japanese region has its own ramen style: shoyu, miso, tonkotsu, shio'],
    vocabulary: [{ word: 'Umami', definition: 'The fifth taste — savory, meaty, and rich' }, { word: 'Chashu', definition: 'Japanese braised pork belly' }, { word: 'Nori', definition: 'Dried seaweed sheets used in Japanese cuisine' }],
  },
};

export const onigiriRecipe: Recipe = {
  id: 'onigiri', name: 'Onigiri (Rice Balls)', cultureId: 'japanese', cultureName: 'Japanese',
  emoji: '🍙', isFeatured: true, difficulty: 'easy', prepTime: 20, cookTime: 10, servings: 4,
  description: 'Triangular rice balls with savory fillings and wrapped in nori — Japan\'s favorite snack.',
  tags: ['rice', 'snack', 'lunch box', 'no-cook'],
  ingredients: [
    { name: 'Japanese short-grain rice', amount: '2', unit: 'cups', notes: 'cooked and slightly warm' },
    { name: 'Nori sheets', amount: '4', notes: 'cut into strips' },
    { name: 'Canned tuna', amount: '1', unit: 'can', notes: 'mixed with 1 tbsp mayo' },
    { name: 'Salmon', amount: '4', unit: 'oz', notes: 'cooked and flaked' },
    { name: 'Umeboshi (pickled plum)', amount: '4' },
    { name: 'Salt', amount: '1', unit: 'tsp', notes: 'for hands' },
    { name: 'Sesame seeds', amount: '1', unit: 'tbsp' },
  ],
  steps: [
    { step: 1, instruction: 'Wet hands, sprinkle with salt. Take 1/2 cup warm rice.' },
    { step: 2, instruction: 'Press a hole in the center, add 1 tbsp filling. Close rice around it.' },
    { step: 3, instruction: 'Shape into triangle by pressing firmly with both palms and three fingers.', tip: 'Firm pressure = onigiri that holds together; gentle = it falls apart' },
    { step: 4, instruction: 'Wrap with nori strip. Sprinkle sesame seeds. Eat immediately or wrap for later.' },
  ],
  kidHelperTasks: ['Choose the filling', 'Press rice into triangles', 'Wrap with nori', 'Decorate with sesame seeds'],
  nutritionNotes: 'Portable, balanced snack. Rice provides quick energy, protein from fillings.',
  nutritionFacts: { calories: 220, protein: 10, carbs: 38, fat: 4, fiber: 1 },
  culturalHistory: 'Onigiri has been eaten in Japan for 2,000 years — the oldest written record is from 11th century. They were originally called "tonjiki" and eaten by Japanese nobles. Today they\'re sold in every convenience store in Japan.',
  aiHint: 'Only short-grain Japanese rice works — long-grain won\'t stick together.',
  homeschoolLesson: {
    subject: 'Japanese Culture: Bento and Food as Art', ageRange: '6-12', duration: 30,
    activity: 'Make a bento box with onigiri as the centerpiece. Discuss how Japanese food culture values presentation and beauty.',
    discussion: ['Why is presentation important in Japanese food?', 'What goes in a Japanese bento box?', 'How is Japanese food art different from food art in other cultures?'],
    funFacts: ['Japan has 50,000+ convenience stores that all sell onigiri', 'Bento culture started in 16th century Japan', 'Onigiri are mentioned in the 11th-century novel The Tale of Genji'],
    vocabulary: [{ word: 'Bento', definition: 'A single-portion Japanese packed meal' }, { word: 'Umeboshi', definition: 'Japanese pickled plum, very sour and salty' }, { word: 'Nori', definition: 'Dried edible seaweed sheets' }],
  },
};

export const bibimbapRecipe: Recipe = {
  id: 'bibimbap', name: 'Bibimbap', cultureId: 'korean', cultureName: 'Korean',
  emoji: '🍱', isFeatured: true, difficulty: 'medium', prepTime: 30, cookTime: 20, servings: 4,
  description: 'Mixed rice bowl with colorful individually-cooked vegetables, gochujang sauce, and a fried egg.',
  tags: ['rice', 'vegetable', 'gochujang', 'egg', 'colorful'],
  ingredients: [
    { name: 'Short-grain rice', amount: '2', unit: 'cups', notes: 'cooked' },
    { name: 'Spinach', amount: '2', unit: 'cups', notes: 'blanched and seasoned' },
    { name: 'Bean sprouts', amount: '1', unit: 'cup', notes: 'blanched' },
    { name: 'Carrots', amount: '2', notes: 'julienned and sautéed' },
    { name: 'Zucchini', amount: '1', notes: 'julienned and sautéed' },
    { name: 'Shiitake mushrooms', amount: '1', unit: 'cup', notes: 'sautéed' },
    { name: 'Ground beef', amount: '8', unit: 'oz', notes: 'seasoned with soy and sesame' },
    { name: 'Eggs', amount: '4', notes: 'fried sunny side up' },
    { name: 'Gochujang', amount: '3', unit: 'tbsp' },
    { name: 'Sesame oil', amount: '2', unit: 'tsp' },
  ],
  steps: [
    { step: 1, instruction: 'Prepare each vegetable separately: blanch, sauté, or marinate. Season each with sesame oil, garlic, and salt.' },
    { step: 2, instruction: 'Cook ground beef with soy sauce, sesame oil, and a little sugar.' },
    { step: 3, instruction: 'Make gochujang sauce: mix gochujang, sesame oil, sugar, and a little water.' },
    { step: 4, instruction: 'Arrange rice in bowls. Place vegetables and beef in colorful sections around the bowl.', tip: 'The visual arrangement is part of the dish — take time with it' },
    { step: 5, instruction: 'Top with fried egg and gochujang. Mix everything together at the table.' },
  ],
  kidHelperTasks: ['Arrange vegetables in sections', 'Mix the gochujang sauce', 'Choose their toppings', 'Mix the bowl at the table'],
  nutritionNotes: 'Complete balanced meal. Many vegetables provide diverse vitamins. Protein from egg and beef.',
  nutritionFacts: { calories: 520, protein: 28, carbs: 68, fat: 15, fiber: 5 },
  culturalHistory: 'Bibimbap means "mixed rice" and originated in Korea during the Joseon Dynasty (1392–1897). It may have started as a way to use leftover vegetables mixed with rice. Today it\'s Korea\'s most internationally recognized dish.',
  aiHint: 'Cook each vegetable separately — bibimbap is about individual flavors that combine when mixed.',
  homeschoolLesson: {
    subject: 'Art: Color and Arrangement', ageRange: '6-12', duration: 30,
    activity: 'Design a bibimbap bowl using art supplies before cooking. Discuss the color wheel and how food plating uses color theory.',
    discussion: ['Why is the visual arrangement of bibimbap important?', 'What colors represent different nutrients?', 'What makes food beautiful?'],
    funFacts: ['Bibimbap is served in a hot stone bowl called dolsot', 'Korea has over 200 types of kimchi', 'Gochujang has been made in Korea for 700+ years'],
    vocabulary: [{ word: 'Gochujang', definition: 'Korean fermented red pepper paste' }, { word: 'Dolsot', definition: 'A hot stone bowl used for serving bibimbap' }, { word: 'Julienne', definition: 'To cut vegetables into thin matchstick strips' }],
  },
};

export const japchaelRecipe: Recipe = {
  id: 'japchae', name: 'Japchae (Glass Noodles)', cultureId: 'korean', cultureName: 'Korean',
  emoji: '🍜', isFeatured: false, difficulty: 'medium', prepTime: 20, cookTime: 20, servings: 4,
  description: 'Stir-fried sweet potato glass noodles with colorful vegetables, beef, and sesame.',
  tags: ['noodles', 'glass noodles', 'stir-fry', 'sesame'],
  ingredients: [
    { name: 'Dangmyeon (sweet potato noodles)', amount: '8', unit: 'oz' },
    { name: 'Beef sirloin', amount: '6', unit: 'oz', notes: 'thinly sliced' },
    { name: 'Spinach', amount: '2', unit: 'cups' },
    { name: 'Carrots', amount: '1', notes: 'julienned' },
    { name: 'Onion', amount: '1', notes: 'sliced' },
    { name: 'Shiitake mushrooms', amount: '4', notes: 'sliced' },
    { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
    { name: 'Sesame oil', amount: '2', unit: 'tbsp' },
    { name: 'Sugar', amount: '1', unit: 'tbsp' },
    { name: 'Sesame seeds', amount: '1', unit: 'tbsp' },
  ],
  steps: [
    { step: 1, instruction: 'Cook noodles per package. Rinse cold, toss with 1 tsp sesame oil.' },
    { step: 2, instruction: 'Marinate beef in soy sauce, sugar, and sesame oil 15 min. Stir-fry, set aside.' },
    { step: 3, instruction: 'Stir-fry each vegetable separately in sesame oil, season with soy and salt.' },
    { step: 4, instruction: 'Combine noodles, beef, and all vegetables in large pan. Add remaining soy sauce and sesame oil.' },
    { step: 5, instruction: 'Toss over medium heat 3 min. Sprinkle sesame seeds. Serve warm or at room temp.' },
  ],
  kidHelperTasks: ['Sprinkle sesame seeds', 'Stir the noodles', 'Arrange the dish on a plate'],
  nutritionNotes: 'Gluten-free noodles. Rich in iron from spinach and beef. Moderate calorie.',
  nutritionFacts: { calories: 420, protein: 22, carbs: 52, fat: 14, fiber: 4 },
  culturalHistory: 'Japchae was created in the 17th century for a Korean king who loved it so much he gave the chef land. "Japchae" literally means "mixed vegetables." It is served at Korean celebrations, birthdays, and holidays.',
  aiHint: 'Sesame oil is added at the very end — heating it too long destroys its delicate flavor.',
  homeschoolLesson: {
    subject: 'History: Korean Joseon Dynasty', ageRange: '6-12', duration: 30,
    activity: 'Research the Joseon Dynasty and its influence on Korean culture. Draw a royal Korean court feast.',
    discussion: ['What makes a dish "royal"?', 'How did royal courts influence food culture?', 'What other dishes were created for kings and queens?'],
    funFacts: ['Japchae was created for King Gwanghaegun in 1608', 'Sweet potato noodles are naturally gluten-free', 'Korean royal court cuisine (surasang) featured 12 dishes at every meal'],
    vocabulary: [{ word: 'Dangmyeon', definition: 'Sweet potato starch noodles, also called glass noodles' }, { word: 'Joseon', definition: 'Korean dynasty that ruled from 1392 to 1897' }, { word: 'Stir-fry', definition: 'Cooking quickly in a very hot pan with constant motion' }],
  },
};

export const jollofRiceRecipe: Recipe = {
  id: 'jollof-rice', name: 'Jollof Rice', cultureId: 'west-african', cultureName: 'West African',
  emoji: '🍚', isFeatured: true, difficulty: 'medium', prepTime: 20, cookTime: 60, servings: 6,
  description: 'One-pot smoky tomato-based rice with chicken, peppers, and onions — West Africa\'s most beloved dish.',
  tags: ['rice', 'chicken', 'one-pot', 'smoky', 'tomato'],
  ingredients: [
    { name: 'Long-grain parboiled rice', amount: '3', unit: 'cups' },
    { name: 'Chicken pieces', amount: '2.5', unit: 'lbs' },
    { name: 'Crushed tomatoes', amount: '28', unit: 'oz' },
    { name: 'Red bell peppers', amount: '3', notes: 'roasted and blended' },
    { name: 'Scotch bonnet or habanero', amount: '1', notes: 'blended (optional for kids)' },
    { name: 'Onions', amount: '2', notes: 'diced' },
    { name: 'Chicken broth', amount: '2', unit: 'cups' },
    { name: 'Tomato paste', amount: '3', unit: 'tbsp' },
    { name: 'Curry powder', amount: '1', unit: 'tsp' },
    { name: 'Thyme', amount: '1', unit: 'tsp' },
    { name: 'Bay leaves', amount: '2' },
  ],
  steps: [
    { step: 1, instruction: 'Season chicken with salt, pepper, curry, thyme. Fry until golden. Remove.' },
    { step: 2, instruction: 'Fry onions in same pot until translucent. Add tomato paste, fry 5 min until darkened.' },
    { step: 3, instruction: 'Add blended tomatoes and peppers. Cook down 20 min, stirring, until paste-thick.' },
    { step: 4, instruction: 'Add broth, bay leaves, and rinsed rice. Stir, place chicken on top.' },
    { step: 5, instruction: 'Cover tightly, cook on low 30 min. Let bottom slightly scorch — that\'s the "party jollof."', tip: 'The slightly smoky bottom crust is celebrated, not a mistake' },
  ],
  kidHelperTasks: ['Rinse the rice', 'Stir the tomato base', 'Season the chicken'],
  nutritionNotes: 'Complete one-pot meal. Lycopene-rich tomatoes and vitamins from peppers.',
  nutritionFacts: { calories: 510, protein: 32, carbs: 62, fat: 14, fiber: 4 },
  culturalHistory: 'Jollof rice originated with the Wolof people of Senegal and Gambia. It spread across West Africa via trade routes. Today there is a famous friendly "Jollof Wars" rivalry between Nigeria and Ghana over who makes it best.',
  aiHint: 'The scorched bottom ("party jollof") is the most prized part — don\'t stir after adding rice.',
  homeschoolLesson: {
    subject: 'Geography: West Africa', ageRange: '6-12', duration: 35,
    activity: 'Map all 16 West African nations. Research each country\'s flag. Find which ones have the colors of the pan-African flag.',
    discussion: ['What is the "Jollof Wars" and why do people care?', 'How does food connect people across countries?', 'What is the pan-African flag and what do its colors mean?'],
    funFacts: ['Nigeria is the most populous country in Africa with 220 million people', 'The "Jollof Wars" between Nigeria and Ghana is a friendly online debate with millions of fans', 'West Africa gave the world okra, black-eyed peas, and rice cultivation techniques'],
    vocabulary: [{ word: 'Wolof', definition: 'An ethnic group and language from Senegal and Gambia' }, { word: 'Pan-African', definition: 'Representing or uniting all of Africa' }, { word: 'Parboiled', definition: 'Rice that is partially cooked before being dried' }],
  },
};

export const egusiSoupRecipe: Recipe = {
  id: 'egusi-soup', name: 'Egusi Soup', cultureId: 'west-african', cultureName: 'West African',
  emoji: '🥘', isFeatured: false, difficulty: 'medium', prepTime: 20, cookTime: 60, servings: 6,
  description: 'Hearty ground melon seed soup with leafy greens, palm oil, and assorted meats — a Nigerian classic.',
  tags: ['soup', 'melon seeds', 'palm oil', 'Nigerian'],
  ingredients: [
    { name: 'Ground egusi (melon seeds)', amount: '2', unit: 'cups' },
    { name: 'Palm oil', amount: '1/2', unit: 'cup' },
    { name: 'Beef or goat', amount: '1.5', unit: 'lbs', notes: 'cut into pieces' },
    { name: 'Stockfish', amount: '4', unit: 'oz', notes: 'soaked' },
    { name: 'Spinach or bitter leaf', amount: '3', unit: 'cups', notes: 'chopped' },
    { name: 'Onion', amount: '1', notes: 'blended' },
    { name: 'Crayfish', amount: '2', unit: 'tbsp', notes: 'ground' },
    { name: 'Scotch bonnet', amount: '1', notes: 'blended' },
    { name: 'Seasoning cubes', amount: '2' },
  ],
  steps: [
    { step: 1, instruction: 'Season and cook meat with onion and seasoning until tender, 30 min. Reserve broth.' },
    { step: 2, instruction: 'Heat palm oil in pot, add blended onion and pepper, fry 10 min.' },
    { step: 3, instruction: 'Mix egusi with water to form a paste. Add to pot in small spoonfuls.' },
    { step: 4, instruction: 'Add meat broth, crayfish, stockfish, and meats. Simmer 20 min.' },
    { step: 5, instruction: 'Add greens and stockfish. Cook 5 more min. Serve with fufu or pounded yam.' },
  ],
  kidHelperTasks: ['Measure egusi seeds', 'Wash the spinach', 'Stir the soup'],
  nutritionNotes: 'High in protein and healthy fats from egusi seeds. Palm oil provides vitamins A and E.',
  nutritionFacts: { calories: 520, protein: 36, carbs: 12, fat: 38, fiber: 5 },
  culturalHistory: 'Egusi soup is eaten across Nigeria, Cameroon, Ghana, and other West African countries. Egusi seeds (from a type of wild melon) have been a protein source in West Africa for thousands of years.',
  aiHint: 'Adding egusi in small spoonfuls (not all at once) prevents clumping and creates a better texture.',
  homeschoolLesson: {
    subject: 'Science: Seeds and Nutrition', ageRange: '6-12', duration: 30,
    activity: 'Examine different seeds (sunflower, pumpkin, egusi). Compare their size, texture, and nutritional content.',
    discussion: ['What nutrients are found in seeds?', 'Why did people discover that seeds were edible?', 'What other seeds do we eat?'],
    funFacts: ['Egusi seeds are from the same family as watermelon', 'Palm oil is the most consumed vegetable oil in the world', 'West Africa produces 80% of the world\'s shea butter from shea seeds'],
    vocabulary: [{ word: 'Egusi', definition: 'Ground seeds from a type of wild melon, high in protein and fat' }, { word: 'Palm oil', definition: 'Orange-red oil from the fruit of oil palm trees' }, { word: 'Stockfish', definition: 'Dried, unsalted cod fish common in West African cooking' }],
  },
};

export const misirWatRecipe: Recipe = {
  id: 'misir-wat', name: 'Misir Wat (Red Lentil Stew)', cultureId: 'ethiopian', cultureName: 'Ethiopian',
  emoji: '🫘', isFeatured: true, difficulty: 'easy', prepTime: 15, cookTime: 45, servings: 4,
  description: 'Spiced red lentils cooked in berbere spice and niter kibbeh, served on spongy injera bread.',
  tags: ['lentils', 'berbere', 'vegan', 'injera', 'spiced'],
  ingredients: [
    { name: 'Red lentils', amount: '2', unit: 'cups' },
    { name: 'Niter kibbeh (spiced butter)', amount: '3', unit: 'tbsp', notes: 'or regular butter' },
    { name: 'Onion', amount: '2', notes: 'finely diced' },
    { name: 'Berbere spice blend', amount: '2', unit: 'tbsp' },
    { name: 'Garlic', amount: '4', unit: 'cloves', notes: 'minced' },
    { name: 'Ginger', amount: '1', unit: 'tsp', notes: 'grated' },
    { name: 'Tomato', amount: '2', notes: 'diced' },
    { name: 'Water or broth', amount: '4', unit: 'cups' },
  ],
  steps: [
    { step: 1, instruction: 'Cook onions in niter kibbeh very slowly for 20 min until deep golden.', tip: 'This caramelized onion base is the foundation of all Ethiopian wat stews' },
    { step: 2, instruction: 'Add garlic and ginger, 2 min. Add berbere, stir constantly 3 min.' },
    { step: 3, instruction: 'Add tomatoes, cook until softened. Add rinsed lentils and water.' },
    { step: 4, instruction: 'Simmer 25 min, stirring often, until lentils are very soft and thick.' },
    { step: 5, instruction: 'Serve on injera bread, scooped up with torn pieces of injera.' },
  ],
  kidHelperTasks: ['Rinse lentils', 'Stir the lentils while simmering', 'Tear the injera into pieces for scooping'],
  nutritionNotes: 'Excellent plant protein. Berbere spices are anti-inflammatory. Complete meal with injera.',
  nutritionFacts: { calories: 310, protein: 18, carbs: 48, fat: 7, fiber: 12 },
  culturalHistory: 'Misir wat is one of Ethiopia\'s most important dishes, especially during fasting periods (Christian Orthodox Ethiopians fast up to 200 days per year, eating vegan). Berbere spice is considered the soul of Ethiopian cooking.',
  aiHint: 'The long-cooked caramelized onion base (20 min minimum) is what separates good wat from great.',
  homeschoolLesson: {
    subject: 'Religion & Culture: Ethiopian Orthodox Christianity', ageRange: '6-12', duration: 35,
    activity: 'Research Ethiopian Orthodox fasting traditions. Create a chart of what foods are eaten vs avoided. Discuss how religion shapes food culture.',
    discussion: ['Why do some religions have food rules?', 'How does fasting for 200 days shape a cuisine?', 'What other religions have food traditions?'],
    funFacts: ['Ethiopia has one of the oldest Christian churches in the world (4th century)', 'Ethiopians fast 200+ days per year and have hundreds of vegan recipes as a result', 'Injera is made from teff, a grain that only grows in Ethiopia'],
    vocabulary: [{ word: 'Berbere', definition: 'Ethiopian spice blend with chili, ginger, fenugreek, and more' }, { word: 'Injera', definition: 'Spongy Ethiopian flatbread made from teff flour' }, { word: 'Wat', definition: 'Ethiopian word for stew' }],
  },
};

export const doroWatRecipe: Recipe = {
  id: 'doro-wat', name: 'Doro Wat (Chicken Stew)', cultureId: 'ethiopian', cultureName: 'Ethiopian',
  emoji: '🍗', isFeatured: false, difficulty: 'medium', prepTime: 20, cookTime: 90, servings: 4,
  description: 'Rich, dark chicken stew slow-cooked in berbere spice sauce with hard-boiled eggs — Ethiopia\'s national dish.',
  tags: ['chicken', 'stew', 'berbere', 'eggs', 'national dish'],
  ingredients: [
    { name: 'Chicken pieces', amount: '3', unit: 'lbs', notes: 'scored with deep cuts' },
    { name: 'Onions', amount: '4', notes: 'finely diced (a lot — this is intentional)' },
    { name: 'Niter kibbeh', amount: '1/4', unit: 'cup' },
    { name: 'Berbere', amount: '3', unit: 'tbsp' },
    { name: 'Garlic', amount: '6', unit: 'cloves', notes: 'minced' },
    { name: 'Ginger', amount: '2', unit: 'tsp', notes: 'grated' },
    { name: 'Hard-boiled eggs', amount: '4', notes: 'peeled and pierced' },
    { name: 'Red wine', amount: '1/4', unit: 'cup', notes: 'optional' },
    { name: 'Lemon juice', amount: '2', unit: 'tbsp' },
  ],
  steps: [
    { step: 1, instruction: 'Cook onions dry (no oil) in pot for 20 min on medium, stirring constantly until dark.', tip: 'Dry-cooking onions first is a unique Ethiopian technique that removes water' },
    { step: 2, instruction: 'Add niter kibbeh, garlic, and ginger. Cook 5 min.' },
    { step: 3, instruction: 'Add berbere, cook 5 min stirring. Add wine if using.' },
    { step: 4, instruction: 'Add chicken with 1 cup water. Cover, simmer 45 min.' },
    { step: 5, instruction: 'Pierce hard-boiled eggs all over with fork. Add to stew, simmer 15 min. Serve on injera.' },
  ],
  kidHelperTasks: ['Pierce eggs with fork', 'Measure berbere spice', 'Stir the onions (with supervision)'],
  nutritionNotes: 'High protein from chicken and eggs. Berbere provides antioxidants. Rich and filling.',
  nutritionFacts: { calories: 480, protein: 42, carbs: 18, fat: 26, fiber: 4 },
  culturalHistory: 'Doro wat is Ethiopia\'s national dish, served at Christmas, Easter, and weddings. The hard-boiled eggs symbolize fertility and are an essential component. It is always eaten communally from a shared plate on injera.',
  aiHint: 'Dry-cooking the onions (no oil) for 20 min before adding fat is the unique key technique.',
  homeschoolLesson: {
    subject: 'Culture: Communal Eating Traditions', ageRange: '6-12', duration: 25,
    activity: 'Set up an Ethiopian-style communal meal. Eat from one shared plate with injera — no utensils. Discuss the experience.',
    discussion: ['How does eating from one plate change the experience?', 'What does communal eating teach about sharing?', 'How do other cultures share meals?'],
    funFacts: ['Ethiopians eat without utensils — injera IS the utensil', 'Sharing food from one plate is called "gursha" and is a sign of love', 'Coffee was discovered in Ethiopia and is still ceremonially brewed there today'],
    vocabulary: [{ word: 'Gursha', definition: 'The Ethiopian act of feeding someone else from your hand, a sign of love' }, { word: 'Communal', definition: 'Shared by everyone together' }, { word: 'Niter kibbeh', definition: 'Ethiopian spiced clarified butter with onions, garlic, and spices' }],
  },
};

export const feijoadaRecipe: Recipe = {
  id: 'feijoada', name: 'Feijoada', cultureId: 'brazilian', cultureName: 'Brazilian',
  emoji: '🫕', isFeatured: true, difficulty: 'hard', prepTime: 20, cookTime: 180, servings: 8,
  description: 'Brazil\'s national dish — black bean and pork stew slow-cooked all day, served with rice, farofa, and orange slices.',
  tags: ['black beans', 'pork', 'stew', 'national dish', 'weekend'],
  ingredients: [
    { name: 'Dried black beans', amount: '2', unit: 'lbs', notes: 'soaked overnight' },
    { name: 'Pork shoulder', amount: '1', unit: 'lb', notes: 'cubed' },
    { name: 'Chorizo sausage', amount: '8', unit: 'oz', notes: 'sliced' },
    { name: 'Bacon', amount: '6', unit: 'oz', notes: 'diced' },
    { name: 'Smoked pork ribs', amount: '8', unit: 'oz' },
    { name: 'Onion', amount: '2', notes: 'diced' },
    { name: 'Garlic', amount: '8', unit: 'cloves', notes: 'minced' },
    { name: 'Bay leaves', amount: '4' },
    { name: 'Oranges', amount: '2', notes: 'sliced, for serving' },
    { name: 'White rice', amount: '4', unit: 'cups', notes: 'cooked, for serving' },
  ],
  steps: [
    { step: 1, instruction: 'Drain soaked beans. Cover with fresh water and cook 1 hour until partially tender.' },
    { step: 2, instruction: 'In a separate pot, render bacon, then brown pork shoulder. Add chorizo and smoked ribs.' },
    { step: 3, instruction: 'Add onion and garlic to meat pot, cook 5 min. Add beans with their cooking liquid.' },
    { step: 4, instruction: 'Add bay leaves, simmer everything together 2+ hours, stirring occasionally.', tip: 'Mash a few beans against the side to thicken the sauce naturally' },
    { step: 5, instruction: 'Adjust salt. Serve with white rice, orange slices (to cut richness), and farofa (toasted cassava flour).' },
  ],
  kidHelperTasks: ['Rinse soaked beans', 'Slice oranges with adult help', 'Stir the pot', 'Measure rice'],
  nutritionNotes: 'Extremely filling and nutrient-dense. High in iron, protein, and fiber. Orange slices aid iron absorption.',
  nutritionFacts: { calories: 620, protein: 42, carbs: 65, fat: 22, fiber: 16 },
  culturalHistory: 'Feijoada was created by enslaved Africans in Brazil who used the pork parts discarded by slaveholders (feet, ears, tails) and combined them with black beans. It became Brazil\'s national dish and is eaten every Saturday.',
  aiHint: 'Mash some beans against the pot wall — this thickens the broth without any starch.',
  homeschoolLesson: {
    subject: 'History: African Diaspora in Brazil', ageRange: '6-12', duration: 40,
    activity: 'Research the African cultural influence in Brazil. Map the slave trade routes to Brazil. Discuss how enslaved people preserved their culture through food.',
    discussion: ['How did enslaved Africans shape Brazilian culture?', 'Why is it important to know who created our food?', 'What other parts of Brazilian culture come from Africa?'],
    funFacts: ['Brazil received more enslaved Africans than any other country — 5 million people', 'Saturday is traditional feijoada day across all of Brazil', 'Capoeira, samba, and candomblé religion all came from African traditions in Brazil'],
    vocabulary: [{ word: 'Diaspora', definition: 'People scattered from their homeland to other places' }, { word: 'Farofa', definition: 'Toasted cassava flour, eaten as a side dish in Brazil' }, { word: 'Cassava', definition: 'A starchy root vegetable native to South America' }],
  },
};

export const paodeQueijoRecipe: Recipe = {
  id: 'pao-de-queijo', name: 'Pão de Queijo (Cheese Bread)', cultureId: 'brazilian', cultureName: 'Brazilian',
  emoji: '🧀', isFeatured: false, difficulty: 'easy', prepTime: 10, cookTime: 20, servings: 20,
  description: 'Irresistible gluten-free Brazilian cheese bread rolls — crispy outside, chewy-stretchy inside.',
  tags: ['bread', 'cheese', 'gluten-free', 'snack', 'breakfast'],
  ingredients: [
    { name: 'Tapioca flour', amount: '2', unit: 'cups' },
    { name: 'Parmesan cheese', amount: '1', unit: 'cup', notes: 'freshly grated' },
    { name: 'Eggs', amount: '2' },
    { name: 'Milk', amount: '1/2', unit: 'cup' },
    { name: 'Vegetable oil', amount: '1/3', unit: 'cup' },
    { name: 'Salt', amount: '1', unit: 'tsp' },
  ],
  steps: [
    { step: 1, instruction: 'Preheat oven to 375°F. Grease a mini muffin tin or baking sheet.' },
    { step: 2, instruction: 'Blend all ingredients in a blender or food processor until smooth.', tip: 'Batter will be very liquid — this is normal for tapioca' },
    { step: 3, instruction: 'Pour batter into prepared tin, filling each cup 3/4 full.' },
    { step: 4, instruction: 'Bake 18–22 min until puffed and golden. They will deflate slightly as they cool — that\'s OK.' },
    { step: 5, instruction: 'Eat warm! Best within 10 minutes of baking.' },
  ],
  kidHelperTasks: ['Press the blender button', 'Pour batter into muffin tin', 'Watch them puff up through the oven window'],
  nutritionNotes: 'Naturally gluten-free. High in calcium and protein from cheese. Quick energy snack.',
  nutritionFacts: { calories: 95, protein: 3, carbs: 12, fat: 4, fiber: 0 },
  culturalHistory: 'Pão de queijo originated in the state of Minas Gerais, Brazil, where enslaved people ground leftover tapioca starch into a dough. Cheese was added when dairy farming arrived. Today they are Brazil\'s most popular snack.',
  aiHint: 'Use a blender, not a stand mixer — the liquid batter needs thorough emulsification.',
  homeschoolLesson: {
    subject: 'Science: Gluten-Free Baking', ageRange: '6-12', duration: 25,
    activity: 'Compare a flour bread roll and pão de queijo. Stretch both when warm. Discuss what makes tapioca stretchy.',
    discussion: ['Why does tapioca make bread chewy without gluten?', 'What is gluten and who can\'t eat it?', 'What other gluten-free grains do you know?'],
    funFacts: ['Tapioca comes from cassava root, native to South America', 'Pão de queijo is sold at every Brazilian airport, bakery, and gas station', 'Minas Gerais state is famous for both cheese and music in Brazil'],
    vocabulary: [{ word: 'Tapioca', definition: 'Starch extracted from cassava root' }, { word: 'Gluten', definition: 'Protein in wheat that makes bread stretchy' }, { word: 'Emulsify', definition: 'To mix two liquids that don\'t normally combine, like oil and water' }],
  },
};

export const chickenTagineRecipe: Recipe = {
  id: 'chicken-tagine', name: 'Chicken Tagine with Preserved Lemon & Olives', cultureId: 'moroccan', cultureName: 'Moroccan',
  emoji: '🏺', isFeatured: true, difficulty: 'medium', prepTime: 20, cookTime: 90, servings: 4,
  description: 'Slow-braised chicken with preserved lemon, green olives, and saffron in a conical clay pot (or heavy pot).',
  tags: ['chicken', 'slow-braised', 'preserved lemon', 'saffron', 'Moroccan'],
  ingredients: [
    { name: 'Chicken pieces', amount: '3', unit: 'lbs' },
    { name: 'Preserved lemon', amount: '1', notes: 'rinsed, pulp removed, rind sliced' },
    { name: 'Green olives', amount: '1', unit: 'cup' },
    { name: 'Onions', amount: '2', notes: 'grated' },
    { name: 'Garlic', amount: '4', unit: 'cloves', notes: 'minced' },
    { name: 'Saffron', amount: '1/2', unit: 'tsp', notes: 'bloomed in 2 tbsp warm water' },
    { name: 'Ginger', amount: '1', unit: 'tsp', notes: 'ground' },
    { name: 'Cumin', amount: '1', unit: 'tsp' },
    { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
    { name: 'Cilantro and parsley', amount: '1', unit: 'cup combined', notes: 'chopped' },
    { name: 'Olive oil', amount: '3', unit: 'tbsp' },
  ],
  steps: [
    { step: 1, instruction: 'Marinate chicken in grated onion, garlic, spices, and olive oil for 1 hour.' },
    { step: 2, instruction: 'Brown chicken in a heavy pot or tagine over medium-high heat.' },
    { step: 3, instruction: 'Add saffron water, 1/2 cup water, and herbs. Bring to simmer.' },
    { step: 4, instruction: 'Cover tightly and cook on low heat 60 min until very tender.', tip: 'Low and slow — do not rush the braise' },
    { step: 5, instruction: 'Add preserved lemon and olives in the last 10 min. Serve with couscous.' },
  ],
  kidHelperTasks: ['Bloom saffron in water', 'Add olives to the pot', 'Stir the marinade'],
  nutritionNotes: 'High protein. Olives and olive oil provide heart-healthy monounsaturated fats.',
  nutritionFacts: { calories: 440, protein: 38, carbs: 14, fat: 26, fiber: 3 },
  culturalHistory: 'The tagine (the conical clay pot) has been used in North Africa for 2,000+ years. Morocco\'s cuisine fuses Berber, Arab, Andalusian, and French influences. Preserved lemon is a Moroccan pantry staple made by fermenting lemons in salt.',
  aiHint: 'The preserved lemon is added late — long cooking destroys its delicate floral flavor.',
  homeschoolLesson: {
    subject: 'History: Silk Road & Spice Trade', ageRange: '6-12', duration: 40,
    activity: 'Map the Silk Road. Trace where Morocco\'s spices (saffron, ginger, cumin) originated. Draw a spice trade route.',
    discussion: ['Why were spices so valuable historically?', 'How did Morocco benefit from being at the crossroads of Africa and Europe?', 'What would food taste like without spices?'],
    funFacts: ['Saffron is worth more than gold by weight', 'Morocco was a major stop on ancient trade routes between Africa, Europe, and Asia', 'The city of Fez has a medina (old city) that hasn\'t changed in 1,200 years'],
    vocabulary: [{ word: 'Tagine', definition: 'Both the conical clay pot and the stew cooked inside it' }, { word: 'Preserved lemon', definition: 'Lemons fermented in salt — a key Moroccan ingredient' }, { word: 'Saffron', definition: 'The world\'s most expensive spice, from crocus flowers' }],
  },
};

export const hariraRecipe: Recipe = {
  id: 'harira', name: 'Harira (Spiced Tomato & Lentil Soup)', cultureId: 'moroccan', cultureName: 'Moroccan',
  emoji: '🍵', isFeatured: false, difficulty: 'easy', prepTime: 15, cookTime: 60, servings: 6,
  description: 'Hearty Moroccan soup of tomatoes, chickpeas, and lentils spiced with cinnamon, ginger, and saffron.',
  tags: ['soup', 'lentils', 'chickpeas', 'Ramadan', 'vegetarian'],
  ingredients: [
    { name: 'Canned tomatoes', amount: '28', unit: 'oz', notes: 'crushed' },
    { name: 'Chickpeas', amount: '1', unit: 'can', notes: 'drained' },
    { name: 'Red lentils', amount: '1/2', unit: 'cup' },
    { name: 'Onion', amount: '1', notes: 'diced' },
    { name: 'Celery', amount: '2', unit: 'stalks', notes: 'diced' },
    { name: 'Cinnamon', amount: '1', unit: 'tsp' },
    { name: 'Ginger', amount: '1', unit: 'tsp', notes: 'ground' },
    { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
    { name: 'Saffron', amount: '1/4', unit: 'tsp' },
    { name: 'Lemon juice', amount: '2', unit: 'tbsp' },
    { name: 'Fresh cilantro', amount: '1/2', unit: 'cup' },
    { name: 'Flour', amount: '2', unit: 'tbsp', notes: 'mixed with water to thicken' },
  ],
  steps: [
    { step: 1, instruction: 'Sauté onion and celery in olive oil until soft, 8 min.' },
    { step: 2, instruction: 'Add spices and ginger, stir 1 min.' },
    { step: 3, instruction: 'Add tomatoes, chickpeas, lentils, and 5 cups water. Simmer 30 min.' },
    { step: 4, instruction: 'Mix flour with 1/4 cup water. Stir into soup to thicken. Simmer 10 more min.' },
    { step: 5, instruction: 'Add lemon juice and cilantro. Adjust salt. Serve with dates and bread.' },
  ],
  kidHelperTasks: ['Drain chickpeas', 'Stir in cilantro', 'Squeeze lemon', 'Mix the flour-water thickener'],
  nutritionNotes: 'Very high fiber and plant protein. Cinnamon is anti-inflammatory. Low fat, very filling.',
  nutritionFacts: { calories: 240, protein: 12, carbs: 40, fat: 4, fiber: 11 },
  culturalHistory: 'Harira is Morocco\'s most important soup, traditionally used to break the Ramadan fast each evening at sunset. It is also served at weddings and celebrations. The combination of spices reflects Morocco\'s position on ancient trade routes.',
  aiHint: 'The flour-water slurry is traditional for thickening harira — it creates a unique silky body.',
  homeschoolLesson: {
    subject: 'Religion & Culture: Ramadan Traditions', ageRange: '6-12', duration: 30,
    activity: 'Learn about Ramadan. Compare it to other religious fasting traditions (Jewish Yom Kippur, Christian Lent, Hindu Navratri).',
    discussion: ['Why do different religions have fasting traditions?', 'How does waiting for food make you appreciate it more?', 'What foods do other cultures eat to break a fast?'],
    funFacts: ['Ramadan is observed by 1.8 billion Muslims worldwide', 'Morocco serves harira with dates and chebakia (honey cookies) to break the Ramadan fast', 'The word harira comes from Arabic meaning "silky"'],
    vocabulary: [{ word: 'Ramadan', definition: 'The Islamic holy month of fasting from sunrise to sunset' }, { word: 'Iftar', definition: 'The meal eaten to break the Ramadan fast at sunset' }, { word: 'Slurry', definition: 'A mixture of flour or starch and water used to thicken soups' }],
  },
};

export const recipes: Recipe[] = [
  adoboRecipe, sinigangRecipe,
  tamalesRecipe, moleRecipe,
  phoRecipe, springRollsRecipe,
  ghormehSabziRecipe, tahdigRecipe,
  biryaniRecipe, dalTadkaRecipe,
  friedChickenRecipe, shrimpGritsRecipe,
  hummusRecipe, shakshukaRecipe,
  ramenRecipe, onigiriRecipe,
  bibimbapRecipe, japchaelRecipe,
  jollofRiceRecipe, egusiSoupRecipe,
  misirWatRecipe, doroWatRecipe,
  feijoadaRecipe, paodeQueijoRecipe,
  chickenTagineRecipe, hariraRecipe,
];

export function getRecipeById(id: string): Recipe | undefined {
  return recipes.find((r) => r.id === id);
}

export function getRecipesByCulture(cultureId: string): Recipe[] {
  return recipes.filter((r) => r.cultureId === cultureId);
}
